<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>cd48235c-35c0-47ac-a436-12aee1716264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnCreatePayment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCreatePayment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pslogosubmit >> internal:text=&quot;Submit&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6daa254d-101e-4981-afd8-93117da5e14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-raised submitButton</value>
      <webElementGuid>99b2f4d8-4a3e-437b-85c1-4b98f57e84f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCreatePayment</value>
      <webElementGuid>27fa868f-b02f-4f54-9fec-0b004b6a8b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paymentaction</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>16f7d025-078c-4ebd-a787-6e39deeea3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit </value>
      <webElementGuid>1c387af0-3b26-4cc2-8c7d-f3114d99e1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pslogosubmit&quot;)/a[@id=&quot;btnCreatePayment&quot;]</value>
      <webElementGuid>60fe6d07-6050-47b8-988f-037a869ba238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnCreatePayment']</value>
      <webElementGuid>20448f8b-9fc9-41bc-9880-fe0d47dcacc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pslogosubmit']/a</value>
      <webElementGuid>70dd5221-3a5d-4309-a54b-7712da6ab165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Submit')])[3]</value>
      <webElementGuid>a0309f64-78a8-4be6-98ca-c7a7cb088934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::a[2]</value>
      <webElementGuid>21c19705-f0ce-4494-b076-b7904ef6b98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>9469faa1-3500-466c-baa8-331416270e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnCreatePayment' and (text() = 'Submit ' or . = 'Submit ')]</value>
      <webElementGuid>e4d639e1-d991-49c8-9020-4e90b6698c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
