<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please select --5 Panel Drug Scre_1a9916</name>
   <tag></tag>
   <elementGuidId>1523579a-52f1-4460-b83d-326d1d988af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bd_service_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bd_service_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bd_service_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>73bacabb-5b8c-4b6a-b1ad-60039fe58f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_id</value>
      <webElementGuid>42050a5d-9eb8-4c15-bd6a-3d00e482468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bd_service_id</value>
      <webElementGuid>829b34e6-51ac-438e-a2e6-af16326c3345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capfield</value>
      <webElementGuid>fba3b919-de8b-4121-a27e-d74989599e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>868682e2-9714-4594-94ea-d76a1ef861f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please select --5 Panel Drug ScreenAssessmentDetoxificationIOPIndividual SessionIntroduction Of Cardiac Pacemaker System Via VeinNebulizer TherapyOutpatientTake Back</value>
      <webElementGuid>760403e5-e713-408d-aa7f-c2b28342dfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bd_service_id&quot;)</value>
      <webElementGuid>d1240974-6369-406e-bd81-47824dd03e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bd_service_id']</value>
      <webElementGuid>b9cf752d-3a8a-497b-b507-49eae3725666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serviceInfo']/div/div/select</value>
      <webElementGuid>d9e2fd78-bbc1-4c0d-9cc7-3df7682977ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service:'])[1]/following::select[1]</value>
      <webElementGuid>7775df1e-48c5-46b5-a8c7-579be127a221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission:'])[2]/following::select[2]</value>
      <webElementGuid>645e878c-66b8-4fb5-83de-f81966af2d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/select</value>
      <webElementGuid>3af3a071-dc82-4655-9d01-4038c1585876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'service_id' and @id = 'bd_service_id' and (text() = '-- Please select --5 Panel Drug ScreenAssessmentDetoxificationIOPIndividual SessionIntroduction Of Cardiac Pacemaker System Via VeinNebulizer TherapyOutpatientTake Back' or . = '-- Please select --5 Panel Drug ScreenAssessmentDetoxificationIOPIndividual SessionIntroduction Of Cardiac Pacemaker System Via VeinNebulizer TherapyOutpatientTake Back')]</value>
      <webElementGuid>a20bc48e-0dbd-482e-ab20-58937367b98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
