<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight for Length Percentile_weight_f_b1f33b</name>
   <tag></tag>
   <elementGuidId>265ae6dd-3428-4e53-83c5-d018444ebcee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weight_for_length_percentile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weight_for_length_percentile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Weight for Length Percentile:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2be0d84a-a7b2-4794-8575-e417e1de3405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c3660c7f-b370-4d24-b0b0-a50e1228132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weight_for_length_percentile</value>
      <webElementGuid>2af8af2a-990c-4b97-aeb0-b8523f2f7780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight_for_length_percentile</value>
      <webElementGuid>c00eb451-f6ef-4046-a0a9-6156449d6a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>17600351-ff86-4cdd-a306-f1365ae51767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight_for_length_percentile&quot;)</value>
      <webElementGuid>6c6325d1-8198-4754-9b34-7bd7ce794204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weight_for_length_percentile']</value>
      <webElementGuid>c9b43449-e65b-40ae-baab-fcf9fca7b0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='generated::OPVdlrfllrlC5u4i']/div[2]/div/form/div/div/div[4]/div/div/input</value>
      <webElementGuid>62c96179-6325-4867-b74a-1de5d614a856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>76f94849-63b9-4ca3-9485-9ebc6379da7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'weight_for_length_percentile' and @id = 'weight_for_length_percentile']</value>
      <webElementGuid>50e09037-7722-485b-ace1-cf0b8e8812ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
