<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chargeQueue</name>
   <tag></tag>
   <elementGuidId>eb74cb97-c59b-488d-85a4-ef6c54f4fb80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='chargequeue']//div[@class='large']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CHARGES QUEUE $31.9K Total. 65&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ba99ea1-3597-49f6-bd9a-f449030c025f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>5a0419df-e0b9-4891-82eb-6c3217e2cf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$31.9K
                                                                    </value>
      <webElementGuid>5b4d0bf6-92ad-40bf-9166-792af8780a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chargequeue&quot;)/div[@class=&quot;rounded panel panel-primary&quot;]/div[@class=&quot;rounded panel-heading&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;large&quot;]</value>
      <webElementGuid>e149144c-d441-4af1-853c-30a264571c40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='chargequeue']/div/div/div/div/div[2]</value>
      <webElementGuid>92af78ad-db16-4c4e-a033-6905ce0e9614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHARGES QUEUE'])[1]/following::div[1]</value>
      <webElementGuid>8acc68b8-a4f1-4b50-b74b-a8f2ba3dbc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAIMS QUEUE'])[1]/preceding::div[4]</value>
      <webElementGuid>59b885e3-bc16-4c63-82d8-3a1ce6b7209f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$']/parent::*</value>
      <webElementGuid>b136a6fe-0774-459f-a448-e0b352488785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div/div/div[2]</value>
      <webElementGuid>18111eff-d709-458e-8e6e-64a3fc588f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$31.9K
                                                                    ' or . = '$31.9K
                                                                    ')]</value>
      <webElementGuid>fc913662-05b3-49d1-9c80-c130df661374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
