<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Connections Progress Note</name>
   <tag></tag>
   <elementGuidId>5abb9b74-4649-41b7-a66c-35a9c100e091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dashboardunbilled']/tbody/tr/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Connections Progress Note&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b5da652a-9e13-4f51-823d-dd97c6634412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connections Progress Note</value>
      <webElementGuid>b3744299-8100-4672-a5d3-8b0822d47067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardunbilled&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]</value>
      <webElementGuid>a4944064-f047-4ea6-a828-cbf3288460c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dashboardunbilled']/tbody/tr/td[6]</value>
      <webElementGuid>f2605988-1c1c-47d9-961f-4096c26a45f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magellan'])[2]/following::td[1]</value>
      <webElementGuid>00d8d891-b832-4944-a07a-08b82b990d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C Client C Automation'])[1]/following::td[3]</value>
      <webElementGuid>3de79a2e-2dc1-4ab6-8e54-2c451f096a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance'])[2]/preceding::td[3]</value>
      <webElementGuid>9bf546d8-88e2-4258-a3e4-06008ad91f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satellite Office'])[3]/preceding::td[4]</value>
      <webElementGuid>a00a1608-12f8-4921-8ac4-1385e757c303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>3968de47-520e-406e-9202-5380459b89f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Connections Progress Note' or . = 'Connections Progress Note')]</value>
      <webElementGuid>65bd3e45-1f28-4919-916b-25dff3f27cc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
