<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>22684ac0-8a3a-4a8e-a483-9a38b4233de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnmainfrmsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnmainfrmsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdaa1586-aae4-4c2a-bc93-706cbdb1ef43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-raised btn-primary btn-block locker nodoubleclick topazsig</value>
      <webElementGuid>6ea33f64-cfc7-44d0-9936-0f05f2917273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ab0403be-c958-4822-ab03-211cd7d2dd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>09cc060c-f025-491b-855a-78d6d806c0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmainfrmsubmit</value>
      <webElementGuid>678d1f74-15d9-42e0-985e-77ee54350c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save
        </value>
      <webElementGuid>07befc69-b7a3-4514-bccd-d4e2aee459a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnmainfrmsubmit&quot;)</value>
      <webElementGuid>96bda190-f123-4376-b2b9-77e60aceb230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnmainfrmsubmit']</value>
      <webElementGuid>a29fef08-8e0e-4d91-a6f4-1e3dfc481189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit_imaging_order']/div[2]/div/form/div[7]/div/button</value>
      <webElementGuid>563fd85f-d230-4a0c-bf80-68cdeab8f9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interpretation:'])[1]/following::button[1]</value>
      <webElementGuid>0f1d2d2c-d1c8-4d66-a98f-ad19af176d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creator / Last Editor Name - Automation Test'])[1]/preceding::button[1]</value>
      <webElementGuid>ecde0d5f-f276-4934-bc63-ad4be722841a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>e3bdec61-d610-4518-a36e-bc0526e5d278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>50686c00-8d4c-4655-b73a-e132c02cf86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and @id = 'btnmainfrmsubmit' and (text() = ' Save
        ' or . = ' Save
        ')]</value>
      <webElementGuid>1e6b77ae-0ed1-4058-9459-de1f7601dd66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
