<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign and Lock_dss</name>
   <tag></tag>
   <elementGuidId>ab6f80f0-0a16-406d-b09e-ab3516bebe4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign and Lock&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d31801ad-9b09-464f-89ee-3abd90da78c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f0662041-2234-4117-97ae-434bde40bc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>40238804-b72b-4a32-a6ef-f123dc557fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>4990e92b-0bc8-43f1-9fe4-100dea545a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8e1eee6b-7639-43f8-9991-7cfb98ffd34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkcosign locker</value>
      <webElementGuid>f77b4201-2f6e-4a96-ad9a-5470168b430e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dss&quot;)</value>
      <webElementGuid>8ff09ba5-e6d9-48d1-9a55-9f68ad2ac810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dss']</value>
      <webElementGuid>16cc166f-2000-4aac-9947-d609ab34477b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainDssSection']/div/label/input</value>
      <webElementGuid>008a97fb-0fe1-45f9-9f3d-91fd40b48525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/div/div/label/input</value>
      <webElementGuid>579d296c-aad1-4840-9125-3151cbdd4a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'dss' and @id = 'dss']</value>
      <webElementGuid>34f6147b-b0fc-4590-9b40-1d2f5d59f715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
