<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CT Abdomen</name>
   <tag></tag>
   <elementGuidId>1165e9ab-59cb-46c0-b716-b6adfc044b0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-imagingOrders-result-jsmr-603913</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-imagingOrders-result-jsmr-603913']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;CT Abdomen&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>155b7d55-a48b-4860-8640-96a2eafe2e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>c7a64c5a-ea02-4b6b-bf6c-528a0d4bcfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-imagingOrders-result-jsmr-603913</value>
      <webElementGuid>55058fa7-84d3-49a8-92f5-c4d8dcd93101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>29ffc193-b08b-4c24-bda5-90aa0bf8baab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04a780e4-7b5f-4579-8fca-578d464b3558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CT Abdomen</value>
      <webElementGuid>92260f7e-88d9-4c7d-9196-a429a4fc86e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-imagingOrders-result-jsmr-603913&quot;)</value>
      <webElementGuid>19d521f9-5cb0-4592-b50f-c9d0178d7ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-imagingOrders-result-jsmr-603913']</value>
      <webElementGuid>6ba70a80-31dd-43b2-8966-401fa881983c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-imagingOrders-results']/li</value>
      <webElementGuid>a0163b08-bad0-4460-8709-12cb8b0b30bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0 entries'])[1]/following::li[3]</value>
      <webElementGuid>728070eb-74e6-4d9a-a719-d7b141dc5015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT Chest'])[2]/preceding::li[1]</value>
      <webElementGuid>e47aa104-5f49-45ee-b210-8b3b6418707c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CT extremity study'])[2]/preceding::li[2]</value>
      <webElementGuid>d467d13b-d85c-4a7a-a338-cefbe4b60b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>7714d8d7-0284-4f54-ba2b-cff9ced0a075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-imagingOrders-result-jsmr-603913' and (text() = 'CT Abdomen' or . = 'CT Abdomen')]</value>
      <webElementGuid>f39b5049-0b86-4fac-ad82-57fc6c86dd0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
