<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Calendar</name>
   <tag></tag>
   <elementGuidId>f6acd254-2122-45ce-9e42-5591e3796675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainMenu']/div/div[2]/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Calendar&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83105d2d-3af5-4352-8090-6d5651e2ec12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://site17.lsapp.cloud/calendar</value>
      <webElementGuid>223f6af3-3422-4d07-a02b-02d0c57123d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Calendar
                        </value>
      <webElementGuid>f0f3f4e5-e293-4675-a8c0-95a3dccb9085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/div[@class=&quot;menu-section&quot;]/div[@class=&quot;menu-section--content opened&quot;]/div[@class=&quot;menu-section--content--item&quot;]/div[@class=&quot;item-label&quot;]/a[1]</value>
      <webElementGuid>56215655-664c-48ac-b09b-0ad9d4a62b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']/div/div[2]/div[4]/div/a</value>
      <webElementGuid>87e57356-2707-4dad-96b5-819915f7c4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Calendar')]</value>
      <webElementGuid>dc4ea347-4093-4be0-9143-3fb83baa8925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='calendar_month'])[2]/following::a[1]</value>
      <webElementGuid>ac2bb073-578f-47b0-a92e-c9208a8ae8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caseload'])[1]/following::a[1]</value>
      <webElementGuid>2a6a10af-0c22-4447-a687-adbada94b83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='group'])[1]/preceding::a[1]</value>
      <webElementGuid>2fd99969-158e-42af-9267-5101ea4b0c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inquiries'])[2]/preceding::a[1]</value>
      <webElementGuid>f5bbc7b2-f413-43f9-9eb7-4e053ede6a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calendar']/parent::*</value>
      <webElementGuid>78940b92-ff55-44ad-ba64-485db6a4eab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://site17.lsapp.cloud/calendar')])[2]</value>
      <webElementGuid>ef4fb319-fd3d-468a-a22c-72265da792c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>12c21aa9-3152-4983-a93d-c37dfc2b790a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://site17.lsapp.cloud/calendar' and (text() = '
                            Calendar
                        ' or . = '
                            Calendar
                        ')]</value>
      <webElementGuid>c960bbc1-76c7-49f7-b2ae-2aca79e301a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
