<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MotivatedWillingAmbivalentResistant</name>
   <tag></tag>
   <elementGuidId>0d940b7c-c14e-41bd-b670-2d3c88658963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtfamilysupport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtfamilysupport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Client Initial Response to Treatment Upon Admission:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>663d39d2-fad9-427c-b445-ca13db297718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtfamilysupport</value>
      <webElementGuid>39872a56-f37f-466a-ae36-367e2eb9ea4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfamilysupport</value>
      <webElementGuid>18a58fd8-944e-40e0-bff8-d2ea9698310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>554f8d17-3d28-42b5-87dc-01f55df617d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MotivatedWillingAmbivalentResistant</value>
      <webElementGuid>08193ea9-c2cf-4fb0-bc3a-5cb649180381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfamilysupport&quot;)</value>
      <webElementGuid>01bd2683-6773-408b-8db8-51e94bc0f46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtfamilysupport']</value>
      <webElementGuid>2a2229b1-47bd-44ef-8855-a5e7b3914be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='initdcplanform']/div[3]/div/div[7]/div/div/select</value>
      <webElementGuid>8e0f38c5-2aa8-4ac2-993f-8ad51ae53372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Initial Response to Treatment Upon Admission:'])[1]/following::select[1]</value>
      <webElementGuid>86e64e2f-1f81-45eb-9098-3f230382ee07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Recommendation Upon Discharge:'])[2]/following::select[1]</value>
      <webElementGuid>c91f4a37-a59c-4560-963e-00a5cdef272e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Family Initial Willingness to Participate in Treatment:'])[1]/preceding::select[1]</value>
      <webElementGuid>c770475b-b05f-4d56-8aa9-9cdcfec6fb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Initial Response to Treatment Upon Admission:'])[2]/preceding::select[2]</value>
      <webElementGuid>11a40006-199a-4786-823a-ea7e65d2d79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>a2511218-9afe-4f0f-934b-7ee6c04a29e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txtfamilysupport' and @id = 'txtfamilysupport' and (text() = 'MotivatedWillingAmbivalentResistant' or . = 'MotivatedWillingAmbivalentResistant')]</value>
      <webElementGuid>e50329aa-a89c-4f38-bd1b-e0f4f1f33307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
