<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Clinical Recommendation Upon Disch_4f87c6</name>
   <tag></tag>
   <elementGuidId>43dc2804-a4c7-44d8-ad57-5faf54ff11b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='needs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#needs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Clinical Recommendation Upon Discharge:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c6696c05-1153-4832-b719-5531b080c1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>needs</value>
      <webElementGuid>0c9bb612-47d8-463c-b4a7-21d67322ad0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>504d428f-3138-4d0b-95b5-a9236d2a8098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>375cb534-cbb4-4484-a900-58acfa8a7af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>needs</value>
      <webElementGuid>dd76b0ec-f3b8-4523-9d45-80c2496ffda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker autoupdate</value>
      <webElementGuid>7552be2f-a860-4a16-8f48-ddd61e43de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f6b5625e-d478-477b-a3d2-b29df6125f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;needs&quot;)</value>
      <webElementGuid>1be89fb9-1aa5-4c9d-9dc8-649734b7cd4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='needs']</value>
      <webElementGuid>c107c61a-24ab-459b-978b-3f3c13744cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='initdcplanform']/div[3]/div/div[5]/div/div/textarea</value>
      <webElementGuid>c131e747-cbb3-40ec-b2a8-5bf5176052c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/textarea</value>
      <webElementGuid>cb88068b-8313-4b7f-a207-55e12b8db9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'needs' and @id = 'needs']</value>
      <webElementGuid>d740d7e2-41e8-45f3-854a-c9319975f40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
