<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Completed</name>
   <tag></tag>
   <elementGuidId>d9951342-227a-402c-a70c-7c24eea4bae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbldcplans > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbldcplans']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Completed&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2156b616-4be3-45a2-ba6a-195cefb861dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
               Completed
                          </value>
      <webElementGuid>719785b7-f7c5-4915-884d-accd83f89878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dcplanblock&quot;)/div[@class=&quot;client-profile--content&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12&quot;]/div[@class=&quot;table-responsive-dummy&quot;]/table[@id=&quot;tbldcplans&quot;]/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>d152088b-e171-4c88-a0b2-bb9c74825e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbldcplans']/tbody/tr/td[4]</value>
      <webElementGuid>91a432a9-6df7-4395-9b44-4aafc93898c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[9]/following::td[1]</value>
      <webElementGuid>36a0c11b-3a38-4566-aca8-e63bfe9fa700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Multiple Programs'])[1]/following::td[2]</value>
      <webElementGuid>d4a25227-d019-45b4-81ee-229d13f38f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[39]/preceding::td[2]</value>
      <webElementGuid>805a2ab2-e7c2-4fca-9c30-9e2934e74ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discharge Medications List for E Client E Automation'])[1]/preceding::td[2]</value>
      <webElementGuid>e6fed99f-742d-4e00-8553-15d7f95f05c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>871f22ec-64dc-4e11-93f1-a75d4b1dbf41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
               Completed
                          ' or . = '
               Completed
                          ')]</value>
      <webElementGuid>5cd644c9-35c6-4589-8a6d-1c01b7fd3923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
