<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payor</name>
   <tag></tag>
   <elementGuidId>a911ec07-9c1d-4080-8d13-95517f44d6bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[normalize-space()='Payor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#censustoggle >> internal:text=&quot;Payor&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eba50251-f44d-45ec-861d-e811552df2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary dataTableToggleBEF986E9-9671-4A8E-8085-799E68CE8262 dropdown-item</value>
      <webElementGuid>50bcf0ed-dc9d-4ed5-9e3f-2865645e5066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a36352a9-090c-4036-8872-20d87772dec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tableid</name>
      <type>Main</type>
      <value>tblclients</value>
      <webElementGuid>fe701700-3a76-4958-ad95-343c387cab85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payor</value>
      <webElementGuid>84a31b05-750a-4232-91b5-9489e64976c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BEF986E9-9671-4A8E-8085-799E68CE8262&quot;)/a[@class=&quot;btn btn-secondary dataTableToggleBEF986E9-9671-4A8E-8085-799E68CE8262 dropdown-item&quot;]</value>
      <webElementGuid>2a60410c-b144-4579-9122-9ab32ec5de0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BEF986E9-9671-4A8E-8085-799E68CE8262']/a[12]</value>
      <webElementGuid>d231fb5d-979c-4ea0-bb25-1ad3c544b681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Payor')])[2]</value>
      <webElementGuid>2b1d0296-a3e2-47db-8865-894f2c636330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proj Discharge'])[1]/following::a[1]</value>
      <webElementGuid>0e93f67d-c096-4037-a317-0d03c0a8ef98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral Source'])[1]/following::a[2]</value>
      <webElementGuid>4bcd42ad-a766-4b9e-a6d6-4e07e8375ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::a[1]</value>
      <webElementGuid>7f2f337b-8b19-467e-9b7f-212a7121efa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payor'])[2]/preceding::a[1]</value>
      <webElementGuid>39046abb-c627-44dd-a094-d977ac46b0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payor']/parent::*</value>
      <webElementGuid>65e9eb0e-9ba6-4c5d-be43-55f757960d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[12]</value>
      <webElementGuid>00f06be7-0d02-4ba2-886b-dd76bc9f754a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Payor' or . = 'Payor')]</value>
      <webElementGuid>f7a204b0-d88e-4b3d-91c4-61ce133ecb1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
