<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Client Face sheets</name>
   <tag></tag>
   <elementGuidId>c6d31484-9e29-4006-834f-93870ae4e281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse1']/div/div[2]/div[3]/div/div[3]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;co_present Client Face sheets&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23a6471b-47ef-4379-8f51-e74a66114da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-label</value>
      <webElementGuid>58c6ba03-fa92-4822-8786-c6f108fc7236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client Face sheets</value>
      <webElementGuid>b8ee5db8-5371-47e1-9014-6527200c08bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row hidden-print&quot;]/div[@class=&quot;col-md-4 col-xs-12 home-census-buttons-container&quot;]/div[@class=&quot;btn-group pull-right text-right facesheet-new-buttons-icons&quot;]/div[@class=&quot;tooltip_census&quot;]/a[@class=&quot;main-yellow-a-btn&quot;]/span[@class=&quot;btn-label&quot;]</value>
      <webElementGuid>f4f12e40-87a9-4dcf-9cae-8770c58d59a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div[2]/div[3]/div/div[3]/a/span[2]</value>
      <webElementGuid>991630e6-618f-4f49-bfb2-019594a7f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='co_present'])[1]/following::span[1]</value>
      <webElementGuid>2b9cb784-2d1e-49df-a6d4-1b56d38c9e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Census'])[2]/following::span[2]</value>
      <webElementGuid>5d08cfaf-b6fd-45ce-83bf-9c1e4c88b50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Face Sheets'])[1]/preceding::span[1]</value>
      <webElementGuid>3dabad20-45ac-42b2-b596-e9edf89c2ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Client Face sheets']/parent::*</value>
      <webElementGuid>68d7f2c2-a1ba-4241-8962-d2ddf7dc6163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span[2]</value>
      <webElementGuid>68ed8773-77e7-4d3c-870c-5ada1a8f8e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Client Face sheets' or . = 'Client Face sheets')]</value>
      <webElementGuid>9f9664da-2ab6-4697-ac3e-38f6147de05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
