<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Automation Clinical Note test</name>
   <tag></tag>
   <elementGuidId>4f154168-88da-45cf-b64c-b95c9a5d252a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-1687188811798</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Note:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>60d65e1b-b56b-484b-a569-ec4ac247d12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>355d5474-cebc-468f-9bd3-aeef0bcd412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtautoheight hidden-print locker autoupdateformdata </value>
      <webElementGuid>ace3e47f-48cb-4c25-bf73-ccb3e21c0b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textarea-1687188811798</value>
      <webElementGuid>cdbc30b0-fad3-44c8-ad46-0a5dcd8708df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-1687188811798</value>
      <webElementGuid>70e34def-2b6c-4d37-b670-bf79230a8171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>frmdata</value>
      <webElementGuid>a4772a5a-f077-49b5-98ad-665fc378f631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>f2fe6439-f562-40c9-bab3-b9d0092f5a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>107</value>
      <webElementGuid>df1ac59e-b16f-4c46-990e-d244b4747f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Clinical Note test</value>
      <webElementGuid>136a0877-b215-4648-a26d-eae018051f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-1687188811798&quot;)</value>
      <webElementGuid>a935c939-3b16-404f-8a2b-f9ec7c3b3b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-1687188811798']</value>
      <webElementGuid>c9c7a8c3-4b97-469c-8fe3-23af49cda4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formdataFirstPanel']/div/div/div[6]/div/div/textarea</value>
      <webElementGuid>c7493400-5975-4bee-b3f9-b9bc7ab24701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::textarea[1]</value>
      <webElementGuid>eeda94c7-958c-4c05-ac72-a047e9d20430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Clinical Note B Client'])[1]/following::textarea[1]</value>
      <webElementGuid>a2dac2e3-ea30-4430-b529-8b0cfd7ae725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Clinical Note test'])[2]/preceding::textarea[1]</value>
      <webElementGuid>1b9026b1-cc36-4038-9cad-bf9b9ff0bd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automation Clinical Note test']/parent::*</value>
      <webElementGuid>463cd979-c0df-47e2-8161-d188a9e5990b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/textarea</value>
      <webElementGuid>554f18b2-0e29-42be-9d7b-4a198c8ddc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textarea-1687188811798' and @id = 'textarea-1687188811798' and @form = 'frmdata' and (text() = 'Automation Clinical Note test' or . = 'Automation Clinical Note test')]</value>
      <webElementGuid>8fd6fba0-02cb-4b45-b6e1-fa03f417721a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
