<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Unlock and Remove Signatures autom_7c0285</name>
   <tag></tag>
   <elementGuidId>59b1086a-ad9a-4ba9-beb7-a6409cf3dcd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-1687188811798']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-1687188811798</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Note:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>47497076-ae64-4e19-8dab-bb5e0aa01bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7964fb5f-a441-4415-8df5-83d107c8d7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtautoheight hidden-print locker autoupdateformdata </value>
      <webElementGuid>79f33c38-d636-4827-8d7d-118011f87cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textarea-1687188811798</value>
      <webElementGuid>28548e1c-5deb-4dc4-a4e0-b74e4356f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-1687188811798</value>
      <webElementGuid>3160ffbc-58d9-4287-a108-03456d3dfb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>frmdata</value>
      <webElementGuid>b10b253a-9e41-4634-9905-8e63419cb468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>7f276c16-73d8-4dc3-a9dc-ffff70e7e1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>107</value>
      <webElementGuid>0e9e14ef-275d-4f84-a9f2-8c8e18c49d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unlock and Remove Signatures automation test</value>
      <webElementGuid>2337b1ef-0f8b-4a7a-a95c-170054504bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-1687188811798&quot;)</value>
      <webElementGuid>fe39a7e4-8118-4220-9bb9-0eb7f6d4d8b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-1687188811798']</value>
      <webElementGuid>95c167d5-26d8-4d6a-82b4-d84e105c7e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formdataFirstPanel']/div/div/div[6]/div/div/textarea</value>
      <webElementGuid>1d878d21-b9cf-42dd-91a9-337959b95557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::textarea[1]</value>
      <webElementGuid>bb7cc175-9461-47f3-8bf7-f41d214bd6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Clinical Note B Client'])[1]/following::textarea[1]</value>
      <webElementGuid>4718295f-a570-47ae-8a59-79565ee04176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlock and Remove Signatures automation test'])[2]/preceding::textarea[1]</value>
      <webElementGuid>1155426a-ed74-4be4-9070-aa1d5b082044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Staff Signature Date/Time'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8fa9147c-7f20-41ae-89eb-888eb9b36c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unlock and Remove Signatures automation test']/parent::*</value>
      <webElementGuid>37849e53-9bd4-42ba-a3ad-ca3311c12634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/textarea</value>
      <webElementGuid>25cc51fa-37f6-4623-9a1e-41ecd17feada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textarea-1687188811798' and @id = 'textarea-1687188811798' and @form = 'frmdata' and (text() = 'Unlock and Remove Signatures automation test' or . = 'Unlock and Remove Signatures automation test')]</value>
      <webElementGuid>17aa3dfd-e061-4e53-b953-ee6a6a49abd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
