<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Note_textarea-1687188811798</name>
   <tag></tag>
   <elementGuidId>4f8058de-b3ed-4a34-b4af-0d9d4459bc12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-1687188811798']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-1687188811798</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Note:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f969e628-5bbc-4753-8b05-2bdd9bd4f648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8ff55be3-e24a-4ab2-a8b0-0e62bfef9898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtautoheight hidden-print locker autoupdateformdata </value>
      <webElementGuid>00335d1b-9b19-4d3b-ab16-98415fbd5da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textarea-1687188811798</value>
      <webElementGuid>350b20c6-40b4-4744-9d5a-8f3897e9e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-1687188811798</value>
      <webElementGuid>d1ca909f-10a4-452e-8980-c4eee9d75c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>frmdata</value>
      <webElementGuid>8016ae02-9665-48a7-84e9-d6292d11cb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>171a728f-1441-4863-ab00-ac6bfbf4a45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>107</value>
      <webElementGuid>88ed7a1d-d9d0-420f-a11d-6eb8dfe3b85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-1687188811798&quot;)</value>
      <webElementGuid>5511e5cb-7768-49f1-a519-5df1c09d813c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-1687188811798']</value>
      <webElementGuid>38a2778a-c438-4c23-9d1d-07ddc2146e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formdataFirstPanel']/div/div/div[6]/div/div/textarea</value>
      <webElementGuid>8ddf37f9-3b86-422c-93a4-1026a7463439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/textarea</value>
      <webElementGuid>1c728c3d-938c-4254-af0e-3ee0bbe6d3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textarea-1687188811798' and @id = 'textarea-1687188811798' and @form = 'frmdata']</value>
      <webElementGuid>3ded1b38-3667-42e9-9826-88b8c68aea49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
