<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_930 - 10 AM</name>
   <tag></tag>
   <elementGuidId>4c464f11-f773-4fb5-9844-bcb9dc720146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover556633']/div[2]/div/span[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text--small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;9:30 - 10 AM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>930c135a-05df-4821-a004-82946cc8565e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--small</value>
      <webElementGuid>47d1f5af-2640-49bb-83be-71913ff66da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9:30 - 10 AM</value>
      <webElementGuid>444b0323-9657-43e9-b461-e1e350375591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover556633&quot;)/div[@class=&quot;popover-content&quot;]/div[@class=&quot;event-details-popover flex-col&quot;]/span[@class=&quot;text--small&quot;]</value>
      <webElementGuid>13d17ae5-6fd8-44a9-a3b4-992061bccbf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover556633']/div[2]/div/span[5]</value>
      <webElementGuid>97bfb4d0-d6ba-4bab-ba14-23f3d2a2f538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday, Oct 1'])[1]/following::span[1]</value>
      <webElementGuid>b78b5080-9135-4218-b8d3-4fb7d73de0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When'])[1]/following::span[2]</value>
      <webElementGuid>4d4730d5-4ea6-4b41-bf13-4115ccf28b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminder'])[1]/preceding::span[1]</value>
      <webElementGuid>0c42f9fe-3275-4853-a343-b4ae4ccff0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9:30 - 10 AM']/parent::*</value>
      <webElementGuid>f8d5ad86-3fcc-4057-9afe-41479672967b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>56e2138b-b4ab-4031-8717-d6fc24350fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '9:30 - 10 AM' or . = '9:30 - 10 AM')]</value>
      <webElementGuid>3d46639a-d79a-4c1c-b27b-9e5551197c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover756192']/div[2]/div/span[5]</value>
      <webElementGuid>18680ef1-7e49-4862-bb10-b2e042fb4f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
