<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blocked for Automation Block</name>
   <tag></tag>
   <elementGuidId>e931342f-f581-462c-baf9-fc97bca25474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fc-event.fc-event-draggable.fc-event-resizable.fc-event-start.fc-event-end.fc-event-past.fc-event-today.fc-timegrid-event.fc-v-event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody//div[6]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Blocked for: Automation Block&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cdb431a-cf77-40c3-978e-611ab774fc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ce8cd40-635a-42f2-862a-7f70cce0e1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-event fc-event-draggable fc-event-resizable fc-event-start fc-event-end fc-event-past fc-event-today fc-timegrid-event fc-v-event</value>
      <webElementGuid>fa10006c-e344-4d5e-9d96-6a829981fc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blocked for: Automation Block</value>
      <webElementGuid>5b3cb885-e1d9-429e-be6a-97a4cc8ced85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar&quot;)/div[@class=&quot;fc-view-harness fc-view-harness-passive&quot;]/div[@class=&quot;fc-timeGridWeek-view fc-view fc-timegrid&quot;]/table[@class=&quot;fc-scrollgrid&quot;]/tbody[1]/tr[@class=&quot;fc-scrollgrid-section fc-scrollgrid-section-body&quot;]/td[2]/div[@class=&quot;fc-scroller-harness&quot;]/div[@class=&quot;fc-scroller&quot;]/div[@class=&quot;fc-timegrid-body&quot;]/div[@class=&quot;fc-timegrid-cols&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;fc-day fc-day-thu fc-day-today fc-timegrid-col&quot;]/div[@class=&quot;fc-timegrid-col-frame&quot;]/div[@class=&quot;fc-timegrid-col-events&quot;]/div[@class=&quot;fc-timegrid-event-harness fc-timegrid-event-harness-inset&quot;]/a[@class=&quot;fc-event fc-event-draggable fc-event-resizable fc-event-start fc-event-end fc-event-past fc-event-today fc-timegrid-event fc-v-event&quot;]</value>
      <webElementGuid>056df03b-1cfc-430b-9be6-65841bf09ae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody//div[5]//a[1]</value>
      <webElementGuid>19882dfd-1fa7-4e4e-b2d0-ec4bf1058dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Blocked for: Automation Block' or . = 'Blocked for: Automation Block')]</value>
      <webElementGuid>57e0fd38-91ea-4ff5-a6f9-ed80d68c290b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
