<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_</name>
   <tag></tag>
   <elementGuidId>eafabd63-cc90-49e1-88b5-9d8d1c3b9beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_mdl_referout_add_save']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_mdl_referout_add_save > i.fa.fa-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#btn_mdl_referout_add_save</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>95eb7f08-7ebb-48c1-9ec7-7cb24ad63c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-save</value>
      <webElementGuid>643637a7-fd95-4df0-b430-a5d68982354b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>bcebd07e-b239-4e0c-b976-6aeaa199b7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_mdl_referout_add_save&quot;)/i[@class=&quot;fa fa-save&quot;]</value>
      <webElementGuid>48df8e68-c0d9-43d1-b72b-5686a2a3fa57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn_mdl_referout_add_save']/i</value>
      <webElementGuid>408e5644-4625-4699-8390-cd94a701972d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer Client Out'])[2]/preceding::i[2]</value>
      <webElementGuid>79a7b41a-9014-4457-bde5-4609dd037d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/div/div[3]/div/div/div[2]/button/i</value>
      <webElementGuid>0cf4b644-b70f-40b6-bc0e-512ce5e64673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>7f3236e6-287f-4a1d-b47c-5ccf87d78292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
