<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Anticipated Effect of Family Dynam_bbb4c4</name>
   <tag></tag>
   <elementGuidId>22861bf0-1ecb-4126-a1bc-bbe31e8f6302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtfamilyeffect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtfamilyeffect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Anticipated Effect of Family Dynamics on Discharge:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>516cd0cf-783b-4081-88c9-ee91c7dc3e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtfamilyeffect</value>
      <webElementGuid>83aa1807-9246-45f6-86f2-903a6be3729b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>6905ccbc-8d83-41f5-b4c8-ece7c3d7d369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>04de3fec-3114-4b0f-970e-39de735efe98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfamilyeffect</value>
      <webElementGuid>4a0f1f80-d19a-4091-bf7b-dbded1952802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>abe1e275-57de-4495-a296-ca72b3eed86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6d8cb80f-8a56-412a-8a83-285c6023742e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfamilyeffect&quot;)</value>
      <webElementGuid>7aa14dcf-b4aa-4386-b49f-e55a9a23f8ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtfamilyeffect']</value>
      <webElementGuid>9bbc5704-8270-42e1-8287-70bcc9c29088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcplanform']/div/div/div/div/div[32]/div/div/textarea</value>
      <webElementGuid>30e8b683-87b4-4a1b-b488-22d8bcc1a8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/div/div/textarea</value>
      <webElementGuid>ca48add6-918b-469c-941e-3e344767c441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtfamilyeffect' and @id = 'txtfamilyeffect']</value>
      <webElementGuid>9b89a3ff-0abc-4986-9302-fdd103b3fb19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
