<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Client Abilities_abilities</name>
   <tag></tag>
   <elementGuidId>998deed0-9f20-4578-9a3d-854de219da5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='abilities']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abilities</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Client Abilities:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb1eef05-bbfe-4f1d-9493-4d78c488e5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>abilities</value>
      <webElementGuid>2660926f-b773-4d28-857e-308d7ea670f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>07bd5a7c-d4f4-4651-be82-7e78b286d0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1b97b162-1e37-475e-a2f1-d0bffa141b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abilities</value>
      <webElementGuid>43e0642a-adcd-4a9a-8393-2e7657c5b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control printworthy locker hidden-print</value>
      <webElementGuid>f0cd1165-bb7e-4b26-b025-05a22de52d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6f611479-a37c-42ca-a42a-0e1cc62aa1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abilities&quot;)</value>
      <webElementGuid>7b91aaba-c3da-44bf-a6fe-bfb015646780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='abilities']</value>
      <webElementGuid>24a1ef9e-526d-4848-b867-0dcdc5863e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcplanform']/div/div/div/div/div[29]/div/div/textarea</value>
      <webElementGuid>c750ed7d-7376-4866-846c-46fd88d52799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/div/textarea</value>
      <webElementGuid>435d2f3f-0b07-4247-abc7-0e397bc25845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'abilities' and @id = 'abilities']</value>
      <webElementGuid>ee115678-5835-4d00-ac21-a867727ac5d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
