<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_11</name>
   <tag></tag>
   <elementGuidId>3efd79a7-c870-4f6b-b875-001817ef03ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tblvshx_client_profile > tbody > tr.odd > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblvshx_client_profile']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;11&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e75e4e54-24a1-441e-bf0b-c23dbde9a984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>6d51785d-f1b2-4fd7-808f-8003ff515f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblvshx_client_profile&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]</value>
      <webElementGuid>a2b60d57-7bbc-4afd-a673-7782733d6754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblvshx_client_profile']/tbody/tr/td[4]</value>
      <webElementGuid>4bd20c4e-bf0f-4624-bc80-99f6cfd86559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[10]/following::td[2]</value>
      <webElementGuid>92b96ffc-c433-4af6-aa09-74d4468ad443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Information'])[1]/following::td[4]</value>
      <webElementGuid>dbffeb59-b1e0-47c4-a2fd-62a5dbe19984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Additional Information'])[1]/preceding::td[4]</value>
      <webElementGuid>5bb4eed8-b872-43c8-a912-d30c06cf1136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::td[6]</value>
      <webElementGuid>213da77f-19e1-47e3-99b0-e138c0f4fd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11']/parent::*</value>
      <webElementGuid>5cf131df-742f-4562-a704-cefe2fe4e065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>47d2f236-10b1-45dc-a4a4-aee7490c7b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '11' or . = '11')]</value>
      <webElementGuid>f1452adf-abd5-4258-8cab-6421e071d547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
