<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Detoxification</name>
   <tag></tag>
   <elementGuidId>4c15b0fd-d0a1-48af-b5ba-59925683607f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbltreatmentsummaries > tbody > tr > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbltreatmentsummaries']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Detoxification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>53fedb81-1d17-4759-be7d-612f74e5fc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detoxification</value>
      <webElementGuid>c7544c35-b992-40c7-9b89-e3956484c59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbltreatmentsummaries&quot;)/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>fa09a800-e452-416f-be3e-7f54aebdc216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbltreatmentsummaries']/tbody/tr/td[2]</value>
      <webElementGuid>c8888df0-2867-47f4-a7f9-8518482dc746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[13]/following::td[2]</value>
      <webElementGuid>05a0ff83-e865-4688-abc5-8bf36480a9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed By'])[8]/following::td[2]</value>
      <webElementGuid>c679bfb4-e414-4aa4-8603-87331c5e8c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[8]/preceding::td[1]</value>
      <webElementGuid>b9d7be0c-5731-4674-bf76-07a8b27ee9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed'])[8]/preceding::td[2]</value>
      <webElementGuid>12bad426-9e28-4758-9b5a-8958150a8878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>45b8f7f8-1abd-4cc1-80e1-13f012af3ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Detoxification' or . = 'Detoxification')]</value>
      <webElementGuid>6b3f0893-d399-441e-a91b-d72c575faca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
