<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Signed</name>
   <tag></tag>
   <elementGuidId>1fbe5783-4dea-4cc6-9f70-61804f079341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbltreatmentsummaries > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbltreatmentsummaries']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Signed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1e6028a6-02b9-4d80-bcc3-055f23000887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Signed
                          </value>
      <webElementGuid>68840629-d0b6-453b-baa4-8028207ff6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbltreatmentsummaries&quot;)/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>c0e9f88b-f991-458d-beb5-b5779c5828a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbltreatmentsummaries']/tbody/tr/td[4]</value>
      <webElementGuid>e47adced-8642-4800-adcc-a84fd90fb030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[8]/following::td[1]</value>
      <webElementGuid>0af907fc-7696-4f7b-b986-5f1257943663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detoxification'])[3]/following::td[2]</value>
      <webElementGuid>5d68c593-51de-4905-81d4-ac348c48226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation of New Records is not Allowed without an Active Episode of Care.'])[16]/preceding::td[2]</value>
      <webElementGuid>640eb6df-967d-4875-8fef-77a10b8991b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation of New Records is not Allowed in a previous Episode.'])[16]/preceding::td[2]</value>
      <webElementGuid>5d482b96-3361-4e2c-bd4b-cafa0febe0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>a7a714fb-241d-4c42-85c1-1db883fcbab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                            Signed
                          ' or . = '
                            Signed
                          ')]</value>
      <webElementGuid>a214b546-4bad-4791-b16b-10c263f7b4de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
