<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10 - 1030 AM</name>
   <tag></tag>
   <elementGuidId>3ac3ab8b-db95-4931-984a-179d77c63c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover330445']/div[2]/div/span[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text--small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;10 - 10:30 AM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc69288b-5eb8-4291-abe4-720e8b5bfaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--small</value>
      <webElementGuid>74c08830-d580-46a6-bbf4-73809696bf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10 - 10:30 AM</value>
      <webElementGuid>9db9a8db-c2ad-4108-a032-a8a30c227c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover330445&quot;)/div[@class=&quot;popover-content&quot;]/div[@class=&quot;event-details-popover flex-col&quot;]/span[@class=&quot;text--small&quot;]</value>
      <webElementGuid>099d3af6-2654-48d5-b352-78651aa67f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover330445']/div[2]/div/span[6]</value>
      <webElementGuid>2725dad4-75df-431e-b10a-67ef917e06d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friday, Sep 27'])[1]/following::span[1]</value>
      <webElementGuid>6a907816-d2b0-4a7f-bc28-32a0e2e5d196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When'])[1]/following::span[2]</value>
      <webElementGuid>b1640cd2-58ce-4874-bdd6-448501ea2b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminder'])[1]/preceding::span[1]</value>
      <webElementGuid>b17218ec-e8da-4208-a922-414cc8c30fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10 - 10:30 AM']/parent::*</value>
      <webElementGuid>1ed5316a-3a69-4d78-b45a-eea430dfedd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]</value>
      <webElementGuid>45d846d5-2f79-4522-8555-c1ffaae6007c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '10 - 10:30 AM' or . = '10 - 10:30 AM')]</value>
      <webElementGuid>feeaed09-5904-4da4-806a-972969040590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
