<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Problem_problem_add</name>
   <tag></tag>
   <elementGuidId>2a68bb4f-5073-4b75-89aa-1926e02364e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='problem_add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#problem_add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#problem_add</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ceba2a2-f3fc-4f74-ac52-c49b4aeb45af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>lstProblems</value>
      <webElementGuid>69fe5733-d9e4-4e87-9a2b-2aebace0814f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>problem_add</value>
      <webElementGuid>96b900af-1f2f-4b55-adfc-9a3f12a015ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1ec28edb-c4ea-4531-841b-0464f6859719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;problem_add&quot;)</value>
      <webElementGuid>67203ac0-6a7b-4215-bb7a-24dddefb445b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='problem_add']</value>
      <webElementGuid>c255ea18-c472-4122-ae53-51d0125441b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdltxgoaladd']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>7b767e13-029d-4620-aac5-671c721fd28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/input</value>
      <webElementGuid>90694d8c-7527-4665-b540-82a4421f5a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'problem_add']</value>
      <webElementGuid>c35c87b9-64a0-41b6-812b-314499c00c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
