<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Client will complete an SI risk assessmen_bacf5f</name>
   <tag></tag>
   <elementGuidId>e69d86e6-a817-4fa6-ab2a-0e7bd25e439b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lo13']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lo13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Client will complete an SI risk assessment half way through treatment and discus&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>94f0df38-e455-4284-81d9-8c648223cc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item-text</value>
      <webElementGuid>45e39011-a757-4ff2-8b9e-123015a08c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lo13</value>
      <webElementGuid>d048a411-4c36-411d-a675-90c11a526144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client will complete an SI risk assessment half way through treatment and discuss any SI as it comes up </value>
      <webElementGuid>38b38287-6511-4911-857f-747651e88f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lo13&quot;)</value>
      <webElementGuid>bceef7cd-a64d-44ff-bfb8-c04df681c924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lo13']</value>
      <webElementGuid>5fbf8f5d-a048-4ffd-a157-133dd1e13deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='objlist']/a[3]/p</value>
      <webElementGuid>e9c3b433-13fa-4687-9833-4f9103251f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category:'])[1]/following::p[3]</value>
      <webElementGuid>fb261f6c-9e1c-451d-a3c0-0d86ad4fbb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Treatment Objective for A Client A Automation'])[1]/following::p[3]</value>
      <webElementGuid>fd4d2919-11aa-452b-811c-b3b48c975043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goal:'])[3]/preceding::p[4]</value>
      <webElementGuid>8507218b-2bc5-4eca-aae6-9429960de48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Goal'])[1]/preceding::p[4]</value>
      <webElementGuid>a30b2924-0cbb-4a14-bf9c-e61bcab31e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Client will complete an SI risk assessment half way through treatment and discuss any SI as it comes up']/parent::*</value>
      <webElementGuid>adad6d8b-017a-498b-8dcc-4aa244b9f3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/p</value>
      <webElementGuid>07a2436c-5e05-415b-be60-bde42ddac551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lo13' and (text() = 'Client will complete an SI risk assessment half way through treatment and discuss any SI as it comes up ' or . = 'Client will complete an SI risk assessment half way through treatment and discuss any SI as it comes up ')]</value>
      <webElementGuid>3cdc462b-b250-4ff2-b216-34d214b55626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
