<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Client Strengths_strengths</name>
   <tag></tag>
   <elementGuidId>8c0b1704-ba04-467c-80ea-fdc0052e5a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='strengths']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#strengths</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Client Strengths:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4fabaeb8-fa06-4387-9903-be76b4a36499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>strengths</value>
      <webElementGuid>399a343b-98b3-41a3-bc14-402c9a518843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bbb1f405-77f6-4a1f-823a-57e35f39caf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1fec1418-66dc-4941-945d-2e1009cdaee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strengths</value>
      <webElementGuid>9e48b8f5-6fdf-4f8b-ad42-121dc64a8f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate locker</value>
      <webElementGuid>1e6797df-9791-4369-801e-aeeaef3efdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ea6a56c7-69fb-4046-8f79-5510a4dee1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;strengths&quot;)</value>
      <webElementGuid>9ea0a2b5-4825-45f8-a3ee-1c4a1c0f1682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='strengths']</value>
      <webElementGuid>f241adc6-34db-48d6-97fc-c9c55dff9758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsnap']/div/div/div/textarea</value>
      <webElementGuid>cd14ed89-840e-404b-88c8-f5098177bf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/textarea</value>
      <webElementGuid>4c601638-d49c-47a2-bb74-fe63372cd397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'strengths' and @id = 'strengths']</value>
      <webElementGuid>fa398728-34f5-4597-8458-eb4a30f6027a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
