<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Family Involvement in Discharge Pl_020026</name>
   <tag></tag>
   <elementGuidId>4ba578a3-d6d7-43ff-8fec-da2c06eed6f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtfamilysupport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtfamilysupport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Family Involvement in Discharge Planning (If none, please explain)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d43fe609-f5ee-410e-8f49-3143bbd55697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtfamilysupport</value>
      <webElementGuid>d5a31fb9-df64-46ce-ad7d-77ab4450379d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4b8a5602-bf8f-4386-9df6-4a23ffedfdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d0c2b35e-7281-4b79-9c9f-a8989b975ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfamilysupport</value>
      <webElementGuid>8af18dc6-b11a-4bdd-b65c-969c3c75af3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate locker</value>
      <webElementGuid>14790f09-6d2b-4cce-a9d4-6a217f9fe65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>36ee1a66-7a2a-4a8f-840e-8dce7ddb819d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfamilysupport&quot;)</value>
      <webElementGuid>697a6cd7-2482-4f3d-bdbc-2fe5d66a6783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtfamilysupport']</value>
      <webElementGuid>e5d7e260-d31c-47be-84fb-c1fa21956a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div[4]/div/div/textarea</value>
      <webElementGuid>7d79bce6-4e86-4b1d-997c-01ec789e5cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/textarea</value>
      <webElementGuid>066e20e1-550b-4644-8497-70d794cbe82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtfamilysupport' and @id = 'txtfamilysupport']</value>
      <webElementGuid>be33f30f-4d40-415a-a9b3-2711cc5b806e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
