<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Census</name>
   <tag></tag>
   <elementGuidId>66c0d270-79ff-464d-80aa-2afecf9ff11e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#census-menu-item > div.item-label > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='census-menu-item']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Census&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20cdc369-e6cc-4517-9628-7893b3e41c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>fdcc52c6-3870-4aff-bb11-b11e3adb89e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Census
                    </value>
      <webElementGuid>3865b6ab-4174-42fa-9c16-17a79b78898b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;census-menu-item&quot;)/div[@class=&quot;item-label&quot;]/a[1]</value>
      <webElementGuid>d0c40282-ab69-4bc0-94b1-22e2857565bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='census-menu-item']/div/a</value>
      <webElementGuid>189ba213-f19f-492a-9697-d937d3f496a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Census')]</value>
      <webElementGuid>0637913a-b3e0-47fa-8d4b-f9787e8acc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='groups'])[1]/following::a[1]</value>
      <webElementGuid>57bf82d9-e463-44fa-b09c-adc62e1b6135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homepage'])[1]/following::a[1]</value>
      <webElementGuid>c59ec3f1-73ca-48c7-9909-a35d851078ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='person'])[1]/preceding::a[1]</value>
      <webElementGuid>c1117e90-e073-473a-96b8-ca948b77b58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caseload'])[1]/preceding::a[1]</value>
      <webElementGuid>7da130e1-c4e8-4e2c-9ecb-16bb00fe6159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Census']/parent::*</value>
      <webElementGuid>27f42b5e-b424-4fb1-8ecd-1e23caef1498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>a9f36ef9-3e42-4ffe-8611-d9feb89d124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>23de9b69-744f-4d0a-b9ad-fcf4efbf8811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                        Census
                    ' or . = '
                        Census
                    ')]</value>
      <webElementGuid>a520ceba-cb33-4c8d-b894-826509637457</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
