<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Reported_fa fa-edit</name>
   <tag></tag>
   <elementGuidId>83a6c394-aa0b-4ad4-b1fc-2b500718a97c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='cmedrow248']/td[8]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>23ddde59-1284-4e28-8b17-2b5006ac16b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>6012f64c-5a80-4cd9-9942-8cd8fee7e04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmedrow248&quot;)/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-primary btn-raised btn-sm opendispomed&quot;]/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>3f5febf3-a5f4-4407-862e-1c766a7e941d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cmedrow248']/td[8]/button/i</value>
      <webElementGuid>e1c2b04b-250e-414b-8528-4e3d3a32ae89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reported'])[1]/following::i[1]</value>
      <webElementGuid>e5ac86f8-c499-44bb-871d-e626fb933f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Prescriber'])[1]/following::i[1]</value>
      <webElementGuid>00460c83-944f-40cf-9a46-dd0a88ab3251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::i[1]</value>
      <webElementGuid>f84e4cac-87c1-4e3a-ba97-732ca36de1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescription Medications Created from Client Reported Medications'])[1]/preceding::i[1]</value>
      <webElementGuid>085739a9-7a9d-4f2d-9dba-4ca516c00850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/button/i</value>
      <webElementGuid>cd1847d3-3196-4ba1-af56-d8b5693e215e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
