<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-group-1639631648138_119</name>
   <tag></tag>
   <elementGuidId>e3b8dfcc-4af1-46fc-9fef-5ed1cbf8da16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-group-16396316481382']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-group-16396316481382</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#radio-group-16396316481382</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>157add93-691c-4c78-9a3c-a85aae935590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>34d0be08-226b-4c64-823e-15782a9a72f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker autoupdateformdata required</value>
      <webElementGuid>b7a7d3ed-0c62-4b7e-89c1-cab2f56350f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-group-1639631648138_119</value>
      <webElementGuid>8d41311d-2777-4809-ac9f-5be3caf19a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group_id</name>
      <type>Main</type>
      <value>radio-group-1639631648138</value>
      <webElementGuid>7e916e98-94f8-4a1a-9497-752180ef7b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-group-16396316481382</value>
      <webElementGuid>4e179cd8-a55a-43d4-942d-2d7f33e6ba79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6dc509a9-6b61-4fc3-a4de-cc5b76535c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-score</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3af8c7d4-3b76-41e9-9d18-3e488f2f3bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scorename</name>
      <type>Main</type>
      <value>Score</value>
      <webElementGuid>c01f02bb-664d-47d9-8a39-9a9cbaeb02ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>3648d613-6ae8-4fd8-8c90-2e2384ddd163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>db508117-45d0-49c7-8cf3-b305ecd72ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sluglabel</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7b0fcbd6-c47b-4084-abda-1ec2e1a7c29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-group-16396316481382&quot;)</value>
      <webElementGuid>7bd496da-5f70-4542-831a-f45e8055f737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-group-16396316481382']</value>
      <webElementGuid>4e262861-18cc-4e61-b16a-8c24d1202ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_radio-group-1639631648138']/span[3]/input</value>
      <webElementGuid>b47d4967-94b2-4a62-a868-4b5af30dc8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/span[3]/input</value>
      <webElementGuid>10838019-94b0-42d3-9b1c-9c87e678d327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio-group-1639631648138_119' and @id = 'radio-group-16396316481382']</value>
      <webElementGuid>f1dcdb83-dcb6-4f25-9eda-543d29328683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
