<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-group-1639631758534_119</name>
   <tag></tag>
   <elementGuidId>35ec9463-0a30-442c-9114-32c669fad144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-group-16396317585340 No tremor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;radio-group-16396317585340\ No\ tremor&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fe7527a-d19d-459a-9ce5-02b2de4d5122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>96f218c7-a744-4208-8d86-5bfb37636893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker autoupdateformdata required</value>
      <webElementGuid>027ccaf5-1128-4e05-8ba5-602377c20cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-group-1639631758534_119</value>
      <webElementGuid>f3996e66-878b-44e9-a6e7-f3b27c69fd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group_id</name>
      <type>Main</type>
      <value>radio-group-1639631758534</value>
      <webElementGuid>eec08dd9-4688-4909-97bc-3acbd45a9863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-group-16396317585340 No tremor</value>
      <webElementGuid>5ccf359b-686e-4024-859d-2a7a6e06d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0 No tremor</value>
      <webElementGuid>b626e4a4-83ee-4c2f-bbc2-df73946961b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-score</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d8e7be3-41bf-428d-8011-737b72d1586b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scorename</name>
      <type>Main</type>
      <value>Score</value>
      <webElementGuid>f959fd8d-af1c-43a8-beb5-3b851df1a10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>2a67f3e5-9ada-4ee7-8852-8d0d1efb4349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>77945bdf-3363-465b-ac1f-242082ae2ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sluglabel</name>
      <type>Main</type>
      <value>0Notremor</value>
      <webElementGuid>0f40e3e5-d6a1-44f8-ba6a-d59623669d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-group-16396317585340 No tremor&quot;)</value>
      <webElementGuid>2e433b2e-6cee-416d-889a-900ab7ab847f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-group-16396317585340 No tremor']</value>
      <webElementGuid>cd0c4ff0-92f7-4575-8fce-b72eaa848f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_radio-group-1639631758534']/span/input</value>
      <webElementGuid>2e6b6d4b-b8fb-4a87-83c7-8bd1e3221904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/span/input</value>
      <webElementGuid>ec6dbc65-1f6b-4023-98ae-ee3bb279ffc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio-group-1639631758534_119' and @id = 'radio-group-16396317585340 No tremor']</value>
      <webElementGuid>0a7a2e89-b8f5-4b45-b3dc-6ea39fbc3a34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
