<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you think you did not get enough s_69b9b6</name>
   <tag></tag>
   <elementGuidId>4c9e5f32-46a6-4cf5-9ea0-d88ca41d6554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-group-16396403994812']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-group-16396403994812</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#radio-group-16396403994812</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7328bb48-f4eb-4fe1-af91-48bce0138c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7112761b-e874-4845-8e5f-a6ef1bfcbddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker autoupdateformdata </value>
      <webElementGuid>cf5f4875-0874-410a-b7a2-3c9843f0cf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-group-1639640399481_119</value>
      <webElementGuid>f868c100-d8d7-4e3b-8343-1a5393754b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group_id</name>
      <type>Main</type>
      <value>radio-group-1639640399481</value>
      <webElementGuid>d785efb5-0e36-4052-8a26-21883feccd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-group-16396403994812</value>
      <webElementGuid>8895119f-b944-447e-9125-5bc22d22d7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c9b32fa0-b908-486a-b26c-560e6a71e336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-score</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>68a33799-ddd7-4834-80b5-8fbfd1bb9121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scorename</name>
      <type>Main</type>
      <value>Score</value>
      <webElementGuid>614b66f1-f9af-497b-85a0-0079861b7c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>21e9ebc5-c80c-4483-8d25-ee666f17b461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>cf09ffef-f08a-498e-b5b0-702af7a40890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sluglabel</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>67a2fae9-3834-42fb-afb4-06eff7eeedd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-group-16396403994812&quot;)</value>
      <webElementGuid>a6f4b40d-464e-453f-b8fe-3dc86929db29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-group-16396403994812']</value>
      <webElementGuid>ba519101-b8a6-4cdd-83e0-d045e924aa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_radio-group-1639640399481']/span[3]/input</value>
      <webElementGuid>f3932df3-e0ab-476a-be24-75d8bdb64163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/span[3]/input</value>
      <webElementGuid>c790edda-b32b-4407-9849-1e329ab5fc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio-group-1639640399481_119' and @id = 'radio-group-16396403994812']</value>
      <webElementGuid>582ac04d-da44-4937-8273-054477c2de65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
