<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-group-1639631744615_119</name>
   <tag></tag>
   <elementGuidId>25fb9f6a-3e62-4bca-bd3b-7cac90a60250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-group-16396317446151']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-group-16396317446151</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#radio-group-16396317446151</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ded20ceb-96b2-4fc3-8228-2b3269c640f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4f9bc7a9-b3f6-4ca9-9e77-eb1990343248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker autoupdateformdata required</value>
      <webElementGuid>93550df8-a6d3-4fb9-a495-47391a7d55dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-group-1639631744615_119</value>
      <webElementGuid>8e114446-6c30-4eb5-9f99-010cd0ee0d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group_id</name>
      <type>Main</type>
      <value>radio-group-1639631744615</value>
      <webElementGuid>41542288-1c1d-48d4-926f-afa73c1a7b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-group-16396317446151</value>
      <webElementGuid>67a6a070-c631-4d79-898e-c556022298ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f84614de-4b67-4518-ad2d-4f014a6d1679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-score</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84fe2dcd-7cdb-4196-ae30-d158cbd36106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scorename</name>
      <type>Main</type>
      <value>Score</value>
      <webElementGuid>9166d3d4-3b68-4c6a-af92-6090e5e9e788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>f2601072-3f50-4e65-974a-bff3045eb90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>e2c1558f-3102-46d1-b93d-64ace74b713a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sluglabel</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>48683504-a82d-4e92-98ec-369a71187a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-group-16396317446151&quot;)</value>
      <webElementGuid>eba131dd-669f-416c-a185-c4919ec8b986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-group-16396317446151']</value>
      <webElementGuid>34e24bdb-9ea4-41e2-b37b-a519c1ea7786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_radio-group-1639631744615']/span[2]/input</value>
      <webElementGuid>ad61e2d8-593a-413d-91ff-d75a6eb7677c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/span[2]/input</value>
      <webElementGuid>841bed47-c9f5-4e7f-a448-564105bf92dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio-group-1639631744615_119' and @id = 'radio-group-16396317446151']</value>
      <webElementGuid>840fa266-5d23-427d-9039-d5898e086ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
