<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional Information_textarea-16_acaf1e</name>
   <tag></tag>
   <elementGuidId>7ea77c37-e858-47da-a22a-9dbc4c630405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-1639641222146']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-1639641222146</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Additional Information&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>313f6ee2-6ec4-4ff3-9afa-d4bdaa3155b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>de8a9ab9-78a6-4143-a282-3845d307f9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hidden-print locker autoupdateformdata </value>
      <webElementGuid>3cd7d23b-defb-41c0-a5fa-9774e12bfe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textarea-1639641222146</value>
      <webElementGuid>900c9897-145e-4851-9170-fdfa8a41d40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-1639641222146</value>
      <webElementGuid>7f3cd27e-2172-4b99-9bda-ac63d26e3b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>frmdata</value>
      <webElementGuid>aae3f6bd-51fa-487f-8424-9115818c8cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>4cf60f3c-4793-45fa-b108-997d02c80f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>447fb0d5-3e44-4313-ac07-e7a331867b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-1639641222146&quot;)</value>
      <webElementGuid>2a91e373-7cc9-490b-9cdb-c1ed24733b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-1639641222146']</value>
      <webElementGuid>0edcd467-0b67-4029-bd1d-5e67a47c0515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formdataFirstPanel']/div/div/div[5]/div[33]/div/textarea</value>
      <webElementGuid>b374a5c5-4bcc-4731-a7df-33831a73892e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/div/textarea</value>
      <webElementGuid>28d092c3-0a13-496e-9e04-8ce7a844330a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textarea-1639641222146' and @id = 'textarea-1639641222146' and @form = 'frmdata']</value>
      <webElementGuid>606aad3d-97a9-4992-afb3-e7fafddf1abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
