<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Automation Test_1</name>
   <tag></tag>
   <elementGuidId>fac06ed4-2149-4fe1-8c00-b2ed0625e58a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblestimates']/tbody/tr[8]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(8) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c1e6c53c-bbea-475e-b55a-b5c6df5056cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Test</value>
      <webElementGuid>92881fc5-2a38-4d93-8417-ae5de61f873d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblestimates&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[4]</value>
      <webElementGuid>d0d58ce4-98a1-4a0c-9cd5-2c59fa0b61a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblestimates']/tbody/tr[8]/td[4]</value>
      <webElementGuid>47ea1fa0-d8ce-433e-9150-ed36bd8a3c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[10]/following::td[1]</value>
      <webElementGuid>2e710139-95f6-4592-b802-13b66c87d604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Entity'])[10]/following::td[5]</value>
      <webElementGuid>978107e4-a1e3-4217-8c2a-b96aff3695f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$211.10'])[1]/preceding::td[1]</value>
      <webElementGuid>18a3ee65-c43f-474d-aff2-49b70332ae05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$14.40'])[1]/preceding::td[2]</value>
      <webElementGuid>6dc3546a-8cfe-4f70-b6b6-82a372620ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]</value>
      <webElementGuid>f04a3704-6759-4014-b174-66629df61ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Automation Test' or . = 'Automation Test')]</value>
      <webElementGuid>ff5db97f-24b5-466b-a3fe-0b56d1d999cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
