<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Signed_btn btn-primary btn-raised btn-sm</name>
   <tag></tag>
   <elementGuidId>292ff001-c39f-479b-99a5-99d04d5f28a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbldcmedslist > tbody > tr > td:nth-of-type(4) > a.btn.btn-primary.btn-raised.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbldcmedslist']/tbody/tr/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1a1e347-5f60-4370-a452-89f40f963261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-raised btn-sm</value>
      <webElementGuid>ed28e127-7fcc-424b-9b8e-5aa1c6ae3c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://site17.lsapp.cloud/dcmedslist/5/edit</value>
      <webElementGuid>a638d372-434e-4f7e-89a9-4972945ffeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbldcmedslist&quot;)/tbody[1]/tr[1]/td[4]/a[@class=&quot;btn btn-primary btn-raised btn-sm&quot;]</value>
      <webElementGuid>1b0e869d-e3a9-436e-8760-95ef790ec71c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbldcmedslist']/tbody/tr/td[4]/a</value>
      <webElementGuid>6e401369-84f7-45bb-9b22-67635d5df1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed'])[8]/following::a[1]</value>
      <webElementGuid>cb92bdc8-0bc4-4f4b-a3fd-4fcfe7abd916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[8]/following::a[1]</value>
      <webElementGuid>a2c6318a-1aa0-4f6c-8bbb-813ecbc7174d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[40]/preceding::a[1]</value>
      <webElementGuid>61ae19a4-c49d-4ca5-aae9-b033b02430a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medication Reconciliation for E Client E Automation'])[1]/preceding::a[2]</value>
      <webElementGuid>e5f59373-ed09-4044-aa57-5bae65fcf1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://site17.lsapp.cloud/dcmedslist/5/edit')])[2]</value>
      <webElementGuid>951dafa3-8d53-4ca7-bde8-89e5db5c82a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/table/tbody/tr/td[4]/a</value>
      <webElementGuid>f3add4da-82ef-4a88-87b9-cd55e9046f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://site17.lsapp.cloud/dcmedslist/5/edit']</value>
      <webElementGuid>3dd1b01f-7598-4cb2-bc25-662e3a5e1a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
