<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>b9cca07d-3e46-409b-acc5-a9fdb5cbd165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnmainfrmsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnmainfrmsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebabf98f-356d-4f87-a6d8-945f408f86c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-raised btn-primary btn-block locker nodoubleclick topazsig</value>
      <webElementGuid>873a8e9b-58bd-48c7-a1a0-04ace7582c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cf59af07-ff35-462c-8184-ba70a24168bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>ed723f04-58c4-4398-8893-360534687b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmainfrmsubmit</value>
      <webElementGuid>1ea50cba-c8e2-44fe-aaf0-29879c1f88b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save
        </value>
      <webElementGuid>ec82941d-ac6a-4f66-b8b1-db86cc9dc1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnmainfrmsubmit&quot;)</value>
      <webElementGuid>9dbbdd3e-b6ae-4dde-8db4-ac38c85d0092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnmainfrmsubmit']</value>
      <webElementGuid>d2b525ea-34cc-46f3-ace3-1ea6be41ba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_immunization']/div[2]/div/div[3]/div/div[3]/div/button</value>
      <webElementGuid>ecad77ad-f782-4c10-8bb5-150205652541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note'])[2]/following::button[1]</value>
      <webElementGuid>9cd35cd8-bbaf-4ee5-9a0e-57bc0aff886b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creator / Last Editor Name - Automation Test'])[1]/preceding::button[1]</value>
      <webElementGuid>7441db04-8aea-4b11-8375-87f026512498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>48b7b5d4-bbc8-4ce8-9933-f99fc7e73e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/button</value>
      <webElementGuid>6bec9802-64e0-4936-83fb-7a07f425bced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and @id = 'btnmainfrmsubmit' and (text() = ' Save
        ' or . = ' Save
        ')]</value>
      <webElementGuid>f0cebdaf-c325-445f-b8ac-55e0b36b5e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
