<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dose_dosenumber</name>
   <tag></tag>
   <elementGuidId>eb8d6a57-915e-46fb-8d71-bbbf9b86f270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosenumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosenumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Dose #&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aa0f1ee-007b-428b-ac88-cb4ccca56167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c2a0cf41-26c7-45c1-86cd-6c2829702192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dosenumber</value>
      <webElementGuid>f7532cf0-7db1-4e36-9f49-9c3f70c0c82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c14d620-cbe5-4fd6-9069-7e50364ee943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosenumber</value>
      <webElementGuid>474207ca-f1dd-454c-9d7c-f303735d79ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker printworthy  hidden-print</value>
      <webElementGuid>d9ca19ac-1981-437b-8285-9933d49bab12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>143ede82-42e4-4677-b601-f2f2f64ed9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>29bbc39e-5b73-4167-af31-f958873d880e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosenumber&quot;)</value>
      <webElementGuid>80730b39-661a-48ba-b8f1-9829c8bb9d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosenumber']</value>
      <webElementGuid>4d79f239-cf54-4891-b457-b25e54938a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_immunization']/div[2]/div/div/div/div[3]/div/input</value>
      <webElementGuid>847a1635-8226-4947-8929-1c64b6459c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/input</value>
      <webElementGuid>e8a1525e-5f9a-4ee0-ab11-46340c38720b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'dosenumber' and @id = 'dosenumber']</value>
      <webElementGuid>5248cd7e-441f-4b98-8582-7edea7fee642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
