<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign and Lock_dss</name>
   <tag></tag>
   <elementGuidId>49e84b86-476f-4824-bcf2-6397d7a00457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign and Lock&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fe2fae4-bcd8-4d9e-84a0-7766f9c5f1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>65383388-9148-4dfb-95e8-25df547906ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>84a05792-33a1-42f7-b242-bb696b1c9acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>401f675e-d0f1-45f5-9c04-3aa54f54e16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3c25c1f9-aed5-4aae-a846-810a8788a8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkcosign locker</value>
      <webElementGuid>6c5d1b1b-130b-4f51-b392-e6fac1da1691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dss&quot;)</value>
      <webElementGuid>a99ff157-f2a7-4fdf-b8ea-4a511579b700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dss']</value>
      <webElementGuid>48b2b145-657b-44b4-8317-f627723db904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainDssSection']/div/label/input</value>
      <webElementGuid>6d8aed6e-3cc0-4c4e-804e-6faf4891c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/label/input</value>
      <webElementGuid>539ca31c-7ce3-4fb2-b4fe-c931ff3afdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'dss' and @id = 'dss']</value>
      <webElementGuid>3303f342-cf6f-40f4-b834-d5d322e72b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
