<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Vaccination-emergent adverse react_de4e53</name>
   <tag></tag>
   <elementGuidId>ac2b1c0b-fd8e-48b1-a324-586cd7669f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reaction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Vaccination-emergent adverse reactions (reported ESAVIs)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>503cab71-e286-4b1b-bf4c-d7d2393c8aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reaction</value>
      <webElementGuid>4aecbfe2-1e25-4ddc-b29d-32623b5e1c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ccda2c79-02f1-4ac9-9635-c50cf2ad1e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>efabd897-5f93-42f7-826f-a36882be759a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reaction</value>
      <webElementGuid>3ba0abd2-af90-4358-981a-abb30fbd5437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker printworthy  hidden-print</value>
      <webElementGuid>f36c2d6c-b87a-47fb-85c9-92ea7b1fde4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reaction&quot;)</value>
      <webElementGuid>747a5300-09ec-4d57-8c4a-124c1ce2502b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reaction']</value>
      <webElementGuid>ac5e1756-00d5-47c4-9c89-92d333a4bb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_immunization']/div[2]/div/div/div[4]/div/div/textarea</value>
      <webElementGuid>336e5148-0c07-4a27-91e5-d8148c04a8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>e8485180-d0ab-42af-8b6a-1c8525137b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'reaction' and @id = 'reaction']</value>
      <webElementGuid>b834408d-8697-40cb-8057-e5410ea2a650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
