<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Reason for not vaccinating (includ_79de9a</name>
   <tag></tag>
   <elementGuidId>fc0550d4-3dbf-44df-b82d-bb5d34972b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#novaccinatereason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='novaccinatereason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Reason for not vaccinating (includes contraindications, history of ESAVI, etc.)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>acd718da-5043-463d-85b3-88fca513f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>novaccinatereason</value>
      <webElementGuid>b7845798-fa03-4c5c-a537-79392bbf4350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>95d1f64e-def1-443c-9f43-b3b2decfd225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fc7442fc-e31a-4654-aabd-dc095663d49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>novaccinatereason</value>
      <webElementGuid>935416b8-50ee-43ba-8c3f-dc96308d4757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker printworthy  hidden-print</value>
      <webElementGuid>8a4a0de1-4ca3-4fe4-bd07-4555c307cdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;novaccinatereason&quot;)</value>
      <webElementGuid>cd39fc14-a3c1-4d27-a295-06a1e9fd1f77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='novaccinatereason']</value>
      <webElementGuid>f6b75686-cd23-4b7c-af44-8c62721af953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_immunization']/div[2]/div/div/div[5]/div/div/textarea</value>
      <webElementGuid>686eede3-2b5d-4e3e-9b49-7b2ceb37b230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/textarea</value>
      <webElementGuid>73e670df-5018-4e56-a86f-afa393edcde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'novaccinatereason' and @id = 'novaccinatereason']</value>
      <webElementGuid>c0aadbc7-c6e2-4166-9303-5469c4db0a1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
