<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_A Client A Automation</name>
   <tag></tag>
   <elementGuidId>2a74da3b-43fe-4753-aa97-c387abb80f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clientNameHref']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clientNameHref</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#clientNameHref</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>697fee31-6719-40a7-bdf8-32ce33bbeae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/client/index/1556?section=scheduling </value>
      <webElementGuid>8add90aa-d1dc-4238-a315-ddc1ad871991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8beefa1f-88b4-42e3-a28a-f3d15cc5fa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientNameHref</value>
      <webElementGuid>9da7a4ce-b704-486e-b1f9-671544337ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A Client A Automation</value>
      <webElementGuid>7750fa25-442d-4468-b354-a514bd32f8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientNameHref&quot;)</value>
      <webElementGuid>d5af9516-44f1-4a19-9c48-bde5ab7381f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='clientNameHref']</value>
      <webElementGuid>1ecb4c35-6574-4466-b735-5a2b15f37701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profileInfoIcons']/div/a</value>
      <webElementGuid>07be4dfa-ffc5-44e9-a8f5-277b4e2e9cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'A Client A Automation')])[2]</value>
      <webElementGuid>1e380a58-7ea8-49c1-b86c-1bcd17d6def4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revise Schedule for'])[1]/following::a[1]</value>
      <webElementGuid>4b1f7b61-fed7-497b-ac6f-a4e4c974a58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H:'])[1]/preceding::a[1]</value>
      <webElementGuid>82318b4c-7f8f-4fb6-aacd-628cbd86969b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C:'])[1]/preceding::a[2]</value>
      <webElementGuid>af135c8d-731d-4806-a1e7-143a40685eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/client/index/1556?section=scheduling ')]</value>
      <webElementGuid>c024e09c-3b42-49d5-9d94-4746ba98585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>230be029-cb94-4074-8ec0-cf8222788f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/client/index/1556?section=scheduling ' and @id = 'clientNameHref' and (text() = 'A Client A Automation' or . = 'A Client A Automation')]</value>
      <webElementGuid>1925c445-6344-4f70-997a-cadd6090de05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
