<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Respiration_resp</name>
   <tag></tag>
   <elementGuidId>a79a7435-dc78-48c8-bf5a-9ca376e76d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='resp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Respiration:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6d6d06f-aae5-42c5-9091-d02649c31278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecfb3af5-8436-4004-8023-73ee91ee2e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resp</value>
      <webElementGuid>79f354e2-b67e-4b04-806d-f9279fc1ecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resp</value>
      <webElementGuid>eeaa0ef3-e249-41ce-903e-e64964241e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsfield</value>
      <webElementGuid>94539f32-7144-4043-8d0a-cdff3d0a4546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resp&quot;)</value>
      <webElementGuid>5f38fd67-b54a-4c91-8468-45c85e5a3b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='resp']</value>
      <webElementGuid>01e8b26e-98ce-4e5c-b16c-fffde90e7281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsedit']/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>db5ac5ff-07bf-43e2-8e5c-d1f9ee26cfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ec9fdf88-d155-4225-ad5a-a46d500b556f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'resp' and @id = 'resp']</value>
      <webElementGuid>9d5ff548-b1fc-48e8-93b4-3c2edaf389a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
