<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Temperature_temp</name>
   <tag></tag>
   <elementGuidId>ac0f05b4-571b-4493-bad5-4beb830476da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#temp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='temp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Temperature:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7951d7eb-7e2f-4c16-adf8-bdb0b961e18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9637be26-9668-46d7-963e-15ab9bc4fd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>temp</value>
      <webElementGuid>da93ea1e-ed72-44cf-af99-44e65b00359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>temp</value>
      <webElementGuid>795cf378-cd26-4d56-aef9-2f1fbcc2110a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsfield</value>
      <webElementGuid>63d33f0f-dd76-4c17-bbe9-af2d7e86ea2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temp&quot;)</value>
      <webElementGuid>82374ffe-98a8-449b-8204-7aa82f582054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='temp']</value>
      <webElementGuid>6780d11e-9088-4835-916b-239f005719a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsedit']/div/div/div[2]/div/div/input</value>
      <webElementGuid>1bb77106-0662-4a80-a0d1-db925798c146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>4efc7bcb-99bd-4341-b0f2-9f32febce1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'temp' and @id = 'temp']</value>
      <webElementGuid>ef4b008f-2e4d-4259-be49-25e7b923ebca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
