<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_O 2 Saturation_o2</name>
   <tag></tag>
   <elementGuidId>62fd0332-10b8-4371-b6e5-28678d76cbcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='o2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;O 2 Saturation:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2e07cd4-1a58-4a29-80cb-e0b788d5db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba60b6c3-b5ce-4567-83fb-3772de5e5acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>o2</value>
      <webElementGuid>eab23030-7638-49da-829c-b2d1eb9a66d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>o2</value>
      <webElementGuid>88e6dd63-5449-456c-9738-d47c2d007341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsfield</value>
      <webElementGuid>a3dbd650-f36d-4fa5-8ea3-359c6bcadc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o2&quot;)</value>
      <webElementGuid>010cadd4-a5c7-49b8-840c-ab98dd0fbc6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='o2']</value>
      <webElementGuid>412a5e02-25c3-4a93-b696-66635544d62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsedit']/div/div/div[3]/div/div/input</value>
      <webElementGuid>e2a60d51-fb1a-404b-adbe-0d9f7c63d205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>dc3f4aaf-936c-4b31-b423-b90b9d2b1650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'o2' and @id = 'o2']</value>
      <webElementGuid>0f8f75eb-9f0a-43e4-b20a-a30f9ee1ff51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
