<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inhaled Oxygen Concentration_inhaled__06efa9</name>
   <tag></tag>
   <elementGuidId>f31b6d7e-771b-4902-93f4-731f6ce971c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inhaled_oxygen_concentration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inhaled_oxygen_concentration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Inhaled Oxygen Concentration:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ca8b0ab-1341-432d-8734-506f683bb550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c1d1bdee-d13a-4968-b4ef-44a82634ea2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inhaled_oxygen_concentration</value>
      <webElementGuid>2183d350-3bc9-4f7c-82a1-1dfb373ee433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inhaled_oxygen_concentration</value>
      <webElementGuid>8b5bcd3b-7e73-4ec1-a8a5-21de91ba4bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsfield</value>
      <webElementGuid>8a5bced6-5649-410c-bcbe-ed9476fb9d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inhaled_oxygen_concentration&quot;)</value>
      <webElementGuid>776cc2ad-9e30-4deb-9db2-b9c648ad7942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inhaled_oxygen_concentration']</value>
      <webElementGuid>32b7f51f-0074-40f1-9439-0b23841d9173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsedit']/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>fabe5883-dc3b-4b4f-a64b-18bce16ace4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>4c784a95-817a-45ae-bb86-940b15bf0177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'inhaled_oxygen_concentration' and @id = 'inhaled_oxygen_concentration']</value>
      <webElementGuid>d01d8086-6daa-491a-91cb-24021c432d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
