<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pulse_pulse</name>
   <tag></tag>
   <elementGuidId>277a9d68-f67d-497b-a708-9ca68a779c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pulse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Pulse:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4f055b8-a283-4b7b-bf22-68d81b252469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8523ad9-e104-4940-ab2d-06264a9dfe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pulse</value>
      <webElementGuid>08eb8df6-aa32-4549-8e39-855cc5fccfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulse</value>
      <webElementGuid>753cca72-1ca4-4efd-a588-9fa62dba46d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsfield</value>
      <webElementGuid>51a17a77-aea9-48e4-b19f-4919db9dfee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulse&quot;)</value>
      <webElementGuid>9db760ac-3c31-4d85-bd5a-3a2fa70a57a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pulse']</value>
      <webElementGuid>438e03af-f88f-4ccb-ac8a-c285e576f3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsedit']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>3787abe6-7487-48b1-a257-8349a29a2c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>8310fc51-f436-4f7a-a2a1-76186c2c9ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pulse' and @id = 'pulse']</value>
      <webElementGuid>10031acb-659c-4ce9-bda5-ed2f57e71e31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
