<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_chevron_left                Back to Profile</name>
   <tag></tag>
   <elementGuidId>9214fa26-200a-479e-be98-7427f5bbd0d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#back-to-client-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='back-to-client-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;chevron_left Back to Profile&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5034ff1-88a8-47dd-8518-b2dc2010b673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://site17.lsapp.cloud/client/index/1557</value>
      <webElementGuid>8c22128d-3414-479a-a5b3-7cbc7ec981f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>back-to-client-button</value>
      <webElementGuid>0c101cec-14f1-47ec-a444-9a935ac502d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-print</value>
      <webElementGuid>b831a0db-6bdd-4e8f-acd0-78dcc9cc20e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                chevron_left
                Back to Profile
            </value>
      <webElementGuid>c4941ce9-6171-4a60-a44d-40f03abd5541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;back-to-client-button&quot;)</value>
      <webElementGuid>52b91bb8-535b-41a9-ba9d-370104f3ce4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='back-to-client-button']</value>
      <webElementGuid>39c22c95-f576-4eb1-a394-59f9ffe184e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='homepage'])[1]/following::a[1]</value>
      <webElementGuid>53a5ac34-6fa4-4fa4-bf54-22fd04d55a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chevron_left'])[1]/following::a[1]</value>
      <webElementGuid>b59e3914-6ac8-4e1b-bbcc-fd0dd215cf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://site17.lsapp.cloud/client/index/1557')]</value>
      <webElementGuid>2625b592-a1f7-45d1-b2b8-9544c9ae7d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a[2]</value>
      <webElementGuid>79c5ff9f-882d-4ca2-940d-547c4fae4f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://site17.lsapp.cloud/client/index/1557' and @id = 'back-to-client-button' and (text() = '
                chevron_left
                Back to Profile
            ' or . = '
                chevron_left
                Back to Profile
            ')]</value>
      <webElementGuid>a82caa6f-f7a1-4bdd-bd0a-b099fdcba3e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
