<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mark as Error</name>
   <tag></tag>
   <elementGuidId>b8e3d774-61ed-4876-a00b-967c4e6a9e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnmarkeie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnmarkeie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Mark as Error&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b232154e-7658-42c2-8ad7-ee1563225a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70673085-66b3-4afc-b523-dc617c760dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-raised btn-block</value>
      <webElementGuid>769f140b-ff2e-420d-8ba3-ea3847fd6300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmarkeie</value>
      <webElementGuid>319dcac5-e8d4-44db-8673-a30f4f6fa46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:disabled</name>
      <type>Main</type>
      <value>reason.length &lt; 4</value>
      <webElementGuid>112d43cb-e239-4b22-823f-32c0fbfd4725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>submitEie(reason); showEieMessage = true;</value>
      <webElementGuid>aa048c0d-c264-462e-80a1-b67883d5bf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Mark as Error
                </value>
      <webElementGuid>1767c7c6-2a0c-4abc-9b3c-c12c9dfa15e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnmarkeie&quot;)</value>
      <webElementGuid>fe0c2041-f73c-49fa-b834-5a25e80bae71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnmarkeie']</value>
      <webElementGuid>75055a43-5d52-4407-8ce7-1bde162537d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clientmed.edit']/div[2]/div/div[2]/button</value>
      <webElementGuid>780d22dc-2b3e-4900-82e5-39be1eec57e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason:'])[1]/following::button[1]</value>
      <webElementGuid>1661f531-6efc-4d24-8dae-5043a94e0bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This document has been marked as error.'])[1]/preceding::button[1]</value>
      <webElementGuid>b5986302-5d63-42f0-a71c-9ab14c3dc5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mark as Error']/parent::*</value>
      <webElementGuid>31812fb7-eb59-4fd3-a08b-ec48afc1929d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>df7a07c5-5570-4056-b742-820b61ddbc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnmarkeie' and (text() = '
                     Mark as Error
                ' or . = '
                     Mark as Error
                ')]</value>
      <webElementGuid>f24d828a-3706-4a41-aeb5-b17f91ac0773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
