<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Client Orientation</name>
   <tag></tag>
   <elementGuidId>3db37446-05ca-493f-a53f-ebf3bdeb8650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-BF2F47C5-A42C-4A6B-9303-58C2F5929498-result-43tt-Client Orientation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Client Orientation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>62aaf3fa-984d-4524-8ae5-38b5d2c951b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>6ffd7898-1c12-482e-aefc-ceb128c94a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-BF2F47C5-A42C-4A6B-9303-58C2F5929498-result-43tt-Client Orientation</value>
      <webElementGuid>b1cf54e8-40f1-4d16-8f15-883e97c7e6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>c61115d3-2f1a-49bd-aae9-8e5262d36c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>551e23b0-389a-457b-ab25-362612e620cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client Orientation</value>
      <webElementGuid>fc5ab766-6f42-444d-a74c-c205e9317d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-BF2F47C5-A42C-4A6B-9303-58C2F5929498-result-43tt-Client Orientation&quot;)</value>
      <webElementGuid>7854f86f-ad86-4402-adc4-8f82c9eecc5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-BF2F47C5-A42C-4A6B-9303-58C2F5929498-result-43tt-Client Orientation']</value>
      <webElementGuid>4863a4da-1bce-4b4a-9c36-5d9709ecfac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-BF2F47C5-A42C-4A6B-9303-58C2F5929498-results']/li[5]</value>
      <webElementGuid>feec5574-7911-43ea-9852-f3da9b6616fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Grievance Procedure'])[2]/following::li[1]</value>
      <webElementGuid>aa06bd42-c32f-477d-a8d6-8cb6e0f786ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIWA B Assessment'])[3]/following::li[2]</value>
      <webElementGuid>771cf8e7-ad2b-416c-9e92-5d399f40b2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consent for Disclosure'])[2]/preceding::li[1]</value>
      <webElementGuid>bc450b43-083a-4bae-b856-8e3f4cdd7a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consent for Emergency Medical Care'])[2]/preceding::li[2]</value>
      <webElementGuid>5f8c9e83-860a-4313-831a-460235c9dbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul/li[5]</value>
      <webElementGuid>ea37057a-4eb9-4438-be1f-cd0803d51a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-BF2F47C5-A42C-4A6B-9303-58C2F5929498-result-43tt-Client Orientation' and (text() = 'Client Orientation' or . = 'Client Orientation')]</value>
      <webElementGuid>7668d713-d354-4e85-9116-933fdd5e5e28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
