<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Clients</name>
   <tag></tag>
   <elementGuidId>80b1603f-adf5-46dc-b7cc-6bafae3af37f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='groupsection']/div[2]/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#groupsection button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed005036-df9a-4d5e-b26f-d2224fa9d213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>d1a54b34-f86b-44c3-bf4c-08d76e43f137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Clients</value>
      <webElementGuid>824a1410-aedf-45db-a91b-2c34cd35c432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupsection&quot;)/div[@class=&quot;col-md-4 col-sm-4 col-xs-12&quot;]/div[@class=&quot;form-group ls-form-group&quot;]/div[@class=&quot;ms-parent multiple-select ls-multiple-select&quot;]/button[@class=&quot;ms-choice&quot;]/span[@class=&quot;placeholder&quot;]</value>
      <webElementGuid>c9e24142-8ad9-480c-82c7-b21d419612ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupsection']/div[2]/div/div/button/span</value>
      <webElementGuid>247a4a8f-2ce8-4fa6-a293-641622a53e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enroll Clients'])[1]/following::span[1]</value>
      <webElementGuid>c9aa8980-b4e2-4f8a-ae6f-ad34b2597da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[1]/following::span[8]</value>
      <webElementGuid>176210d6-e1f9-4f9d-8317-1343e42ae452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C Automation, C Client MR# 24-11008'])[3]/preceding::span[1]</value>
      <webElementGuid>571b4e84-1be5-4e39-b567-cb9dd7b3d1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No matches found'])[1]/preceding::span[2]</value>
      <webElementGuid>dc67d20d-61e4-4908-b3ef-1a6e78bf91d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Clients']/parent::*</value>
      <webElementGuid>e69d7230-6e92-4565-90af-5c6423e310cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/button/span</value>
      <webElementGuid>7af50c72-1775-4aa2-be08-99d2515582fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Clients' or . = 'Select Clients')]</value>
      <webElementGuid>d673f9fe-b543-4cdf-953b-55e8df019d10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
