<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mark as Error</name>
   <tag></tag>
   <elementGuidId>d0152111-5227-4f7e-855c-7561c1568da2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnmarkeie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnmarkeie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Mark as Error&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3dbd9d95-2532-4fcd-b255-6d835e67edf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bbde792-f29e-4285-b7ff-dc1f946607ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-raised btn-block</value>
      <webElementGuid>bd57e34f-5769-40a9-9fbd-346a506dc9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmarkeie</value>
      <webElementGuid>60b16855-3e33-4522-9175-a269a8605abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:disabled</name>
      <type>Main</type>
      <value>reason.length &lt; 4</value>
      <webElementGuid>7670a353-8840-4ced-8275-93c3a2824719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>submitEie(reason); showEieMessage = true;</value>
      <webElementGuid>76f64e3e-d2c6-43ed-b33b-02e70e638cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Mark as Error
                </value>
      <webElementGuid>45887c48-5e79-43bc-aa91-a64008a704f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnmarkeie&quot;)</value>
      <webElementGuid>3291521b-8c1f-4935-904d-95a179326c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnmarkeie']</value>
      <webElementGuid>d3157a92-aa73-4cb5-b21a-5202ea39d797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clientdx.edit']/form/div/div/div[11]/div/div[2]/button</value>
      <webElementGuid>ce76c3d4-4f47-4117-8ff4-df4edddc6ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason:'])[1]/following::button[1]</value>
      <webElementGuid>aa058109-f186-4b6b-8caf-e4676fe2f33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This document has been marked as error.'])[1]/preceding::button[1]</value>
      <webElementGuid>bf2f32b2-712b-421a-ae94-3a5a2f3e3f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mark as Error']/parent::*</value>
      <webElementGuid>069c4715-e9ed-4dc6-a697-652cbe1bedbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>5439a970-c447-43e3-a731-ad861370ac93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnmarkeie' and (text() = '
                     Mark as Error
                ' or . = '
                     Mark as Error
                ')]</value>
      <webElementGuid>dd71974e-9e94-4c60-a7e6-1e77193d435b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
