<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --Chemical Dependen_f373e3</name>
   <tag></tag>
   <elementGuidId>bfcd9357-6682-4821-a7da-153498fde2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dxcategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dxcategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Diagnosis Category:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>652634d7-461e-46df-9c1a-23442277534a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dxcategory</value>
      <webElementGuid>f4d27128-255b-401b-95ff-62b18aeb99f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dxcategory</value>
      <webElementGuid>9f43a1b5-ea7d-45f0-b0fd-291869d18300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control savecontrols</value>
      <webElementGuid>4db121f2-70ba-4bea-807e-5cc2a65ef22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please Select --Chemical DependencyMental HealthOther</value>
      <webElementGuid>942cd0fd-e2ac-4620-8b8b-cfa48be39186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dxcategory&quot;)</value>
      <webElementGuid>010b9293-c5e3-4e47-9c54-ddae638f6590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dxcategory']</value>
      <webElementGuid>6be21e2d-afe0-4409-925a-65475aafd0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='clientdxform']/div/div/div[3]/div/div/select</value>
      <webElementGuid>e55cb1c8-caf2-4b3a-aea5-f095fbb6464e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis Category:'])[1]/following::select[1]</value>
      <webElementGuid>591ce00a-ae55-4e60-8e66-81518b772c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Diagnosis Priority'])[1]/following::select[2]</value>
      <webElementGuid>5ae4ddb0-087d-4097-b5c4-01af6d298fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/preceding::select[1]</value>
      <webElementGuid>ac3f69d2-b77a-483a-9b24-23349026dbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis:'])[1]/preceding::select[1]</value>
      <webElementGuid>6d338837-98ef-4afa-90c1-fd9a62c1947e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>ba28152f-cefe-4e6c-888f-cc55e0b3d63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dxcategory' and @id = 'dxcategory' and (text() = '-- Please Select --Chemical DependencyMental HealthOther' or . = '-- Please Select --Chemical DependencyMental HealthOther')]</value>
      <webElementGuid>475d8379-3151-43ba-8e87-f3a32e6c521e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
