<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_edit</name>
   <tag></tag>
   <elementGuidId>5841f64c-a93b-4b7e-b206-71534ed4acd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Mens Residential'])[10]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.tablesaw-cell-content > a.main-yellow-a-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 - 1A B Automation, B Client 1673 08/28/2024 2:34 pm Female Blue Cross Blue Shield of Texas edit&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07e528bd-7c19-4ec3-ac01-78f3b2e5e807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-yellow-a-btn</value>
      <webElementGuid>5528cdfd-62e2-4ae9-bc3d-5b37e118dd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://site17.lsapp.cloud/roombedassignment/60/edit</value>
      <webElementGuid>726069c8-9851-4a12-b18a-4e1c2efc1960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>03baefeb-471e-44d8-a5b9-fd6d8d3fa4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                edit
                                            </value>
      <webElementGuid>9d8f8117-a975-4ff4-9ab9-b951270dab60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablesaw-4027&quot;)/tbody[1]/tr[1]/td[8]/span[@class=&quot;tablesaw-cell-content&quot;]/a[@class=&quot;main-yellow-a-btn&quot;]</value>
      <webElementGuid>2d338c2f-b1c6-4e17-956e-eeca3642485f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablesaw-4027']/tbody/tr/td[8]/span/a</value>
      <webElementGuid>6f2f88a3-f022-402c-88c1-5c6e16ec3064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mens Residential'])[10]/following::a[1]</value>
      <webElementGuid>c6eb3668-5591-4830-ac97-6578e12ea0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mens Residential'])[9]/following::a[1]</value>
      <webElementGuid>01f2cf4e-7b3f-4377-a65b-6a1d5f2a39d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mens Residential'])[11]/preceding::a[1]</value>
      <webElementGuid>945639dd-03e8-4d0f-8b80-3b36a75d3fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://site17.lsapp.cloud/roombedassignment/60/edit')]</value>
      <webElementGuid>3552c95c-18d1-4c14-83eb-12dc87264cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>0ddf70ee-4338-4d90-bb8b-c3d0921c1e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://site17.lsapp.cloud/roombedassignment/60/edit' and (text() = '
                                                edit
                                            ' or . = '
                                                edit
                                            ')]</value>
      <webElementGuid>0384a2df-5737-4769-bda4-43b1884719b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
