<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mark as Entered in Error_locker print_2e6d18</name>
   <tag></tag>
   <elementGuidId>2cb08980-000b-4851-b4c3-2b40834d7e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.locker.printworthy.hidden-print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='0'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mark as Entered in Error&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea9a6e30-0472-456e-a696-ce42bc4aa3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>622b73cb-4913-4782-ac66-aae25b7af662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker printworthy hidden-print</value>
      <webElementGuid>b638617e-4b05-41d2-af6e-05ae8aabe03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>showEie = !showEie</value>
      <webElementGuid>d3949ccc-6230-4da7-895f-48efd8bfed1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>form.eie</value>
      <webElementGuid>b4d61034-cad0-4d62-bf57-d152f6bb8266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af8d8c43-f7c9-44be-af08-53eb9d50ae0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medorder.edit&quot;)/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[1]/div[1]/div[@class=&quot;tab-content&quot;]/div[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;print:hidden&quot;]/div[1]/div[1]/div[@class=&quot;checkbox-simple hidden-print&quot;]/label[@class=&quot;control-label&quot;]/input[@class=&quot;locker printworthy hidden-print&quot;]</value>
      <webElementGuid>f6a08473-f758-4ff9-aa84-c950096abad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='0'])[3]</value>
      <webElementGuid>826f6af1-dbff-41e2-a0c8-7e0a4382bc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='medorder.edit']/div[2]/div/div/div/div[3]/div/div/div/div/div[10]/div/div/div/label/input</value>
      <webElementGuid>0ac7a4e4-3949-4c0d-81b5-83ccc081ffe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/label/input</value>
      <webElementGuid>efbe046d-db53-4437-8753-97ef458e5e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>0731c63e-aa7a-48fa-8c4a-4185f32d7d80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
