<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Glucose Reading_reading</name>
   <tag></tag>
   <elementGuidId>ef6b86f4-8ad0-4ecc-b14e-bb0e9782a0f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Glucose Reading:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96493f18-650a-48f2-8246-a804d749bb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4669e610-c2e7-4051-8e85-a2d1c1276a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reading</value>
      <webElementGuid>a3cb8abb-15b3-4fac-8f49-dc7366e814c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reading</value>
      <webElementGuid>d1a3a391-cd18-4b03-ba31-6f9e61db0b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e0e4236-54b4-4bc4-8f67-70b8be6daae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>9c74dc42-1297-4451-8ba7-9a97d5e5cdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reading&quot;)</value>
      <webElementGuid>ddb6a35a-5c2f-4529-a551-46e0cc9b5149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reading']</value>
      <webElementGuid>7ad295c1-9952-4080-8375-7a9f1cb766a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glucose.edit']/form/div/div/div[2]/div/div/input</value>
      <webElementGuid>7292d483-8ef9-4d0e-a70a-4fa8e33635ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>44090e03-4747-40d2-894e-67aedcf14431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'reading' and @id = 'reading']</value>
      <webElementGuid>3228ff71-f99a-4db9-9fd6-16fa03ec8d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
