<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>3f2cf74b-b5c8-4145-87fc-3008dbb04aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnmainfrmsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnmainfrmsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d5767ac-3323-4c40-b054-b93221b1eace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-raised btn-primary btn-block locker nodoubleclick topazsig</value>
      <webElementGuid>7305f3f6-85a1-4623-b272-dcc0e6733429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5e56a616-2e71-40c8-92ad-d569ce5820e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>993f65e8-a3c0-474b-9e52-029141b65ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmainfrmsubmit</value>
      <webElementGuid>ee83a077-64a5-46c7-b784-bd0a59b7982f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save
        </value>
      <webElementGuid>a8342a89-372b-461e-8fb9-e6564b5f1b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnmainfrmsubmit&quot;)</value>
      <webElementGuid>7b0525a1-de58-4908-99a6-13c25bf8c146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnmainfrmsubmit']</value>
      <webElementGuid>baadfdb2-d072-44f2-a37e-d48473796496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='balscreen.edit']/div[2]/div/form/div/div/div[10]/div/button</value>
      <webElementGuid>25edecbc-870d-43bf-bb4b-4b9cdaba07ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/following::button[2]</value>
      <webElementGuid>0015fd8b-aaa7-4804-b710-03ac4dfb0f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creator / Last Editor Name - Automation Test'])[1]/preceding::button[1]</value>
      <webElementGuid>c1975738-b585-4f5a-9124-4006db9b97dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>edc86122-7573-4985-8c5c-1930c5f4d3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>9aa787fe-ea15-4c66-b893-1ad0ca2713f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and @id = 'btnmainfrmsubmit' and (text() = ' Save
        ' or . = ' Save
        ')]</value>
      <webElementGuid>63de6faa-56a9-4967-b8ba-461fc5d2fe12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
