<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BAL Reading_balreading</name>
   <tag></tag>
   <elementGuidId>c764f771-fa22-4141-b46b-6375c069b1e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#balreading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='balreading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;BAL Reading:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9210695-193d-4d64-b6b9-383636826ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07476be5-0b6e-4f1d-986d-563b4dd297c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>balreading</value>
      <webElementGuid>977ed469-6b45-42de-b603-72a3ff5a24f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>balreading</value>
      <webElementGuid>32f8bc0e-254a-4f7b-ad74-a1c3dfc67aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker printworthy hidden-print</value>
      <webElementGuid>d1944373-c182-4792-bf9d-0a2d89752a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;balreading&quot;)</value>
      <webElementGuid>62a7b91b-9750-4937-990c-bf82639149cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='balreading']</value>
      <webElementGuid>5da93a13-ff77-4003-ace4-2607f61ed2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='balscreen.edit']/div[2]/div/form/div/div/div[2]/div/div/input</value>
      <webElementGuid>39307ab5-4f44-44a5-95fa-896d7bab6e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>49bc5b30-cdf8-4e14-ad99-952b0e742701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'balreading' and @id = 'balreading']</value>
      <webElementGuid>703ddb8c-4e75-4cde-a8c7-6be0be5e9d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
