<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Admission Date_dateadmission</name>
   <tag></tag>
   <elementGuidId>e9d0910d-1b8d-4278-8638-21637e24d93b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateadmission</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateadmission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Admission Date:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdc1e29d-3824-4fed-aaeb-afbc620c1171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>a0b7db66-8891-495a-8459-5bb43a2c9c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dateadmission</value>
      <webElementGuid>a66e8af5-382a-4767-8782-0a1c9f2c799b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024-11-28</value>
      <webElementGuid>322c1525-e5af-455d-938e-91f480978b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateadmission</value>
      <webElementGuid>6ba49903-60f1-48e3-962e-d512cb714fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate_summary</value>
      <webElementGuid>5aee4296-23d1-4d95-9e54-684f58966fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateadmission&quot;)</value>
      <webElementGuid>1f8304b1-8dac-49aa-9fc9-eb7bb93f95c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateadmission']</value>
      <webElementGuid>8925ac49-0eb3-425d-a248-5c3eec26320c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='treatmentsummary.edit']/div[2]/div/form/div[2]/div/div[5]/div/div/input</value>
      <webElementGuid>9b81b3b5-d765-431d-b7a5-20cfabfee8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>3f208d7c-7faf-4716-ab3c-acefedf8f56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'dateadmission' and @id = 'dateadmission']</value>
      <webElementGuid>aae7e567-1788-402d-97d7-997b865f0764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
