<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Primary</name>
   <tag></tag>
   <elementGuidId>43d3025d-3f14-4302-9606-3d3fe6871cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.col-md-4.col-sm-4.col-xs-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbldxdisplay']/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Primary&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f41ce881-0356-4738-8a74-5bbfc5c71e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-sm-4 col-xs-4</value>
      <webElementGuid>59ce0c16-bd0e-4a7c-8dba-5864c276901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primary</value>
      <webElementGuid>7743977b-9f2f-44a3-8bdc-5488d794204e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbldxdisplay&quot;)/tbody[1]/tr[2]/td[@class=&quot;col-md-4 col-sm-4 col-xs-4&quot;]</value>
      <webElementGuid>1cc19fb4-dc10-4540-b424-429805f838b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbldxdisplay']/tbody/tr[2]/td[2]</value>
      <webElementGuid>ca8c61e3-a422-4865-9635-8b0cb429aa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alcohol Use Disorder, Mild (F10.10)'])[1]/following::td[1]</value>
      <webElementGuid>51f404c5-04dd-4cb5-bc44-c04de9f52d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rank'])[1]/following::td[2]</value>
      <webElementGuid>9a8ae408-341f-480d-aff5-c878ccba5cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Diagnoses as of the Date of this Document'])[1]/preceding::td[1]</value>
      <webElementGuid>040e0ebd-b85f-49ec-a95e-cf7d03426fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explanation of Diagnostic Impressions:'])[1]/preceding::td[2]</value>
      <webElementGuid>e3812e13-3cc1-4ebe-98f7-d6d3cacacab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Primary']/parent::*</value>
      <webElementGuid>3944913b-5501-414f-8cf1-7e76bf428774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>1f24d19f-f4b5-4a4f-875a-6f0bdb3b90dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Primary' or . = 'Primary')]</value>
      <webElementGuid>59154858-dc43-438a-9f32-99adc720adcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
