<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Counselor Highlights and Goals_cou_c6fc14</name>
   <tag></tag>
   <elementGuidId>a84e7011-a120-48d1-a0fa-25572fa59a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#counselorhighlightsgoals</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='counselorhighlightsgoals']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Counselor Highlights and Goals:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>70848f77-7ade-48aa-b94e-804bbba3e93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>counselorhighlightsgoals</value>
      <webElementGuid>f720f22c-5af8-422f-b4e7-9ef12b880dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>21eee8b2-fe8e-4792-8edf-1420c7ef928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>76257ffb-0033-4581-bb94-bf5c03342a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>counselorhighlightsgoals</value>
      <webElementGuid>e22853f8-6646-49b9-ae4e-d96155b69517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate_summary</value>
      <webElementGuid>48fca6af-1d64-49ad-bf78-089aa7504a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4ed7e176-c584-4e61-a307-a90b2501df4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counselorhighlightsgoals&quot;)</value>
      <webElementGuid>016f7719-1bca-4b69-9c37-5edbb968514d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='counselorhighlightsgoals']</value>
      <webElementGuid>0178f707-cc1e-4ee5-b1f5-470b53359ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='treatmentsummary.edit']/div[3]/div/div[4]/div/div/textarea</value>
      <webElementGuid>ca3f7ffd-6615-4569-987d-45299a075fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>d5e9908a-ef29-446f-b798-38e3961dc423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'counselorhighlightsgoals' and @id = 'counselorhighlightsgoals']</value>
      <webElementGuid>04cef9cd-8566-4202-a8c4-bdbbfc6d2af9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
