<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Self Discovery and Resources_selfd_81c42a</name>
   <tag></tag>
   <elementGuidId>a3e03369-46dc-42b1-8e55-a56e311ac042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selfdiscovery</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='selfdiscovery']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Self Discovery and Resources:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>31ad53c3-8fc4-48dd-9835-c1d4f9e1086a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selfdiscovery</value>
      <webElementGuid>4d1c6904-eb3e-445f-b01b-f0f184177408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9c10c0cd-5a7f-4e98-be4c-7f0d8579f2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0d37aa5c-589f-48f9-9ce3-83207e6dfd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfdiscovery</value>
      <webElementGuid>821deb0e-17d2-478d-8ecb-1aa176260817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate_summary</value>
      <webElementGuid>2158ebdf-33c1-4030-816d-6d95f9385b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e37d9110-ac9f-46fc-94b1-0fef7c5937d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfdiscovery&quot;)</value>
      <webElementGuid>916c4394-0cb9-4de1-8f8e-253ee4f5414e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='selfdiscovery']</value>
      <webElementGuid>40b3188a-27e6-4916-ae33-33d68a1a1f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='treatmentsummary.edit']/div[3]/div/div[8]/div/div/textarea</value>
      <webElementGuid>7d9bcabd-5ae8-42ab-8623-8a831f24a1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/textarea</value>
      <webElementGuid>bc4d3667-5f06-40f3-b632-2af3ac89d1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'selfdiscovery' and @id = 'selfdiscovery']</value>
      <webElementGuid>61bff903-8fea-4f02-823f-f1d1607ea110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
