<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Explanation of Diagnostic Impressi_5c480f</name>
   <tag></tag>
   <elementGuidId>59f90fc8-9717-4c35-9e2d-c4556c9bfa63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dximpression</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='dximpression']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Summary of DSM V diagnostic criteria for top two active diagnoses&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e242580b-af1b-4c2f-9759-953153efe5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dximpression</value>
      <webElementGuid>33199ae0-ddf9-448f-beae-8043c86729c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7d32adc7-2682-42e1-afab-017a9c7a7a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>81383bad-770c-4da4-b288-eb46c7aa52df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dximpression</value>
      <webElementGuid>b73c640d-48b0-4d83-b738-a763b48e9b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate_summary</value>
      <webElementGuid>cfce9670-afbf-4bdf-ab43-ff3156350800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>95e20b68-01df-4ba1-beb5-f9abde4ccd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Summary of DSM V diagnostic criteria for top two active diagnoses</value>
      <webElementGuid>96a53665-3d0b-48aa-b0cf-7b73d3c1a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dximpression&quot;)</value>
      <webElementGuid>49a6c412-1f4d-4c68-b595-025e43099d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='dximpression']</value>
      <webElementGuid>4deeb807-75fa-4c26-8ca0-61003ffaa9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='treatmentsummary.edit']/div[3]/div/div[15]/div/div/textarea</value>
      <webElementGuid>5be5404f-a5c7-474a-b7b2-f5f075607bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/textarea</value>
      <webElementGuid>a9d3e253-d38a-4549-a76f-08fb3bb16551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dximpression' and @id = 'dximpression' and @placeholder = 'Summary of DSM V diagnostic criteria for top two active diagnoses']</value>
      <webElementGuid>51f101b0-13b0-4814-8f8c-009bdb94fa77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
