<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Psychiatry_psychiatry</name>
   <tag></tag>
   <elementGuidId>d733ad19-66dc-41ee-b5f0-acc3bc14f7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#psychiatry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='psychiatry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Psychiatry:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3ed44e90-b524-4546-8513-8647b4b894dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>psychiatry</value>
      <webElementGuid>933ba639-f90c-4da4-87a1-8d6d4641edca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>719d13e7-fe11-46f2-9e41-eb442ae5c78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c75a018f-5845-40ff-98a6-ca74e23d56ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>psychiatry</value>
      <webElementGuid>4ed16c7e-ac17-4db9-bb42-4dd5321becab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate_summary</value>
      <webElementGuid>21f92ce5-ed0e-481e-85c6-8263a7625069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f2045331-efa3-49f2-9be9-b16ec8d2369b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;psychiatry&quot;)</value>
      <webElementGuid>5f7ecd78-b1f7-41f5-97e7-f511524d0e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='psychiatry']</value>
      <webElementGuid>76aa02b0-7475-47db-bdb8-5b12a5984c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='treatmentsummary.edit']/div[3]/div/div[10]/div/div/textarea</value>
      <webElementGuid>c1f4e86a-33a0-4b40-9530-8345af41721f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/textarea</value>
      <webElementGuid>0ac8b990-9bb6-4d83-9e5f-de02db667e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'psychiatry' and @id = 'psychiatry']</value>
      <webElementGuid>c3a31e2a-7025-4d59-8a93-6c803e4a4d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
