<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How Addressed_mdl_allergy_add_howaddress</name>
   <tag></tag>
   <elementGuidId>433275cf-a0a1-4e76-81b7-7fca43f71071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl_allergy_add_howaddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl_allergy_add_howaddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mdl_allergy_add_howaddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d6be1bc-4bea-407b-a337-447c3bee98c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6867d6a-5c2c-4f84-bc4b-780a65565bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mdl_allergy_add_howaddress</value>
      <webElementGuid>6f747c49-d037-47e5-a8ea-5be285cb6f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl_allergy_add_howaddress</value>
      <webElementGuid>b6f22f9c-d735-456e-b2fd-b084bfa16ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capfield mdl_allergy_add_field</value>
      <webElementGuid>a22ecbd8-d6d6-447f-9ad4-18edf3d1d9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl_allergy_add_howaddress&quot;)</value>
      <webElementGuid>b9bafdc4-1af5-4e8f-899c-35330525ea09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl_allergy_add_howaddress']</value>
      <webElementGuid>9eafa10f-327b-49c8-8d5e-a7a945894932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdl_allergy_add']/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>2a543869-6344-448e-bfdc-1a418b6a496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>fa429aa2-37aa-4db3-9da9-2d266673a850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mdl_allergy_add_howaddress' and @id = 'mdl_allergy_add_howaddress']</value>
      <webElementGuid>5a6c4ded-313a-4a6d-9699-983060d372e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
