<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reaction_mdl_allergy_add_reaction</name>
   <tag></tag>
   <elementGuidId>44b47257-a12b-48df-8346-5463e135100d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl_allergy_add_reaction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdl_allergy_add_reaction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mdl_allergy_add_reaction</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2400dc5-76d1-4619-93e7-3c8bb4c9dc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c2d0a93-1e1b-40c4-a126-dc77b5d17f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mdl_allergy_add_reaction</value>
      <webElementGuid>8cf0a751-4c60-483a-bad5-40d9059a1c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl_allergy_add_reaction</value>
      <webElementGuid>ee908972-756d-414f-9a68-527715c48a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capfield mdl_allergy_add_field</value>
      <webElementGuid>356a1f20-6ac8-4fde-bc44-4a81bfd9055a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl_allergy_add_reaction&quot;)</value>
      <webElementGuid>9078e1c1-7560-488b-8006-52d9a7043dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl_allergy_add_reaction']</value>
      <webElementGuid>d3b718cd-2e51-476f-b97a-1f04ea9c7dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdl_allergy_add']/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>25b42206-8ce6-4895-bfe0-a81b5e2039dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>fb7ea56a-7e34-4a4d-85c8-166cc79fd4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mdl_allergy_add_reaction' and @id = 'mdl_allergy_add_reaction']</value>
      <webElementGuid>6ec2e47f-ff8c-451d-8732-36866a759b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
