<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --                 _809191</name>
   <tag></tag>
   <elementGuidId>734f2abb-fe00-4098-b99d-d8dd28945009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mdl_allergy_add_allergytype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdl_allergy_add_allergytype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mdl_allergy_add_allergytype</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>968f5e06-8e31-4f6e-9ce6-1194ba1a74ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mdl_allergy_add_allergytype</value>
      <webElementGuid>8680a50c-44a9-48e2-b2be-e3c59fb467d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl_allergy_add_allergytype</value>
      <webElementGuid>58e75858-6402-4495-a49b-a3f902209a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mdl_allergy_add_field</value>
      <webElementGuid>a325dd21-df51-4a4b-a731-93ece9da3043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                    -- Please Select --
                                                                    Food
                                                                    Medication
                                                                    Environmental
                                                                    NKDA
                                                            </value>
      <webElementGuid>ed46417a-5513-4bf2-877b-e10f412cd505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl_allergy_add_allergytype&quot;)</value>
      <webElementGuid>0d550098-1172-4b4f-9ca1-6e2ef06cf0ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mdl_allergy_add_allergytype']</value>
      <webElementGuid>9027307b-268c-4a4b-b77a-f17abdbc5d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdl_allergy_add']/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>fd64956e-6156-48eb-a13f-80888b5d4864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergy Type:'])[1]/following::select[1]</value>
      <webElementGuid>24053b43-d11a-4751-9b10-0b2b8c131ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergy'])[2]/following::select[1]</value>
      <webElementGuid>d30da781-93ca-4c6e-b059-1d99c8f55965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reaction:'])[1]/preceding::select[1]</value>
      <webElementGuid>cefd85f7-f7e5-468b-84e9-d68d9d1419de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Substance:'])[1]/preceding::select[1]</value>
      <webElementGuid>2f0ca710-fce8-44b0-ac76-86f60f6cf5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>b37dadb5-153e-4fcd-83d5-80b37f9fb9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'mdl_allergy_add_allergytype' and @id = 'mdl_allergy_add_allergytype' and (text() = '
                                                                    -- Please Select --
                                                                    Food
                                                                    Medication
                                                                    Environmental
                                                                    NKDA
                                                            ' or . = '
                                                                    -- Please Select --
                                                                    Food
                                                                    Medication
                                                                    Environmental
                                                                    NKDA
                                                            ')]</value>
      <webElementGuid>a8fd5028-3fae-4e83-976a-4011149f1a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Substance:'])[1]/preceding::select[2]</value>
      <webElementGuid>4bb1d3ec-830c-4b70-8383-ff965871411d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
