<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Potentially Life-threatening_check</name>
   <tag></tag>
   <elementGuidId>71bbf456-1d9d-4186-b78e-21f0767fc3a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mdl_allergy_add']/div/div/div[2]/div[4]/div[2]/div/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.col-sm-6.col-xs-6 > div.checkbox > label.control-label > span.checkbox-material > span.check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Allergy&quot;s >> label >> internal:has-text=&quot;Potentially Life-threatening&quot;i >> span >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49daf9a7-ba46-41cc-a0dc-614f7bee6468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>d2ac1ee2-5e1e-4801-b640-58d979ce2590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl_allergy_add&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-6 col-xs-6&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;control-label&quot;]/span[@class=&quot;checkbox-material&quot;]/span[@class=&quot;check&quot;]</value>
      <webElementGuid>95bf843c-3440-4cfe-b16e-427fb3d07481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdl_allergy_add']/div/div/div[2]/div[4]/div[2]/div/label/span/span</value>
      <webElementGuid>e77377e2-018b-45de-95f1-7edd1af9a3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label/span/span</value>
      <webElementGuid>04dd199c-cbb5-4dba-a1c2-1b4ab226b166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
