<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Eating</name>
   <tag></tag>
   <elementGuidId>a15d3d95-74d8-4010-bccc-769c7cac2b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl_allergy_row_86 > td:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Adrenal cortical hypofunction (disorder)'])[1]/following::td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Eating&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>030c7d4e-cadf-459f-b4b0-05ead3b27493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eating</value>
      <webElementGuid>093e2daf-c286-4990-ba72-84c2fc5672e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl_allergy_row_86&quot;)/td[6]</value>
      <webElementGuid>a95a6ff4-3503-40bf-86ad-9bc89f92cde8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='mdl_allergy_row_86']/td[6]</value>
      <webElementGuid>15910fe3-73f6-4419-ba05-8567824cb9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adrenal cortical hypofunction (disorder)'])[1]/following::td[2]</value>
      <webElementGuid>9b139827-4382-4189-8ff3-b5ecce1ca72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[4]/following::td[3]</value>
      <webElementGuid>a35067cb-d9e6-4e2e-acaf-3739b5900915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[6]/preceding::td[3]</value>
      <webElementGuid>d1f742e0-f4f4-41a1-80d1-e800bcd6d282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Alcohol Level for A Client A Automation'])[1]/preceding::td[3]</value>
      <webElementGuid>baeb33bf-5465-4aff-8eca-288ff8a61fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eating']/parent::*</value>
      <webElementGuid>ea8f609b-21c6-483b-9411-95868f09f84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/div/table/tbody/tr/td[6]</value>
      <webElementGuid>d1b35401-9d62-4858-9859-a975076dfe2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Eating' or . = 'Eating')]</value>
      <webElementGuid>1245103e-8512-49da-921a-9c77c766a0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='mdl_allergy_row_83']/td[6]</value>
      <webElementGuid>6bbc6fd1-c63a-4e84-b7c5-aa03a36b70a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severe (severity modifier) (qualifier value)'])[1]/following::td[1]</value>
      <webElementGuid>f2ea05c2-fcfe-4e5b-add9-5b316ea38f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bronchitis (disorder)'])[1]/following::td[2]</value>
      <webElementGuid>20d417db-4562-43f5-81a1-19846e2ae0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
