<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_No allergies to display</name>
   <tag></tag>
   <elementGuidId>deec7a24-c8fa-48e3-8b24-06ecc30c41bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='mdl_allergy_row_0']/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdl_allergy_row_0 > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;No allergies to display&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e47dc664-8505-450a-be17-1c0d44078b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6f1c6307-c302-492f-a8a2-27d7f035bdc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No allergies to display</value>
      <webElementGuid>380711cc-1ea0-42fc-8782-1fc3123860c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl_allergy_row_0&quot;)/td[1]</value>
      <webElementGuid>3ad89ef0-326f-4f95-9b11-05a770dc3d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='mdl_allergy_row_0']/td</value>
      <webElementGuid>99f667ae-04a3-4eeb-ae6f-4ccb9b8cab81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Added'])[1]/following::td[1]</value>
      <webElementGuid>189ea10a-a0e0-4979-ac5b-604cd6a5893c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How Addressed?'])[1]/following::td[1]</value>
      <webElementGuid>142fa002-82cb-4ec7-8a91-b41bb2c1f0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[6]/preceding::td[1]</value>
      <webElementGuid>aa42188c-8906-4f38-b72b-e3670f701656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Alcohol Level for E Client E Automation'])[1]/preceding::td[1]</value>
      <webElementGuid>f9c03dfa-a9de-467e-99cf-135c09f09adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No allergies to display']/parent::*</value>
      <webElementGuid>22e746c1-509c-4a97-a11b-8c4740f19f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>1fb6d795-1d0c-49e4-b4ee-baef1d45ccf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'No allergies to display' or . = 'No allergies to display')]</value>
      <webElementGuid>05d35b74-0935-499d-9e7d-cac2cf755854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
