<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Not Selected --At MealsDailyEvery_c99cb7</name>
   <tag></tag>
   <elementGuidId>9824db04-17a8-4a9d-a21b-2a20fab4ab91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Frequency']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Frequency</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Frequency</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3268608a-9f20-4f59-8966-73a609c9fc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>9aad171d-71a1-4881-b4c4-b7a3f5ae08ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Frequency</value>
      <webElementGuid>beeec798-0244-40ac-b273-d911d8a6bf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fa7b887c-216a-44a8-9bb9-c182a68f8741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>How Often</value>
      <webElementGuid>7d78bacf-f9a8-4919-8bfa-5897d3aade56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Not Selected --At MealsDailyEvery 4 Hours, As NeededEvery DayEvery Day After DinnerEvery Morning Before BreakfastEvery NightEvery Night at Bedtime</value>
      <webElementGuid>ab53728f-f3db-4e1e-a907-ed746db090c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Frequency&quot;)</value>
      <webElementGuid>3c244e9d-2107-4a88-8980-de6b14c59cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Frequency']</value>
      <webElementGuid>0ba70b04-fe25-4261-9bd3-dd6a4df992ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createpresription']/div[2]/div/form/div/div/div[3]/div[4]/div/select</value>
      <webElementGuid>04c1b3eb-014c-44b2-a749-1d878099e01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency:'])[1]/following::select[1]</value>
      <webElementGuid>f2b4fa23-08c4-49e3-9689-6d54fc0ad5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Route:'])[1]/following::select[2]</value>
      <webElementGuid>e51053b9-c68e-4666-bc62-b43983aa56f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::select[1]</value>
      <webElementGuid>741946ce-7258-4026-81fc-4e10bb8de80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# Refills:'])[1]/preceding::select[1]</value>
      <webElementGuid>d32c002b-a61a-4082-911d-40044c2e4c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>39413749-7829-454d-8278-fc44eee56fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'frequency' and @id = 'Frequency' and @placeholder = 'How Often' and (text() = '-- Not Selected --At MealsDailyEvery 4 Hours, As NeededEvery DayEvery Day After DinnerEvery Morning Before BreakfastEvery NightEvery Night at Bedtime' or . = '-- Not Selected --At MealsDailyEvery 4 Hours, As NeededEvery DayEvery Day After DinnerEvery Morning Before BreakfastEvery NightEvery Night at Bedtime')]</value>
      <webElementGuid>78ce9d32-aac8-4bbe-99bb-5e349577c9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
