<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_----        Yes        No</name>
   <tag></tag>
   <elementGuidId>8639150c-b6fa-43d6-9d3c-045530c43bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='iscurrent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iscurrent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currently Taking?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f658efc-b340-44b2-9215-c24d456fb958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iscurrent</value>
      <webElementGuid>f5d6178b-a39d-4105-a931-de831850c786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iscurrent</value>
      <webElementGuid>24d2e01e-6305-411e-bee6-c0947c5f1d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7f199d1b-a745-400d-b76d-785d7b7e64c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        ----
        Yes
        No
    </value>
      <webElementGuid>9a241c66-0042-4cfd-a79f-4eb900f8d4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iscurrent&quot;)</value>
      <webElementGuid>1fb90435-0987-4b01-832e-a553a20b2314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='iscurrent']</value>
      <webElementGuid>33ec565c-655a-4e80-b02a-ee5e8d0028b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createpresription']/div[2]/div/form/div/div/div[11]/div/div/select</value>
      <webElementGuid>ab016f83-4f0d-409f-a4a9-e0452248f3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currently Taking?'])[1]/following::select[1]</value>
      <webElementGuid>d9801d96-b05e-494f-b323-91e3ffd8760a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Taken:'])[1]/following::select[1]</value>
      <webElementGuid>e2c0c258-d7b1-436d-aea2-a49328a1fa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective?'])[1]/preceding::select[1]</value>
      <webElementGuid>30428eb6-8b96-4b68-a4b5-ebdf2b1cb1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taken Last 6 Months?'])[1]/preceding::select[2]</value>
      <webElementGuid>e73b4488-8c1c-4cfc-98b7-cbdd681c86f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/select</value>
      <webElementGuid>fd00b55f-f2fd-4a66-bb44-b34c2db7e0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'iscurrent' and @id = 'iscurrent' and (text() = '
        ----
        Yes
        No
    ' or . = '
        ----
        Yes
        No
    ')]</value>
      <webElementGuid>4df8073e-8851-4388-a540-72de69ad9ed2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
