<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_----    Yes    No</name>
   <tag></tag>
   <elementGuidId>8db6c219-fdc0-4380-83d6-e8c343ff2585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='effectiveyn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#effectiveyn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Effective?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cfc77f35-2eaa-4cae-af89-550bbb6464f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>effectiveyn</value>
      <webElementGuid>b696ff26-4672-4dd3-94bd-74df2898659a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>effectiveyn</value>
      <webElementGuid>7377f99f-e290-43b6-8620-1075ee1a8cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a29eba35-6e3c-4ef1-9663-fc13f72e44ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    ----
    Yes
    No
    </value>
      <webElementGuid>3cb5edc0-f372-437e-97a8-7a332527d832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;effectiveyn&quot;)</value>
      <webElementGuid>227b280a-e821-4499-91be-688fee92c90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='effectiveyn']</value>
      <webElementGuid>1aa0f16d-272e-4b00-8ced-b7af10e8855c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createpresription']/div[2]/div/form/div/div/div[11]/div[2]/div/select</value>
      <webElementGuid>a8b94aec-294a-40bf-9f58-c4fbc9b56980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective?'])[1]/following::select[1]</value>
      <webElementGuid>9b3da088-7a5a-47e0-9b9d-3d84ef2b7858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currently Taking?'])[1]/following::select[2]</value>
      <webElementGuid>e16a8cf4-7aae-4c79-b057-1108a5121937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taken Last 6 Months?'])[1]/preceding::select[1]</value>
      <webElementGuid>4a1ec243-e366-491c-9649-3b901050bdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date:'])[2]/preceding::select[2]</value>
      <webElementGuid>cbcf8a42-8944-4e5d-a376-ea2cd691fa09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/select</value>
      <webElementGuid>3896e7f0-a4ad-45b8-80be-ec49eb7af6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'effectiveyn' and @id = 'effectiveyn' and (text() = '
    ----
    Yes
    No
    ' or . = '
    ----
    Yes
    No
    ')]</value>
      <webElementGuid>d6a481f7-76bb-4663-9866-0f653d856458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
