<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1</name>
   <tag></tag>
   <elementGuidId>e1d20c90-7a9d-4174-ae64-d076806b86ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-B428ACE5-7FE1-4A79-B897-04F506EBBC4E-result-leyv-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-mium-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>01cb73a2-348d-4d60-9f24-9f983dca7782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>ae2890af-35b6-4913-872b-e82a335e92e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-mium-1</value>
      <webElementGuid>60de3a25-446d-4e3e-a8d5-15a43bbad1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>b034c175-5a80-4881-b9d4-b124338cd22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6e54213-0b4f-474b-b434-33ce20675cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7018bf5f-e478-41a3-aed3-73163ca1385a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-mium-1&quot;)</value>
      <webElementGuid>16ccbdfc-3007-4dd6-8591-fca2e97c95fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-B428ACE5-7FE1-4A79-B897-04F506EBBC4E-result-leyv-1']</value>
      <webElementGuid>515d88ec-cf26-4996-b3e7-5987e67856f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-results']/li</value>
      <webElementGuid>d6bbc8a1-3bb8-4224-91d1-c57d48877bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::li[1]</value>
      <webElementGuid>64599f8c-eac6-4edd-9291-aaac8279121d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>a446382a-294a-4d68-94b7-a90bb609080e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-mium-1' and (text() = '1' or . = '1')]</value>
      <webElementGuid>a0675a69-6ea9-42e2-af27-9b88f7375fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
