<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_2A</name>
   <tag></tag>
   <elementGuidId>97f14af9-e938-451b-a25c-e9789f310e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-BBA4CB05-491F-4D68-B5A2-FF1F96F1398C-result-wht5-2A']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-B04E04BB-F137-4839-A4DA-6A2385789A08-result-i3zf-2A</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;2A&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>837962fc-3a7d-4910-aa26-a590e9ca0abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>a9fd8c24-e64b-4294-84de-ebb9861b4fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-B04E04BB-F137-4839-A4DA-6A2385789A08-result-i3zf-2A</value>
      <webElementGuid>58b3c7ef-aa48-4a3d-a7fe-516b3129c5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>3b2364cc-11a0-4b4b-b631-79be85cd59f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00af60c2-d375-4f66-95bc-a30c17fdfc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2A</value>
      <webElementGuid>e5600d43-53b2-4b3b-b0d9-034fdc654acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-B04E04BB-F137-4839-A4DA-6A2385789A08-result-i3zf-2A&quot;)</value>
      <webElementGuid>ed4b648c-99bb-45e9-bdb6-fffc1aa480ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-BBA4CB05-491F-4D68-B5A2-FF1F96F1398C-result-wht5-2A']</value>
      <webElementGuid>268e82e0-2c59-4784-bbf3-5b71297d8598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-B04E04BB-F137-4839-A4DA-6A2385789A08-results']/li[2]</value>
      <webElementGuid>4d217d4d-356c-4504-987a-397287ece854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::li[2]</value>
      <webElementGuid>804bc472-7ca3-4177-8b4d-ab1a45e41404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>77ca2533-8fbb-4d6d-a3e3-99edd77e656e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-B04E04BB-F137-4839-A4DA-6A2385789A08-result-i3zf-2A' and (text() = '2A' or . = '2A')]</value>
      <webElementGuid>3e0827d8-3c5e-4841-b20e-47863da4c5d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
