<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_2</name>
   <tag></tag>
   <elementGuidId>8f092bb2-3269-4225-8b08-597f1dd29466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-B428ACE5-7FE1-4A79-B897-04F506EBBC4E-result-1fko-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-7rtp-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d14b553-6cb1-4b4b-8006-1e474de178fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>d5d34e1f-9813-4ab6-9abb-8000c4d8e496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-7rtp-2</value>
      <webElementGuid>96e30feb-64b2-46fa-96d5-2548d7a5dc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>ac7efba8-c09a-45cd-9d81-6c0865dbbe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>622a5915-54a2-4c81-b5a5-040339d5b64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>eb3dfb7a-8ef5-484a-8fff-a79e51bf2c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-7rtp-2&quot;)</value>
      <webElementGuid>3b8ce4a0-25d6-4611-ab86-9ae219e656a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-B428ACE5-7FE1-4A79-B897-04F506EBBC4E-result-1fko-2']</value>
      <webElementGuid>75d7abf6-2d03-4aa9-bec3-22234770db6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-results']/li[2]</value>
      <webElementGuid>1b49a64c-5847-42ec-8424-06ee2bd82e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::li[2]</value>
      <webElementGuid>2936ffd9-ff6e-4243-bdcd-6f4e4a7b6a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>09873f26-1cb3-4d13-a76a-2ec8470fe420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-BF8E139A-0DCB-4120-BC76-F1FD7887B144-result-7rtp-2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>9d1ff93d-71be-4798-b8f8-92c7db8aaf25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
