<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve Selected</name>
   <tag></tag>
   <elementGuidId>ffd52828-8fcf-444f-b8ef-1bf78d384e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6 > button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='action'])[103]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Approve Selected&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6eb0bd15-d352-4e3b-ac14-01f007f0ab95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-raised btn-sm pleasewait</value>
      <webElementGuid>03d72532-bdd1-42cf-9332-af79b4ad0189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>037d0a7d-ed8d-43a5-bdb1-b6e8634073ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>b870c1c0-7e98-46aa-a8a2-a4bbc6f026e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>generate|selected</value>
      <webElementGuid>3cb18c9f-0709-4b12-8943-eff01d8b4bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.pleasewait').prop('disabled', true);$('#showspinner').show();document.getElementById('generate_charge_action').value = 'generate|selected';this.form.submit();</value>
      <webElementGuid>828d0ffa-d263-4761-9f7d-1e0d8053bbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve Selected</value>
      <webElementGuid>78eb4153-74ab-4ebb-98b3-392173a2dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formUnbilled&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;col-sm-6&quot;]/button[@class=&quot;btn btn-primary btn-raised btn-sm pleasewait&quot;]</value>
      <webElementGuid>0daff0e5-3a17-4319-a1c6-4100441065a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='action'])[103]</value>
      <webElementGuid>9d4f7691-c7da-4284-95a3-8f2f5467931b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formUnbilled']/div[4]/div/button</value>
      <webElementGuid>43917363-2094-4d32-b29f-a91215bbb7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 50 of 64 entries'])[1]/following::button[1]</value>
      <webElementGuid>6a819119-00e9-4110-8e87-a70e2cc2d3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[50]/following::button[1]</value>
      <webElementGuid>4b32292b-bc89-445c-b0cf-900b8d0314c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve All'])[1]/preceding::button[1]</value>
      <webElementGuid>7a808d4f-36ff-4129-b53f-c7ced7923031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claims Queue'])[1]/preceding::button[2]</value>
      <webElementGuid>3d85e6c1-5e7e-4ee6-90bc-44d0861de823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve Selected']/parent::*</value>
      <webElementGuid>faf29061-03fc-41de-b8bc-ff910ef42bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>572b0caf-62d4-40ba-ae9e-d08c11c55a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Approve Selected' or . = 'Approve Selected')]</value>
      <webElementGuid>f42d5cd2-d34a-43f3-b6a2-ab21b436ca33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
