<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Financial</name>
   <tag></tag>
   <elementGuidId>f003f76d-3abb-40aa-809e-cf4f2377fcb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainMenu']/div[8]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainMenu >> internal:text=&quot;Financial&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dabbbed0-f4ac-4a61-ab58-865539c5feb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-label</value>
      <webElementGuid>4795dd91-cfe7-4386-80ad-a76c46deb2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Financial</value>
      <webElementGuid>7009c339-d034-4dd8-9ca2-899110795068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/div[@class=&quot;menu-section&quot;]/div[@class=&quot;menu-section--title&quot;]/div[@class=&quot;title-label&quot;]</value>
      <webElementGuid>e1212c39-871c-403d-8363-a8b19c1fcc2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']/div[8]/div/div</value>
      <webElementGuid>e628d55f-77f0-4674-95a1-98bd5cd6fccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_balance_wallet'])[1]/following::div[1]</value>
      <webElementGuid>3d32e9f0-315d-49bf-ab23-f2773ed6cdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bed Assignment'])[2]/following::div[3]</value>
      <webElementGuid>64bcdcf1-1121-41a3-aa40-2d62c5afbe6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='monetization_on'])[2]/preceding::div[1]</value>
      <webElementGuid>a5d211f9-1b83-45e0-8560-db24cd1c8027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Financial'])[3]/preceding::div[1]</value>
      <webElementGuid>cb900cb8-6480-4c29-828f-d9a092bd4ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>937a1918-1b90-465f-944c-73d49d529d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Financial' or . = 'Financial')]</value>
      <webElementGuid>59aea412-35c6-4a3d-999f-e75f4728e154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
