<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>b6e6ea2a-57bc-460a-8530-77f35745326b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsaveLabResult</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnsaveLabResult']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Upload&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6dc7dd1-4654-4727-890c-055cbc19b036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-raised btn-block btn-primary btn-blue</value>
      <webElementGuid>b7d82d2e-a35a-4018-9db3-621538d3e4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsaveLabResult</value>
      <webElementGuid>03cfd811-6146-4310-b9e7-2214f9361f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9504d8c7-ddb4-461c-b6c4-0f37be2af9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>49ac712a-afb8-433d-babc-891ced333501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Upload</value>
      <webElementGuid>78ba0b25-f6af-4e66-9892-fc44dacf477c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsaveLabResult&quot;)</value>
      <webElementGuid>83dfc6d5-8c1f-4a84-9978-cc319e774ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnsaveLabResult']</value>
      <webElementGuid>943c09aa-c66f-4c56-b261-5ae8cf93740f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showaddexdocLabResult']/div/div[2]/form/div[5]/div/button</value>
      <webElementGuid>c5d8a5de-bb0b-4b7f-88a3-816643646f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign and Lock'])[1]/following::button[1]</value>
      <webElementGuid>8d409595-9df5-49d6-8279-8e25c5c91365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::button[1]</value>
      <webElementGuid>d72b0bdb-425d-4c2c-aede-2e22379236e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/div/button</value>
      <webElementGuid>5918b3cf-490c-4702-bcc8-e380295b6297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnsaveLabResult' and @type = 'submit' and @name = 'action' and (text() = ' Upload' or . = ' Upload')]</value>
      <webElementGuid>04d6fa2b-26d4-4dc9-a691-e913f5d9075e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
