<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Upload Lab ResultNew Lab Result</name>
   <tag></tag>
   <elementGuidId>173e1027-fb0e-4d53-bf99-9a2704dd48a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labresult_choose_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='labresult_choose_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add Lab Result&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5d14193-8321-48bb-9b28-cdb507cc5748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>labresult_choose_type</value>
      <webElementGuid>d7d0218e-0c77-4007-8280-9e10f7c9525a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labresult_choose_type</value>
      <webElementGuid>6f5e4907-864e-4d84-8c6d-d15b8af49268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control eplocker medevalbuttons</value>
      <webElementGuid>512f715c-4f58-45cc-a7d0-4eaaa7131ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload Lab ResultNew Lab Result</value>
      <webElementGuid>b576831d-216f-4c25-9dda-51d1fb82397f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labresult_choose_type&quot;)</value>
      <webElementGuid>cf9c2d70-a832-435b-9c07-cd319e7b98fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='labresult_choose_type']</value>
      <webElementGuid>34aec41c-02ca-4a11-972e-9bc5dddabd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tablabresult_include']/div/div/form/div/select</value>
      <webElementGuid>a58cd900-808e-4bad-93fe-ad092614c3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Lab Result'])[1]/following::select[1]</value>
      <webElementGuid>4ad06d24-14e6-4c59-83cc-3f7a8fd2378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[10]/following::select[1]</value>
      <webElementGuid>3b9ae828-90a2-4370-8447-21870fb72cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[17]/preceding::select[1]</value>
      <webElementGuid>f7afd16e-12d4-4b78-b4c8-433e753c4c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Lab Results for A Client A Automation'])[1]/preceding::select[1]</value>
      <webElementGuid>2f8c75b9-7d4b-41e7-a78c-4eaa01171b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/select</value>
      <webElementGuid>8931190d-d91a-40fc-862c-bc1d218613e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'labresult_choose_type' and @id = 'labresult_choose_type' and (text() = 'Upload Lab ResultNew Lab Result' or . = 'Upload Lab ResultNew Lab Result')]</value>
      <webElementGuid>ce8e3023-5cf1-457c-a42c-4fd46e280cad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
