<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --COVID-19 RapidCOV_75c690</name>
   <tag></tag>
   <elementGuidId>43638cd8-6322-48ce-9156-9bb1cc04e77b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ordername_select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ordername_select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ordername_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d63f04c8-9de7-4c87-bf4d-2d05ba8f8817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ordername_select</value>
      <webElementGuid>bc9d1a44-39ae-44ed-b4e5-0569b9ad08b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ordername_select</value>
      <webElementGuid>5a005f64-dd51-487c-9644-bc6d62417d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker printworthy labresult_field select_text_switch_field width80</value>
      <webElementGuid>f7c5e4aa-f9ac-4a84-8e30-1a74a987a8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hidden</name>
      <type>Main</type>
      <value>labresult_title</value>
      <webElementGuid>eab31f22-39bc-447f-b4e3-ac608eac8a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please Select --COVID-19 RapidCOVID-19 PCRCOVID-19 AntigenInfluenzaStrepMono</value>
      <webElementGuid>0e1bf025-17ad-481d-8fe5-3f29a72c43ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ordername_select&quot;)</value>
      <webElementGuid>1bb34fd8-9076-475f-953d-0c0ad157af7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ordername_select']</value>
      <webElementGuid>8972abb2-19d8-4885-b586-4be044a47018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ordername_select_holder']/div/select</value>
      <webElementGuid>3751b6ec-c467-41dc-932f-722d616209bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test:'])[1]/following::select[1]</value>
      <webElementGuid>e0b3fc4c-850b-4d64-b1e7-bbfabdc56f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test:'])[2]/preceding::select[1]</value>
      <webElementGuid>5c9317ae-8320-4994-837a-c141404d78d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Test:'])[1]/preceding::select[1]</value>
      <webElementGuid>70284409-48fb-462f-973c-0d2f67b68e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/select</value>
      <webElementGuid>cb2c7970-ac24-46f3-9a63-22b451126a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ordername_select' and @id = 'ordername_select' and (text() = '-- Please Select --COVID-19 RapidCOVID-19 PCRCOVID-19 AntigenInfluenzaStrepMono' or . = '-- Please Select --COVID-19 RapidCOVID-19 PCRCOVID-19 AntigenInfluenzaStrepMono')]</value>
      <webElementGuid>2b513a34-f323-4e44-8b52-86d2b9b39fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
