<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --NegativePositiveU_b19f9e</name>
   <tag></tag>
   <elementGuidId>c3ae7d5d-efcc-45bc-afb2-1ccd8d27d59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labresult_result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='labresult_result']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Overall Result:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c4b4fda2-f868-46fb-9a05-0b02f6da5ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>labresult_result</value>
      <webElementGuid>cc5a4015-48b5-4771-9147-7dc2c589185b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labresult_result</value>
      <webElementGuid>700f2ed8-c92b-4163-a265-0b89a0bbe84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control eplocker medevalbuttons labresult_field</value>
      <webElementGuid>554da7b7-6fa0-42f7-99e9-81df2c3c640d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please Select --NegativePositiveUndeterminedCancelled</value>
      <webElementGuid>83d35b78-4ee1-41c3-955b-996b14426f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labresult_result&quot;)</value>
      <webElementGuid>e6325e1b-5541-448a-bef4-4c553f9d536b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='labresult_result']</value>
      <webElementGuid>03281e08-e23d-485b-a78b-e059ec67ed8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='labresult_section_panelbody']/form/div[2]/div/div/select</value>
      <webElementGuid>a4efc7fd-ffcb-4edf-b8a0-fc30bd49ef26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overall Result:'])[1]/following::select[1]</value>
      <webElementGuid>c80db6ac-1eaf-40b7-84dc-23163465332e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Test:'])[1]/following::select[1]</value>
      <webElementGuid>6469954c-bbc8-4137-9e35-ed5a3b3977ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Result:'])[1]/preceding::select[1]</value>
      <webElementGuid>e67c9901-723a-423a-9ef1-6f355bc9e869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[2]/preceding::select[1]</value>
      <webElementGuid>7db567c6-cf6e-4051-b190-72c00a0c6b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/select</value>
      <webElementGuid>34767855-671a-47f3-81c9-80253a1f4951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'labresult_result' and @id = 'labresult_result' and (text() = '-- Please Select --NegativePositiveUndeterminedCancelled' or . = '-- Please Select --NegativePositiveUndeterminedCancelled')]</value>
      <webElementGuid>b26b69a9-1858-4aa8-ad22-8b21ea129c7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
