<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_11202024_1</name>
   <tag></tag>
   <elementGuidId>d5461a16-0d24-426e-851d-5eb01a660264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labresultmanual_tbl > tbody > tr > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='labresultmanual_tbl']/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;11/20/2024&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d6515868-4d5d-4bb3-b237-9d35e5513ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11/20/2024</value>
      <webElementGuid>52cc92ef-ed78-42d5-85c9-6d91d04f5e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labresultmanual_tbl&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>ac01a850-80a8-457c-984c-e41def6a585b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='labresultmanual_tbl']/tbody/tr/td[3]</value>
      <webElementGuid>9fb5d20c-24e3-4278-8246-b0bfa0584b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COVID-19 PCR'])[2]/following::td[2]</value>
      <webElementGuid>b789c00b-fd35-4cf7-99eb-c70bc0ae47d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[5]/following::td[3]</value>
      <webElementGuid>7af8f544-b592-401a-94e4-679506afbe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positive'])[2]/preceding::td[1]</value>
      <webElementGuid>7006e944-ff07-4d03-b6a3-f27967b45b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test on 11/20/2024'])[1]/preceding::td[2]</value>
      <webElementGuid>938fdd6b-5a82-4699-a50a-14e5a8ff4411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/table/tbody/tr/td[3]</value>
      <webElementGuid>c3175a12-6a08-420c-94f1-846d20b15df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '11/20/2024' or . = '11/20/2024')]</value>
      <webElementGuid>91e384c7-9d06-4740-9268-941fa85ded62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
