<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Positive</name>
   <tag></tag>
   <elementGuidId>d6924230-d429-4cf4-a395-eef3e0815aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labresultmanual_tbl > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='labresultmanual_tbl']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Positive&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f720e1d6-9043-41b7-bba9-86eff4b7ccf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Positive</value>
      <webElementGuid>195b0f26-85be-4f75-91e6-400bbfb7af69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labresultmanual_tbl&quot;)/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>6ca472ce-ebaa-46c4-a26f-68f47dcbad06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='labresultmanual_tbl']/tbody/tr/td[4]</value>
      <webElementGuid>645729ac-f1f8-4493-8091-3070f290b70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COVID-19 PCR'])[2]/following::td[3]</value>
      <webElementGuid>91000c85-fa43-4253-943e-688f5c1679a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[5]/following::td[4]</value>
      <webElementGuid>d865bce0-ec27-4107-a2ce-34307513c6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test on 11/20/2024'])[1]/preceding::td[1]</value>
      <webElementGuid>3d920aec-df96-4542-a8c2-f5b31ee881f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Signed'])[1]/preceding::td[2]</value>
      <webElementGuid>3b685a8f-df63-483f-9390-3c6f261b9f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/table/tbody/tr/td[4]</value>
      <webElementGuid>3771d939-6725-403f-a8a3-8102f5e5d46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Positive' or . = 'Positive')]</value>
      <webElementGuid>3ffd0b69-f006-4ff0-a6a6-a7224c7b1966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
