<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Note_labresult_notes</name>
   <tag></tag>
   <elementGuidId>48256669-6f57-4779-b6c5-d916d5711973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labresult_notes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='labresult_notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Note:&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4a5928a2-b633-4a4f-bcd6-826589455f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>labresult_notes</value>
      <webElementGuid>d74324b7-8851-4469-9330-2871a1e18652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9de50edf-115c-4f12-9946-2ae3e7dc8b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5815aee7-3c9b-4a81-8aef-d2633f10cfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labresult_notes</value>
      <webElementGuid>d7f95c5a-811d-4683-8ceb-799a9adec2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control eplocker medevalbuttons labresult_field</value>
      <webElementGuid>7915689e-abd8-429f-ba02-374c340a8e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labresult_notes&quot;)</value>
      <webElementGuid>2efb9ad6-bb9f-4cfa-aa34-b7bead50f489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='labresult_notes']</value>
      <webElementGuid>b1a07129-8363-4518-a098-e18f39e1f6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='labresult_section_panelbody']/form/div[3]/div/div/textarea</value>
      <webElementGuid>8f043e47-b487-4fcf-aca8-91144f5749dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/textarea</value>
      <webElementGuid>96f7008a-ad93-48c5-9850-32400001fbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'labresult_notes' and @id = 'labresult_notes']</value>
      <webElementGuid>9a270bbd-75fe-46bf-8614-1ca09201a76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
