<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign and Lock_dss</name>
   <tag></tag>
   <elementGuidId>46a81d75-252e-423c-9d5a-ad8d11bb6676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign and Lock&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf49e590-4f76-46cf-a5f4-7f244b81d8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>590e05a4-9524-4508-b15b-fc11d3be052f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>f5c51053-39e9-495d-992f-2778fafdabf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>f175a9aa-48ca-434f-80da-55cdcb87ad3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bdd86785-4145-4ca6-a135-78bf33cbf4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkcosign locker</value>
      <webElementGuid>1cac10bb-8507-42ab-b6b2-d902eb9cf557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dss&quot;)</value>
      <webElementGuid>912f82e8-4af8-443e-891e-5d19a37f95f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dss']</value>
      <webElementGuid>af0f28dc-4d5e-42d4-8de6-5cd2f84d22db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainDssSection']/div/label/input</value>
      <webElementGuid>d0863b0b-e5f4-4e0a-bb20-9ad464449310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/label/input</value>
      <webElementGuid>16c761d3-c183-4612-ad0f-7a538df88065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'dss' and @id = 'dss']</value>
      <webElementGuid>9fc51996-1ff9-4bd8-af68-9fc48cc739a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
