<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_lineamount_1</name>
   <tag></tag>
   <elementGuidId>7ea3776c-99b2-498c-a727-8d60b378039b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.is-focused > #p_lineamount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='p_lineamount'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2 Type: Apply For: Amount:&quot;i] >> #p_lineamount</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7df999d8-063f-4688-bce9-dd71db21e44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>812903bc-9695-4e30-9cf3-7ad2f70191f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lineamount[]</value>
      <webElementGuid>0e373229-f236-4177-96da-fa9488504f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p_lineamount</value>
      <webElementGuid>974d4090-8b58-4c27-9de0-d1f7adc6528f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lineamount formValidation</value>
      <webElementGuid>506913a9-6e16-474f-8b05-1e886c04a388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>519ebb97-abad-4006-acb9-f37e3a643567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addr1&quot;)/td[4]/div[@class=&quot;form-group is-focused&quot;]/input[@id=&quot;p_lineamount&quot;]</value>
      <webElementGuid>65cf86b8-22de-447e-9eaf-b3c57efd231c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='p_lineamount'])[2]</value>
      <webElementGuid>24071c5a-7f6a-4ab3-b318-fb3b199a5537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='addr1']/td[4]/div/input</value>
      <webElementGuid>9108b728-3823-4558-b478-d1779a7fb97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/input</value>
      <webElementGuid>25a9e772-fffc-4f8c-adc0-caa79203cd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'lineamount[]' and @id = 'p_lineamount']</value>
      <webElementGuid>60ff82bb-759c-4fe9-b9e9-1b84fd80c8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
