<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Sign with TopazReset_jSignature</name>
   <tag></tag>
   <elementGuidId>7f8033d8-1dea-436a-9a2d-cd331a69bdca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.jSignature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signature1']/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>e2efc86f-490d-452f-9480-1fe3ea8d3010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jSignature</value>
      <webElementGuid>de3f267c-c050-4945-a3cf-6d7b2a72ec29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>8ec5f62c-7201-41db-ab4f-37723f8f784e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>762e23ba-5a92-490b-af27-cb225404cbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signature1&quot;)/canvas[@class=&quot;jSignature&quot;]</value>
      <webElementGuid>6392c1d8-2436-4d23-ba2b-b74c1d9d8181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signature1']/canvas</value>
      <webElementGuid>aedb25bb-173d-4af2-bb62-e407046ad516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>325e6f13-11a5-46d1-81bc-de83d68526c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
