<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Condition Treated_primarydx</name>
   <tag></tag>
   <elementGuidId>0d732cfc-9176-46ba-99e9-c06029af8650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#primarydx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='primarydx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Condition Treated:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf440abc-5af4-4e6d-9535-dbd255eb9aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aada3d71-5cb3-4c1f-8dee-fcf03189cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primarydx</value>
      <webElementGuid>1f253830-0462-4da0-bf1e-46e32d184cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primarydx</value>
      <webElementGuid>8b8f2e4b-21b5-423f-a1b5-5c375a56051d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control autoupdate</value>
      <webElementGuid>d765e641-0868-45fc-802b-04c25670dda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primarydx&quot;)</value>
      <webElementGuid>d16cab87-1828-4d46-9365-74e440b0b5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='primarydx']</value>
      <webElementGuid>0060865a-c195-4467-9f20-6fa3c0b52fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div/div/div/input</value>
      <webElementGuid>11e4053d-e496-4e1c-b7b1-f850e54de40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>5bbc1454-f91c-41fa-9b10-f5bb8342cad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'primarydx' and @id = 'primarydx']</value>
      <webElementGuid>7dafd00c-aab6-48ca-b468-48ab3967a591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
