<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entered in Error_iseie</name>
   <tag></tag>
   <elementGuidId>b14f99b9-7c8d-46d4-a7d6-f9eae6d3e2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iseie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iseie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entered in Error&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9ae422f-150b-428e-83f4-3b973b113441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e505b55-4cb8-4ddd-a2bf-94c4198a5742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iseie</value>
      <webElementGuid>77724059-b34c-4d7e-9228-c97564b57d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>showEieSection</value>
      <webElementGuid>96b8c056-2294-4d4b-98a5-4213c06b886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iseie&quot;)</value>
      <webElementGuid>ddbe8126-cc4c-44dd-b062-c39ef87bc7ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iseie']</value>
      <webElementGuid>8ca67182-ceb8-45a1-a961-f872445c5a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmconsentctx']/div/div/b/div[2]/div/div/div/label/input</value>
      <webElementGuid>0407fc11-8b06-4ffb-8311-40fc9cc10e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label/input</value>
      <webElementGuid>156c1649-bde1-406e-bd60-f4d9953f716f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'iseie']</value>
      <webElementGuid>d7735221-47b8-4a14-a8d0-695400042b8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
