<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1629</name>
   <tag></tag>
   <elementGuidId>b0c66d3e-85de-4b4c-9bde-f69c4af0e434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inquiryprofileblock']/div[3]/div[2]/div/div/div/div/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.label.label-primary.mediumLabel.rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Last Episode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f3e71903-1484-4e59-8d0f-b4ddc32a3973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label label-primary mediumLabel rounded</value>
      <webElementGuid>22a6825a-6643-4ac6-9d7f-2e60bc294bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last Episode</value>
      <webElementGuid>72479722-bd4f-479f-9728-bd5186fd1c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1629</value>
      <webElementGuid>2199a239-123a-46cc-944c-ff7b0a47f51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inquiryprofileblock&quot;)/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 inq_episodes&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-md-1 col-sm-2 col-xs-2 inq_episodes_rounded&quot;]/label[@class=&quot;label label-primary mediumLabel rounded&quot;]</value>
      <webElementGuid>df46fc9a-f563-42ef-9512-b0bebf47eaf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inquiryprofileblock']/div[3]/div[2]/div/div/div/div/div[3]/label</value>
      <webElementGuid>2ff9452c-658b-4be6-ad4e-cbe944f98759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::label[1]</value>
      <webElementGuid>6ba4888c-47a1-4839-9104-526c3ff7e93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Episode: 08/28/2024'])[1]/following::label[2]</value>
      <webElementGuid>0dca5c26-6426-4b8a-bc44-54a8163d8115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Log'])[1]/preceding::label[3]</value>
      <webElementGuid>d7a944a4-1e30-467d-b1e2-c90c387f7d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inquiry Facesheet'])[1]/preceding::label[3]</value>
      <webElementGuid>01d56902-a343-434a-811f-c3dc34d89a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1629']/parent::*</value>
      <webElementGuid>a0a5e3e9-0106-4838-b046-6a52e3a79fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/label</value>
      <webElementGuid>1c4c8adf-8cea-4dc9-84c3-3adb17f1801b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Last Episode' and (text() = '1629' or . = '1629')]</value>
      <webElementGuid>72c8fc5f-9b0e-40cb-a5a2-82814cfe506e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
