<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8e38520d-fba2-4559-89c5-a8c94f598d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sigdefault']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-8.col-sm-8.col-xs-8 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sigdefault >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>55942209-1754-49ff-9c81-b91f145993ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMjY5IiBoZWlnaHQ9IjM2Ij48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDEgMyBjIDAuMjYgMC4xNyA5Ljc5IDcuMDIgMTUgMTAgYyA0LjE0IDIuMzYgOC40OCA0LjU1IDEzIDYgYyAxMi4wOSAzLjg3IDI0LjUgOC4yNSAzNyAxMCBjIDI1LjE4IDMuNTMgNTAuNjkgNC4zOSA3NyA2IGMgNy4xNSAwLjQ0IDEzLjc0IDAuMiAyMSAwIGMgMTcuNjMgLTAuNDkgMzQuNCAtMC4yMyA1MSAtMiBjIDguMDUgLTAuODYgMTcuMDYgLTIuNzUgMjQgLTYgYyA3Ljg2IC0zLjY4IDE1Ljk3IC0xMC41MyAyMyAtMTYgYyAxLjYxIC0xLjI1IDIuOTUgLTMuMjYgNCAtNSBsIDIgLTUiLz48L3N2Zz4=</value>
      <webElementGuid>da01dc4c-1746-41ba-934f-6f4fa07c628e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>f1dc3dd9-4ec3-454a-95e5-64797429bc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sigdefault&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-sm-8 col-xs-8&quot;]/img[1]</value>
      <webElementGuid>8938e8a2-d2fc-4cf7-9e6b-e3dd1dd9eac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sigdefault']/div/div/img</value>
      <webElementGuid>69c5477c-5018-47c5-bf1f-58c28e905968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMjY5IiBoZWlnaHQ9IjM2Ij48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDEgMyBjIDAuMjYgMC4xNyA5Ljc5IDcuMDIgMTUgMTAgYyA0LjE0IDIuMzYgOC40OCA0LjU1IDEzIDYgYyAxMi4wOSAzLjg3IDI0LjUgOC4yNSAzNyAxMCBjIDI1LjE4IDMuNTMgNTAuNjkgNC4zOSA3NyA2IGMgNy4xNSAwLjQ0IDEzLjc0IDAuMiAyMSAwIGMgMTcuNjMgLTAuNDkgMzQuNCAtMC4yMyA1MSAtMiBjIDguMDUgLTAuODYgMTcuMDYgLTIuNzUgMjQgLTYgYyA3Ljg2IC0zLjY4IDE1Ljk3IC0xMC41MyAyMyAtMTYgYyAxLjYxIC0xLjI1IDIuOTUgLTMuMjYgNCAtNSBsIDIgLTUiLz48L3N2Zz4=')]</value>
      <webElementGuid>3055cb0c-5ce0-401f-9cc5-0cea135bcb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/img</value>
      <webElementGuid>9eebc710-4b97-4929-ae89-a45ab4f4fe50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMjY5IiBoZWlnaHQ9IjM2Ij48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDEgMyBjIDAuMjYgMC4xNyA5Ljc5IDcuMDIgMTUgMTAgYyA0LjE0IDIuMzYgOC40OCA0LjU1IDEzIDYgYyAxMi4wOSAzLjg3IDI0LjUgOC4yNSAzNyAxMCBjIDI1LjE4IDMuNTMgNTAuNjkgNC4zOSA3NyA2IGMgNy4xNSAwLjQ0IDEzLjc0IDAuMiAyMSAwIGMgMTcuNjMgLTAuNDkgMzQuNCAtMC4yMyA1MSAtMiBjIDguMDUgLTAuODYgMTcuMDYgLTIuNzUgMjQgLTYgYyA3Ljg2IC0zLjY4IDE1Ljk3IC0xMC41MyAyMyAtMTYgYyAxLjYxIC0xLjI1IDIuOTUgLTMuMjYgNCAtNSBsIDIgLTUiLz48L3N2Zz4=']</value>
      <webElementGuid>2c596d8a-56f8-442a-a5fb-a84c522e2416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
