<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>28c5ebef-3516-4fc8-9d5d-ea361e225500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formEstimate']/div/div/div[11]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-10.col-sm-10.col-xs-10 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>29419d7d-7f08-4b35-a36e-2e42feeb01ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMzQzIiBoZWlnaHQ9IjQ5Ij48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDEgMyBjIDAuMjUgMC4yMSA5IDguNjIgMTQgMTIgYyA2LjE4IDQuMTggMTMuMDcgNy45MiAyMCAxMSBjIDguMDcgMy41OSAxNi4zOSA2LjQ1IDI1IDkgYyA5LjY2IDIuODYgMTkuMDIgNC44OCAyOSA3IGMgNi4xIDEuMyAxMS44MiAyLjMzIDE4IDMgYyAxMi41NyAxLjM3IDI0LjM1IDIuNjYgMzcgMyBjIDI1LjkxIDAuNjkgNTAuMTggMC44NiA3NiAwIGMgMTUuMDEgLTAuNSAyOS4zOCAtMS44MyA0NCAtNCBjIDEwLjE5IC0xLjUyIDIwLjE3IC00LjA1IDMwIC03IGMgNi44NyAtMi4wNiAxMy41NSAtNS4wMSAyMCAtOCBjIDIuODMgLTEuMzEgNS41NCAtMy4wOSA4IC01IGMgMy41MSAtMi43MyA2LjgxIC01LjgxIDEwIC05IGMgMi4xOSAtMi4xOSA0LjI0IC00LjUzIDYgLTcgbCA0IC03Ii8+PC9zdmc+</value>
      <webElementGuid>6feaef5c-ef68-4a41-b320-4ff98ebca43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>2004a8dd-7271-483c-935d-ca358b750923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEstimate&quot;)/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-sm-10 col-xs-10&quot;]/img[1]</value>
      <webElementGuid>43cef9ab-5121-48fc-be22-9bb54601b0c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEstimate']/div/div/div[11]/div/img</value>
      <webElementGuid>4bc01a79-2d3a-43cc-ab0a-a3dd4ef84098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMzQzIiBoZWlnaHQ9IjQ5Ij48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDEgMyBjIDAuMjUgMC4yMSA5IDguNjIgMTQgMTIgYyA2LjE4IDQuMTggMTMuMDcgNy45MiAyMCAxMSBjIDguMDcgMy41OSAxNi4zOSA2LjQ1IDI1IDkgYyA5LjY2IDIuODYgMTkuMDIgNC44OCAyOSA3IGMgNi4xIDEuMyAxMS44MiAyLjMzIDE4IDMgYyAxMi41NyAxLjM3IDI0LjM1IDIuNjYgMzcgMyBjIDI1LjkxIDAuNjkgNTAuMTggMC44NiA3NiAwIGMgMTUuMDEgLTAuNSAyOS4zOCAtMS44MyA0NCAtNCBjIDEwLjE5IC0xLjUyIDIwLjE3IC00LjA1IDMwIC03IGMgNi44NyAtMi4wNiAxMy41NSAtNS4wMSAyMCAtOCBjIDIuODMgLTEuMzEgNS41NCAtMy4wOSA4IC01IGMgMy41MSAtMi43MyA2LjgxIC01LjgxIDEwIC05IGMgMi4xOSAtMi4xOSA0LjI0IC00LjUzIDYgLTcgbCA0IC03Ii8+PC9zdmc+')]</value>
      <webElementGuid>5c25bb21-cdb6-4d63-872c-479dffa8eb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/img</value>
      <webElementGuid>cd321c5a-ab84-4d4c-84e2-806f41579caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMzQzIiBoZWlnaHQ9IjQ5Ij48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDEgMyBjIDAuMjUgMC4yMSA5IDguNjIgMTQgMTIgYyA2LjE4IDQuMTggMTMuMDcgNy45MiAyMCAxMSBjIDguMDcgMy41OSAxNi4zOSA2LjQ1IDI1IDkgYyA5LjY2IDIuODYgMTkuMDIgNC44OCAyOSA3IGMgNi4xIDEuMyAxMS44MiAyLjMzIDE4IDMgYyAxMi41NyAxLjM3IDI0LjM1IDIuNjYgMzcgMyBjIDI1LjkxIDAuNjkgNTAuMTggMC44NiA3NiAwIGMgMTUuMDEgLTAuNSAyOS4zOCAtMS44MyA0NCAtNCBjIDEwLjE5IC0xLjUyIDIwLjE3IC00LjA1IDMwIC03IGMgNi44NyAtMi4wNiAxMy41NSAtNS4wMSAyMCAtOCBjIDIuODMgLTEuMzEgNS41NCAtMy4wOSA4IC01IGMgMy41MSAtMi43MyA2LjgxIC01LjgxIDEwIC05IGMgMi4xOSAtMi4xOSA0LjI0IC00LjUzIDYgLTcgbCA0IC03Ii8+PC9zdmc+']</value>
      <webElementGuid>dba32eb3-75a1-4a0b-aa18-22218a5c2cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
