<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Out-of-Network Family Out of Pocket M_97c17b</name>
   <tag></tag>
   <elementGuidId>3629ae62-69f2-4146-9d0c-2f3e53a6ebb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oon_ytd_fam_oop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oon_ytd_fam_oop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Out-of-Network: Family Out of Pocket Met YTD:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f49755ff-fdd0-41a2-affa-85089f02cd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5586b7a8-b9e0-4226-b8c4-54a66613a7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oon_ytd_fam_oop</value>
      <webElementGuid>c2bcf2d3-1178-42c4-99db-f604a4723570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oon_ytd_fam_oop</value>
      <webElementGuid>69136250-5f3b-40a5-ac15-a17f88cec3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>50ec762f-4970-41e7-b756-09f05c6bb55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oon_ytd_fam_oop&quot;)</value>
      <webElementGuid>cfe17184-3bdc-4d76-bc5d-0e89ab01c0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oon_ytd_fam_oop']</value>
      <webElementGuid>5c07c1e8-f936-49fe-b34a-6d921b1b75bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEstimate']/div/div/div[6]/div[4]/div/input</value>
      <webElementGuid>e9c0b34f-09f3-4470-8de8-b6aabb80776c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/div/input</value>
      <webElementGuid>4bc438e5-7554-40db-bf86-95ba497ca275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'oon_ytd_fam_oop' and @id = 'oon_ytd_fam_oop']</value>
      <webElementGuid>59670d4b-ce3c-46d7-b5e6-d0f12bdc0b9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
