<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_In Network Family Out of Pocket Met Y_c7dc58</name>
   <tag></tag>
   <elementGuidId>2f9afab3-4dd8-41f3-af19-0d562063384a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ytd_fam_oop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ytd_fam_oop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;In Network: Family Out of Pocket Met YTD:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bfc1a39-5bc8-4e9e-ab5e-8d8487dba270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5d272e0-5e26-439c-bb1f-515d67198461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ytd_fam_oop</value>
      <webElementGuid>36668e42-d099-4dbd-93a9-6ccbb5cc4292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ytd_fam_oop</value>
      <webElementGuid>13427551-0b1f-4488-9f89-f4df19c6334d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>6b9c50d9-4da2-4854-bee4-88234ccfca95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ytd_fam_oop&quot;)</value>
      <webElementGuid>bb6fb53a-bf58-48ef-a97e-9e3e031b35f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ytd_fam_oop']</value>
      <webElementGuid>3d6fcff6-e2fb-4f47-bac1-0e1cdcf23804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEstimate']/div/div/div[5]/div[4]/div/input</value>
      <webElementGuid>532e176f-345b-4799-a08c-0d9c1d000284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div/input</value>
      <webElementGuid>41eb41b8-7b95-42d5-81b5-07a0179691d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ytd_fam_oop' and @id = 'ytd_fam_oop']</value>
      <webElementGuid>407085bd-8e02-4ef2-a1e5-6a9db0f08afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
