<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Out-of-Network Individual Maximum Out_23c1e0</name>
   <tag></tag>
   <elementGuidId>00665603-3ccf-4a3b-bca4-2fddd6b9f782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oon_calendar_year_ind_oop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oon_calendar_year_ind_oop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Out-of-Network: Individual Maximum Out of Pocket::&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73858790-d11e-4e93-89c7-97503d231b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03351034-4e41-47dd-b52f-b36d2c090fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oon_calendar_year_ind_oop</value>
      <webElementGuid>79b585f2-e729-4ff4-9bb0-49ce1bfe98dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oon_calendar_year_ind_oop</value>
      <webElementGuid>284088bd-5278-4433-b09e-e4028942a5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>bbbbc66f-b89a-43fc-b6d6-18d2bb04a5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oon_calendar_year_ind_oop&quot;)</value>
      <webElementGuid>bfb04aa9-aeb5-408d-a94b-a4c7809b457c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oon_calendar_year_ind_oop']</value>
      <webElementGuid>33ebec54-1dd4-4bfb-90c2-9701d6a6b367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEstimate']/div/div/div[6]/div/div/input</value>
      <webElementGuid>4012c293-fe0a-4f9e-a606-6b769b41171c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>389f9f2c-3d83-4afd-8452-9446aebc5997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'oon_calendar_year_ind_oop' and @id = 'oon_calendar_year_ind_oop']</value>
      <webElementGuid>e582f485-b14b-4339-b9a5-aaea799dd6dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
