<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Not SelectedYesNo</name>
   <tag></tag>
   <elementGuidId>f660972c-3bc7-4af2-b3e3-2de2c13819d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='oondedincyn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oondedincyn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Deductible included in OOP?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c1599f6d-b1c3-454a-88cf-e47e95922698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oondedincyn</value>
      <webElementGuid>7c8ffe23-fcbd-4bec-a713-db9fc91e9223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oondedincyn</value>
      <webElementGuid>1a38adb3-0433-452b-9e9e-154b91400113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>981c607c-aad9-4532-847e-9cf5b7f57902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not SelectedYesNo</value>
      <webElementGuid>2c96c958-be4c-45db-bd13-6ba685a633f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oondedincyn&quot;)</value>
      <webElementGuid>b5a60c2f-e94e-4017-9260-598d2d741101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='oondedincyn']</value>
      <webElementGuid>38f40f61-4c03-4aad-a89f-c533b7c1ccfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEstimate']/div/div/div[4]/div[5]/div/select</value>
      <webElementGuid>3b2e4743-c1bb-4e12-ad0d-bca32b8e5e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible included in OOP?'])[1]/following::select[1]</value>
      <webElementGuid>7432f71d-a8d2-423e-bd28-5ce8f78ae687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Life Met:'])[1]/following::select[1]</value>
      <webElementGuid>23a60b32-b9c4-48b2-bbc2-b7ea05fcb051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Network: Individual Maximum Out of Pocket:'])[1]/preceding::select[1]</value>
      <webElementGuid>0a5e9a3f-f55b-435a-9ea4-859130d65359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Network: Indiviual Out of Pocket Met YTD:'])[1]/preceding::select[1]</value>
      <webElementGuid>da143830-8123-4d32-9b13-984e41fc09c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>1a795305-ae8b-42da-a14d-daf8decc334a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'oondedincyn' and @id = 'oondedincyn' and (text() = 'Not SelectedYesNo' or . = 'Not SelectedYesNo')]</value>
      <webElementGuid>ec923ccd-d96c-4a1a-950c-3bdd103f83fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
