<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please select --5 Panel Drug Scre_5f4c46</name>
   <tag></tag>
   <elementGuidId>ba23f876-1d94-4808-9be6-55f0e88345b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='s_service_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#s_service_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Service:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>39628b14-5d8d-4453-b14d-a012fea15408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s_service_id</value>
      <webElementGuid>da9a322c-b9ab-4cbb-bd32-7d328bdb8762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s_service_id</value>
      <webElementGuid>d12fd2ba-e66d-4fa1-826d-df97d1cb74d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capfield</value>
      <webElementGuid>ea7833c3-30d5-4346-85c6-1095e637a1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fb5f9ffb-fc5f-4fd0-a23f-0bb3fc5bc813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please select --5 Panel Drug ScreenAssessmentDetoxificationIndividual SessionInpatient ResidentialIntroduction Of Cardiac Pacemaker System Via VeinIOPNebulizer TherapyOutpatientTake Back</value>
      <webElementGuid>aacdfe41-3af0-471d-8e8f-e6a8464612fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s_service_id&quot;)</value>
      <webElementGuid>2ec58dd4-c263-4e7a-97ad-31471c80b434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='s_service_id']</value>
      <webElementGuid>bbed4b08-2950-4449-9764-5dd992b53827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmService']/div/div/div/div/select</value>
      <webElementGuid>d0301d3e-cb3a-43e6-a8a3-fcb408250d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service:'])[1]/following::select[1]</value>
      <webElementGuid>16e4b3f8-2326-42ed-a51b-13645d7c9292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimate Service'])[1]/following::select[1]</value>
      <webElementGuid>7031c327-0670-405c-9a32-5a238a413899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Type:'])[1]/preceding::select[1]</value>
      <webElementGuid>54e79590-81bc-4741-9fcb-c8bf03a2875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# of Units/Sessions:'])[1]/preceding::select[2]</value>
      <webElementGuid>4ebd12b7-4521-404a-ad89-11e4a4302875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/select</value>
      <webElementGuid>402012f3-5902-4b44-b87a-81eb27142cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 's_service_id' and @id = 's_service_id' and (text() = '-- Please select --5 Panel Drug ScreenAssessmentDetoxificationIndividual SessionInpatient ResidentialIntroduction Of Cardiac Pacemaker System Via VeinIOPNebulizer TherapyOutpatientTake Back' or . = '-- Please select --5 Panel Drug ScreenAssessmentDetoxificationIndividual SessionInpatient ResidentialIntroduction Of Cardiac Pacemaker System Via VeinIOPNebulizer TherapyOutpatientTake Back')]</value>
      <webElementGuid>8e4d1c83-c5f0-4420-8f0b-ef7dc486d1e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
