<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1.10</name>
   <tag></tag>
   <elementGuidId>5e3aa10b-387d-4964-bf79-a45ed5f523d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='admitfee_footer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#admitfee_footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#admitfee_footer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9236c783-c5e1-4483-8a91-d69c5816a9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admitfee_footer</value>
      <webElementGuid>644e2ad4-b3ca-41e7-91b1-dd789e6a52cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1.10</value>
      <webElementGuid>bbbe6f98-3907-4a24-9f3b-fa67369563cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admitfee_footer&quot;)</value>
      <webElementGuid>deae163e-f12f-4691-a4f4-fc35c778f8c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='admitfee_footer']</value>
      <webElementGuid>9aafc2ba-4f3b-4724-8f94-f98740741161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl_estimate']/tfoot/tr/td[2]/span</value>
      <webElementGuid>9c95e163-6915-4335-8198-4409053df5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission Fee'])[1]/following::span[1]</value>
      <webElementGuid>6b003e6f-874c-4bf1-8482-1dc7f7197a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[4]/following::span[1]</value>
      <webElementGuid>1adbc762-34df-41aa-a82d-33e1a25afdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[5]/preceding::span[1]</value>
      <webElementGuid>4802cfde-a2e7-4570-957e-7abe8d4e207f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[6]/preceding::span[1]</value>
      <webElementGuid>8624789d-c6b0-4433-920b-724eaa1ac137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1.10']/parent::*</value>
      <webElementGuid>d7930bdf-f909-4f0b-9d87-e00581b9b85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/td[2]/span</value>
      <webElementGuid>d128f884-56d1-4ff1-be0e-b2c7e96aaa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'admitfee_footer' and (text() = '$1.10' or . = '$1.10')]</value>
      <webElementGuid>115410d3-18ba-4e4b-b558-669f30006931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
