<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grievance Procedure (CFF)</name>
   <tag></tag>
   <elementGuidId>c4613ab4-cb27-4655-8fd4-9bc3ba12ae8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#consentselect > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='consentselect']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Grievance Procedure (CFF)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54924f45-49c5-4fc7-b9e4-2eb002d46898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consentx/create/1674/np_cff_grievance</value>
      <webElementGuid>dadbb7c7-bc92-4b50-81a3-b7b6e25f4248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grievance Procedure (CFF)</value>
      <webElementGuid>8ee0ed7a-ac34-4035-83b0-67ef2039036e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consentselect&quot;)/li[1]/a[1]</value>
      <webElementGuid>43500a79-6905-4b07-b306-76d602d34161</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='consentselect']/li/a</value>
      <webElementGuid>d52742d7-5888-4b5d-8024-a6b01f33f5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grievance Procedure (CFF)')]</value>
      <webElementGuid>a2394a22-cd4c-471f-b1fc-6ed4d2a5eb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show State Specific Consents:'])[1]/following::a[1]</value>
      <webElementGuid>8be245df-b046-4647-80a2-203379af993a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[62]/preceding::a[1]</value>
      <webElementGuid>76f37559-749a-4d9f-aa4a-4b4216ada3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grievance Procedure (CFF)']/parent::*</value>
      <webElementGuid>dbb66f87-97bf-4937-a6f1-cc6cdc7a80ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/consentx/create/1674/np_cff_grievance')]</value>
      <webElementGuid>129f3735-c45d-4689-93c1-3debd00233bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li/a</value>
      <webElementGuid>ea025712-24ac-464d-8127-a3edcfc80344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/consentx/create/1674/np_cff_grievance' and (text() = 'Grievance Procedure (CFF)' or . = 'Grievance Procedure (CFF)')]</value>
      <webElementGuid>0b97f0dc-4278-4638-a305-86e9b382f4bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
