<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate</name>
   <tag></tag>
   <elementGuidId>c3f084f6-43c1-40a2-8020-274e5ca13bd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsaveag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnsaveag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#btnsaveag</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0f66c7b-b672-4e41-8584-1e0f702dcd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0dd13f6f-17d3-4479-afb5-1e7b9fe12e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-raised nodoubleclick</value>
      <webElementGuid>5011770f-7eca-4595-b84d-7e5dde560997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnsaveag</value>
      <webElementGuid>4bfe3139-3430-485c-a38a-bf4a71cdb9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsaveag</value>
      <webElementGuid>43d2db62-c6b8-4f08-9ffe-d90b179a382d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>54c7411a-8380-45e7-9d33-17f0655de202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate
                </value>
      <webElementGuid>d7301fe5-d9e2-489e-a538-e7629ba46fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsaveag&quot;)</value>
      <webElementGuid>a5a691fa-700e-4396-a2a6-ff3f612b94d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnsaveag']</value>
      <webElementGuid>95508b77-1057-4a50-a21e-6818b9447a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdlag']/div/div/div[2]/button</value>
      <webElementGuid>fb02f421-3d85-4663-9801-7a5edc2b8150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You will be redirected to the earliest unsigned consent.'])[1]/following::button[1]</value>
      <webElementGuid>5bae6bb1-77ea-43dd-b41c-9f1b9a0d499b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorization to Charge'])[1]/following::button[1]</value>
      <webElementGuid>8228c536-5be8-4f1e-931e-dee802a6b3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate']/parent::*</value>
      <webElementGuid>13b16d5e-c20c-4765-8d02-84473a3b9b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/button</value>
      <webElementGuid>34b815f7-1bd4-48d4-b90d-829fe367c449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'btnsaveag' and @id = 'btnsaveag' and (text() = 'Generate
                ' or . = 'Generate
                ')]</value>
      <webElementGuid>845bec62-3fbc-4bc2-9c38-67bc5e748ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
