<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consent for Telemedicine_admission_consents</name>
   <tag></tag>
   <elementGuidId>c4dfc856-fdf3-4f39-8ae0-6972f8e89e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ac11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ac11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr >> internal:has-text=&quot;Consent for Treatment&quot;i >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>692673e1-208c-423d-b9b6-e97781595178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8bffb65b-d290-423e-888d-b6ebc0edf7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>admission_consents[]</value>
      <webElementGuid>460cc98a-35ef-49c9-9ffc-41118f77ea87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac11</value>
      <webElementGuid>fda4509e-1d79-4bd0-a13a-e72d98f48709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>25fd5653-51c0-4157-8d35-f50372bc8fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkconsent checkme</value>
      <webElementGuid>f100a7aa-c9fa-4dc0-b976-8a118fd753eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ac11&quot;)</value>
      <webElementGuid>7a4613ea-1158-4bd1-8178-0358d6427fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ac11']</value>
      <webElementGuid>2dfddd5a-a616-4b88-a687-e61fc7bb3590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdlag']/div/div/div/div[2]/div/table/tbody/tr[8]/td/div/label/input</value>
      <webElementGuid>48e712d7-f8b7-4eeb-abf0-9c3df164ce08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/label/input</value>
      <webElementGuid>c735ba3c-fecf-4808-981c-e9b5348a016c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'admission_consents[]' and @id = 'ac11']</value>
      <webElementGuid>a5816a52-815c-46ca-a0ee-333822dd7863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
