<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CheckACHCredit Card</name>
   <tag></tag>
   <elementGuidId>5b4085b1-d48b-4ce2-88e9-bb40e9905998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p_method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='p_method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#p_method</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>297c03c5-b4ad-4137-aeaa-e5ac9797e785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>method</value>
      <webElementGuid>2a8aae55-c239-417d-b953-75cbcd7b596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p_method</value>
      <webElementGuid>719dc8c3-3fd4-43a0-93bb-32ac7899157e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control capfield</value>
      <webElementGuid>720a2ae7-e62c-47cc-ad96-4dd32caa385c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check/ACHCredit Card</value>
      <webElementGuid>b441a693-87e5-46a9-9c9c-d7f2c2c64a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_method&quot;)</value>
      <webElementGuid>a8c27042-466b-4434-8650-09efb5a62418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='p_method']</value>
      <webElementGuid>798361f5-68c8-44c6-a11f-4b89c11c6eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method:'])[1]/following::select[1]</value>
      <webElementGuid>441ffb6f-7e9a-435b-a0bd-def0c283d376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payor:'])[1]/following::select[1]</value>
      <webElementGuid>45d053dc-6ece-4a8d-aa66-602603d11e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name on Card:'])[1]/preceding::select[1]</value>
      <webElementGuid>60c6caf2-bff2-40bf-81b9-822159dda013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Zip:'])[1]/preceding::select[1]</value>
      <webElementGuid>e3ff342a-7e93-4f8a-b295-70d966877196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>b75bcc17-b283-4733-9f42-b5a014173faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'method' and @id = 'p_method' and (text() = 'Check/ACHCredit Card' or . = 'Check/ACHCredit Card')]</value>
      <webElementGuid>d8b64d83-e5fe-4f47-b073-e2452ecd360a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
