<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_add</name>
   <tag></tag>
   <elementGuidId>58bd931f-0d61-424e-94d1-1719a7e0cbcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idcplanbuttons']/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-fab.dxlocker.eplocker.idcplanbuttons > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idcplanbuttons >> internal:role=link[name=&quot;add&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a5d47810-5a15-49fe-995f-42688b24b16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>d98bcb01-ac73-4326-b6c8-5ed0dc3554d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>53acebff-51e8-448e-a9e0-ddd3818fb4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcplanbuttons&quot;)/div[@class=&quot;btn-group-sm ro-remove&quot;]/a[@class=&quot;btn btn-primary btn-fab dxlocker eplocker idcplanbuttons&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>8ead6aad-b516-4fbb-90bf-8e17a846a091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcplanbuttons']/div/a/i</value>
      <webElementGuid>57096843-ed2d-43b2-a577-839c152ccd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Episode Override'])[9]/following::i[1]</value>
      <webElementGuid>93042013-23cc-4a5e-a573-164f6e5aee00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation of New Records is not Allowed in a previous Episode.'])[13]/following::i[2]</value>
      <webElementGuid>d59219a1-de12-4456-8d36-d6aff4ba29bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initial Discharge Plan for A Client A Automation'])[1]/preceding::i[1]</value>
      <webElementGuid>0a356870-4eab-45d5-97d4-7d1c42ac394e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[18]/preceding::i[1]</value>
      <webElementGuid>71a53446-053d-40df-bfa8-f01cf4ee0b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[4]/div[2]/div[2]/div/div/div/a/i</value>
      <webElementGuid>d3211469-2897-4014-9ea5-d91a37b6244d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>35fec6b5-057b-482d-9025-23a9dab4cbb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
