<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_12032024</name>
   <tag></tag>
   <elementGuidId>1d74f12d-5e57-4e45-9650-e77ae46b8de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblinitdcplans']/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tblinitdcplans > tbody > tr > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;12/03/2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d945dbec-355b-4c24-b11a-ea4acb13d2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12/03/2024</value>
      <webElementGuid>34978740-2dff-4b41-9a3d-3012256be188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblinitdcplans&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>976a7550-773e-4ceb-8deb-26bdb0bf63ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblinitdcplans']/tbody/tr/td</value>
      <webElementGuid>a2f38ac5-a76c-461f-93f4-aa9aa96fc292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[11]/following::td[1]</value>
      <webElementGuid>4b30e92a-3ff3-4df3-886a-aec8b462ca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[2]/following::td[1]</value>
      <webElementGuid>2d3ae037-448f-4097-af14-758bd84b2865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detoxification'])[3]/preceding::td[1]</value>
      <webElementGuid>2f8ca6cd-b375-43d3-abc2-a66d86d7c014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed'])[9]/preceding::td[2]</value>
      <webElementGuid>9094e9c8-8409-4777-a163-17cb0a800a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12/03/2024']/parent::*</value>
      <webElementGuid>bd8bc1d6-669a-457b-9cde-c0115f8288f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/table/tbody/tr/td</value>
      <webElementGuid>341afff1-dbb9-4031-a54f-0b48010a0231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '12/03/2024' or . = '12/03/2024')]</value>
      <webElementGuid>a183a771-02d6-4414-aaa8-99ffbf61c19f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
