<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Detoxification</name>
   <tag></tag>
   <elementGuidId>23f5b8e6-5a7f-4283-ba90-66b5959ed10a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblinitdcplans']/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tblinitdcplans > tbody > tr > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Detoxification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b8c46d32-398d-4673-b5a6-0bd3978be2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detoxification</value>
      <webElementGuid>1dd6fef5-f525-49de-8cc8-52ed7d711243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblinitdcplans&quot;)/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>c5bb43c8-f154-4302-8571-92c3634984ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblinitdcplans']/tbody/tr/td[2]</value>
      <webElementGuid>fe7ff0d5-8ad8-4aa8-9816-096570731c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[11]/following::td[2]</value>
      <webElementGuid>234cbeaf-860e-4757-93dc-ffac4688eee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[2]/following::td[2]</value>
      <webElementGuid>f9816474-6c27-4353-acda-0542a5d33892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed'])[9]/preceding::td[1]</value>
      <webElementGuid>8db7c7ec-d309-4d24-a619-7ec9dbaa0342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation of New Records is not Allowed without an Active Episode of Care.'])[14]/preceding::td[3]</value>
      <webElementGuid>bb701d01-bcae-4875-9b10-0af9a57329f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>a311c5c9-4dab-4eb2-b77a-6fff6386a50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Detoxification' or . = 'Detoxification')]</value>
      <webElementGuid>424e70aa-ce27-4213-9425-4a36a1de06ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
