<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Signed</name>
   <tag></tag>
   <elementGuidId>de025f43-bd89-4b91-95a2-63d505fc7e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblinitdcplans']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tblinitdcplans > tbody > tr > td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Signed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>152616e9-7840-4f11-87cf-17b59bb6bd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signed</value>
      <webElementGuid>aee7a251-fbb8-4f35-9c76-eed103f731a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblinitdcplans&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>4232c1ee-1b0f-4128-95d8-6bbec7e6f9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblinitdcplans']/tbody/tr/td[3]</value>
      <webElementGuid>409ec514-b473-42d7-b76b-c510402c9ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detoxification'])[3]/following::td[1]</value>
      <webElementGuid>72e75a22-8ec4-47fd-bfb0-0a3cf6a8ee9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[11]/following::td[3]</value>
      <webElementGuid>729eeda8-83ef-499f-bdda-d09ff5d6fd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation of New Records is not Allowed without an Active Episode of Care.'])[14]/preceding::td[2]</value>
      <webElementGuid>9bd4c146-6b7c-4049-97d4-cd0171de6804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation of New Records is not Allowed in a previous Episode.'])[14]/preceding::td[2]</value>
      <webElementGuid>e6002b79-147e-4c7a-9ad4-1180d45da3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>605a61e9-695e-4c8a-b56a-c43b5973705b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Signed' or . = 'Signed')]</value>
      <webElementGuid>3faf7a76-c73e-481e-a806-2a3597f74975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
