<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lab Tests</name>
   <tag></tag>
   <elementGuidId>850d8379-e0e9-44c2-9006-a4caf8df191a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='heading_test']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Lab Tests&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0966d593-e154-482a-a616-ca0d927ff5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>6093be23-8a18-49dd-8c4b-fbd34aa511bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c3a31bf-6dd7-411f-adb7-cdd2eb80fd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>0f36bb06-41f1-42a3-b475-d361dc723e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>e5c344ec-65b3-476f-90ea-51dae2b37a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#ltinfo</value>
      <webElementGuid>af59ee9a-cbaf-4b1a-b1a2-ed79ca2cb1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>abf417da-a509-4de0-97df-d3d15564dee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ltinfo</value>
      <webElementGuid>3e821428-d7bb-43f8-a180-481eeab623f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Lab Tests 
          </value>
      <webElementGuid>1ef4c22e-05ef-4368-8600-ed3f55048b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading_test&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>f7928d1e-702f-4948-82a3-19c51251990c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading_test']/h4/a</value>
      <webElementGuid>08011e63-6b00-4185-be16-29d718069ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Electronic?'])[1]/following::a[1]</value>
      <webElementGuid>d35f4a79-43d3-404c-965e-d91d1e922632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes to be Added to Order'])[1]/following::a[1]</value>
      <webElementGuid>e1778bb6-8e70-4794-92fd-8ae1dd711738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Tests:'])[1]/preceding::a[1]</value>
      <webElementGuid>c190c8a7-7b9b-4f7a-9469-3d7d25fbdf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#ltinfo')]</value>
      <webElementGuid>0935d9cf-bf15-4f87-b6f1-cfef62396759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4/a</value>
      <webElementGuid>7019af99-519b-4b02-94f6-d045fe2faf7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#ltinfo' and (text() = '
              Lab Tests 
          ' or . = '
              Lab Tests 
          ')]</value>
      <webElementGuid>bcd8812e-8dd3-4f5d-8fb6-b7198e0da72f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
