<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox_1</name>
   <tag></tag>
   <elementGuidId>70d8a032-de83-4307-b75c-371f4b7c9705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(17) > label > input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='12,0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Benzodiazepines EIA [300 ng/mL] [BE02S]&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c10d270-f796-4ca9-89f8-643069968ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3b96e081-8d2a-4c4a-9c44-29a53a843641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12,0</value>
      <webElementGuid>1025a134-eb45-4770-bbc6-7fd0949860f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>selectItemavailable_test_select</value>
      <webElementGuid>1b5ebce9-3d51-4698-afdf-7afa1205658a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testselect&quot;)/div[@class=&quot;ms-parent form-control&quot;]/div[@class=&quot;ms-drop bottom&quot;]/ul[1]/li[17]/label[1]/input[1]</value>
      <webElementGuid>84e5d565-0995-4723-9bec-d81566cde3fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='12,0']</value>
      <webElementGuid>fc20f6d1-fc6b-45c0-862e-96e18f97eb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testselect']/div/div/ul/li[17]/label/input</value>
      <webElementGuid>7080658e-20de-4c81-9b2c-ecb214f50b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[17]/label/input</value>
      <webElementGuid>2bf8f3da-c4a2-4fb9-aa3f-996dd240678e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>bf1eb063-c2cb-4876-b248-8f6332db9da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
