<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Frozen                              _7e1fe1</name>
   <tag></tag>
   <elementGuidId>337529e4-263b-4bef-b5d1-9efacc34ebbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tempcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Temperature:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12717f27-d52d-4021-9991-29ca680fcf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempcode</value>
      <webElementGuid>bd012878-48d3-405c-800c-ba090ee21b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempcode</value>
      <webElementGuid>2528e12c-210a-4685-bf07-4d1b6c18c97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker form-control</value>
      <webElementGuid>15951b24-17ee-48e8-b2a2-52d8bbd4d330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Frozen
                                    Refrigerated
                                    Ambient
                                    Unspecified
                                  </value>
      <webElementGuid>77c1fef2-c427-43d1-a0b2-9a967d5e7f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempcode&quot;)</value>
      <webElementGuid>de728157-a6da-400e-81dc-0eee5ad86a00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tempcode']</value>
      <webElementGuid>dbd041df-021a-4fa6-b519-07f4247b318d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderinfo']/div/div[6]/div[2]/div/select</value>
      <webElementGuid>b6f6c1f6-89d7-443a-9841-a4240676a04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature:'])[1]/following::select[1]</value>
      <webElementGuid>29660f90-54f2-4f69-9355-bb22321c557d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specimen Container'])[1]/following::select[2]</value>
      <webElementGuid>fbbb698e-27da-4afd-8587-7a0178d2e676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specimen Type:'])[1]/preceding::select[1]</value>
      <webElementGuid>92bb5833-96e1-460f-8ca2-ca0362f8c2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>8fe8db4a-b1e8-44c7-be8c-f8573460fb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tempcode' and @id = 'tempcode' and (text() = '
                                    Frozen
                                    Refrigerated
                                    Ambient
                                    Unspecified
                                  ' or . = '
                                    Frozen
                                    Refrigerated
                                    Ambient
                                    Unspecified
                                  ')]</value>
      <webElementGuid>abee084f-ecae-4441-a478-d35a862ce0a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
