<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Entered in Error_check</name>
   <tag></tag>
   <elementGuidId>9f73ce9c-1d82-48e8-be7d-ff7c14a55d7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-4.col-md-4.col-sm-4.col-xs-4 > div.checkbox > label.control-label > span.checkbox-material > span.check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='eiestuff']/div/div/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#eiestuff span >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aa26c241-3e39-441a-a783-d5f466a20cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>e80f8ebb-8f9f-4d71-b012-b63c9adc825a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eiestuff&quot;)/div[@class=&quot;col-lg-4 col-md-4 col-sm-4 col-xs-4&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;control-label&quot;]/span[@class=&quot;checkbox-material&quot;]/span[@class=&quot;check&quot;]</value>
      <webElementGuid>aa836003-8bd5-48f3-b4fb-96931a55c909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eiestuff']/div/div/label/span/span</value>
      <webElementGuid>fedf3ce2-070a-4553-ae9a-43be66ade9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/label/span/span</value>
      <webElementGuid>019346bb-023c-416a-958e-b9b26f1223ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
