<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Rationale_rationale_text1</name>
   <tag></tag>
   <elementGuidId>0709c085-7881-447f-b106-66e64e18b582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rationale_text1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='rationale_text1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rationale:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>49d522c6-e401-4897-b344-0c88e008b530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rationale_text1</value>
      <webElementGuid>8960adfc-ae10-4e92-9d0a-f835263d6ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f59e044b-4030-495c-94fe-427ef06f25dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c737b780-bd22-4c37-b8d9-e031a0879027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rationale_text1</value>
      <webElementGuid>23c5a3d4-9435-47af-ba67-691bfaa1b191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker rationales form-control showme</value>
      <webElementGuid>ce4b971e-8e93-44eb-8177-140271a0985d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b10dda73-caaa-4788-9c9c-c58db7380329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hiddeninput</name>
      <type>Main</type>
      <value>rationale</value>
      <webElementGuid>56b01819-9a12-444c-8a85-f6958328d621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rationale_text1&quot;)</value>
      <webElementGuid>d9354b27-d4c9-4f91-b9f7-c2683105e92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='rationale_text1']</value>
      <webElementGuid>cebb97af-0c6d-4de2-b84c-fb4ac05bf92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderinfo']/div/div[7]/div/table/tbody/tr/td/div/textarea</value>
      <webElementGuid>ec90ee0a-dc4b-4445-a34b-e41f73c54896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/textarea</value>
      <webElementGuid>87b1eb2a-9bbe-4755-888d-2501a28ee975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'rationale_text1' and @id = 'rationale_text1']</value>
      <webElementGuid>383ee279-aa34-4fd8-982a-5845589b8c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
