<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Expand viewarrow_outward</name>
   <tag></tag>
   <elementGuidId>291671bd-d7e8-45da-ba89-998e5925d2f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='addProgressNoteModal']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.modal-show-full-screen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Expand view arrow_outward&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76657366-058f-4f36-9deb-6ec0a79320fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>08b2e577-d26f-486f-a7dd-659d5da2c2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-show-full-screen</value>
      <webElementGuid>84b22f33-10f5-4c71-b424-99287989cea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Expand viewarrow_outward</value>
      <webElementGuid>15db4f65-57a6-4a7a-91d1-92d5d0153800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addProgressNoteModal&quot;)/div[@class=&quot;ls-modal-window&quot;]/div[@class=&quot;ls-modal-window--content&quot;]/div[@class=&quot;ls-modal-window--header&quot;]/a[@class=&quot;modal-show-full-screen&quot;]</value>
      <webElementGuid>f0699cf7-78f0-49f0-83a9-5b51f65240c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addProgressNoteModal']/div/div/div/a</value>
      <webElementGuid>8b51aebc-964d-4f7d-978e-aabf5b66830c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New progress note'])[1]/following::a[1]</value>
      <webElementGuid>ab90ac9c-5017-4f32-9d6a-4f838b59d8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Added'])[2]/following::a[1]</value>
      <webElementGuid>caaf2780-fd1b-4afa-8c27-b4c73dc4631a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Expand view']/parent::*</value>
      <webElementGuid>cddd8c96-947d-4cda-a84d-d97aea3d4207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[71]</value>
      <webElementGuid>5be07f6a-b87d-435e-987a-6e8da9f23345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/a</value>
      <webElementGuid>d5e90977-6c0e-4fc5-8e48-782aa0389dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Expand viewarrow_outward' or . = 'Expand viewarrow_outward')]</value>
      <webElementGuid>e296189a-c3c7-4af6-983b-06fe53e61982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
