<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Female</name>
   <tag></tag>
   <elementGuidId>f0b0f91b-34ca-4718-80f2-47a13b365c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Female']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4) > span.tablesaw-cell-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Female&quot;i] >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c2791c14-64ce-4406-a614-0518c237f2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tablesaw-cell-content</value>
      <webElementGuid>70eac199-e55f-4514-a104-5f11204bc571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>aa5bf3a4-8655-49ba-af29-22a5a014fb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablesaw-1988&quot;)/tbody[1]/tr[1]/td[4]/span[@class=&quot;tablesaw-cell-content&quot;]</value>
      <webElementGuid>541cdee2-b004-4b66-bcc2-a735a09ab883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Female' or . = 'Female')]</value>
      <webElementGuid>f799ba66-c1c4-466d-a5bf-ff862e4afe80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
