<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Associated Factors What other symptom_d4156a</name>
   <tag></tag>
   <elementGuidId>d6520773-602c-4783-9837-7897849b2483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#painrating5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='painrating5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;5&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acd5cbe9-3bf5-4017-b779-24bdc5d66346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1bd34f67-111b-4732-bc63-68fbf1bb4983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>painrating</value>
      <webElementGuid>11403c9f-a4f0-47c8-9ba6-f0ca1f2c43a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>painrating5</value>
      <webElementGuid>834849e6-ec64-416e-b7a7-4d6156c20521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8f74c7a8-9c47-4e84-b2f8-c5e7a37d205f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker</value>
      <webElementGuid>d09833a5-c7dd-4b2c-89a7-549125135cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;painrating5&quot;)</value>
      <webElementGuid>fcd0747f-c187-4868-8adc-9230d462828e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='painrating5']</value>
      <webElementGuid>9d21f9ce-3219-4880-9485-ec2a60e20b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='painynsection']/div[10]/div[5]/label/input</value>
      <webElementGuid>9573fadc-d29b-4e55-b920-f8847be3f120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/input</value>
      <webElementGuid>b588b2d0-83d2-4bf0-aced-efe0e7c5fcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'painrating' and @id = 'painrating5']</value>
      <webElementGuid>7cfa1c35-c9e5-488a-ae45-e9031ea21720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
