<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--not-selected--YesNo</name>
   <tag></tag>
   <elementGuidId>a748c36b-bf1b-4124-86ef-92804be178d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#painyn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='painyn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Are you experiencing any pain?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1ac991e-49db-42b1-b1c8-4b2af88af25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>painyn</value>
      <webElementGuid>61b21345-88f2-492e-bcf9-93205bc5b822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>painyn</value>
      <webElementGuid>3b29abc5-3b5c-4319-8406-ed2b6f498864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control yn</value>
      <webElementGuid>c52228ac-2e54-4720-ab18-f18aad3fc57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--not-selected--YesNo</value>
      <webElementGuid>bf1b094c-8fd5-4070-af28-9fd1183fe79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;painyn&quot;)</value>
      <webElementGuid>ee644a90-291b-47a7-b5a0-9401b8cee577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='painyn']</value>
      <webElementGuid>f9eae104-5357-4f72-8b31-b05440ed3aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createpainrating']/div[2]/div/form/div/div/div[2]/div/div/select</value>
      <webElementGuid>11e6e4ff-6829-49c5-8ec8-8a84afcfc972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you experiencing any pain?'])[1]/following::select[1]</value>
      <webElementGuid>c443832f-94df-4b14-88b2-76297408c85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time:'])[1]/following::select[1]</value>
      <webElementGuid>c5316243-0b8e-4057-a904-fe49c944cb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Character: Please describe your pain:'])[1]/preceding::select[1]</value>
      <webElementGuid>be979aa1-7ff4-4ab8-8aa4-7f8aa2a72393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Onset: When did your pain begin? How often do you experience it?'])[1]/preceding::select[1]</value>
      <webElementGuid>e2af64a8-09de-4075-acf6-3807cf66c243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>75096c10-9542-4b34-b9ce-cc07ae9b1fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'painyn' and @id = 'painyn' and (text() = '--not-selected--YesNo' or . = '--not-selected--YesNo')]</value>
      <webElementGuid>26e22c56-a171-41b0-866d-dfb2bfb6b665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
