<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Associated Factors What other symp_d4f16d</name>
   <tag></tag>
   <elementGuidId>e77ba420-9bcc-4198-ac31-080086d77436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtfactors</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtfactors']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Associated Factors: What other symptoms occur with it?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>feac64e4-7cb0-47b1-82aa-db418f141b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtfactors</value>
      <webElementGuid>7842defe-7b54-4771-a000-c5bf2bab8399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f9b7cac0-9fcc-4eb9-9739-9afb66db4f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>00accd6b-5f9d-4aa5-ba0a-0fa5f2e34a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfactors</value>
      <webElementGuid>c53d7d97-0ae9-46de-82e7-d84a5bc2e7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>46c1f331-ed37-4b63-b670-38982e3c8867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f15f519e-a4cc-424e-adf2-790bc15a6ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfactors&quot;)</value>
      <webElementGuid>6f7a2bf9-fc1d-4a64-9908-c6c6a3d77422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtfactors']</value>
      <webElementGuid>ba723acf-d6db-4291-9117-88a91702938a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='painynsection']/div[8]/div/div/textarea</value>
      <webElementGuid>f359092b-0357-4150-8a2c-68dbb70c9f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/textarea</value>
      <webElementGuid>05d1bff9-5bf7-48f9-83bd-d92112261e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtfactors' and @id = 'txtfactors']</value>
      <webElementGuid>758d5c52-9a71-474d-b118-f65e9ac8fdce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
