<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reason_eiereason</name>
   <tag></tag>
   <elementGuidId>8b12a828-2061-43d1-b060-3347ec77ed98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eiereason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eiereason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Reason for Error&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dcc7f13-1854-45b9-be7c-642a2a7c4721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99d95e34-b585-4124-923d-5826cbbefc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>66e4e437-f69a-4c62-bf04-87f725337874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eiereason</value>
      <webElementGuid>58293c64-b1ab-4920-bf54-1ba3145d0883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for Error</value>
      <webElementGuid>f7f6f2ad-bae3-4ad3-9fcd-22ab705420bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>902d60fa-c8d2-4385-94ac-f10b7e7d049b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>9078a378-f6e2-4989-8c41-320a0fd99257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;tablesaw-enhanced ls-light&quot;]/body[1]/div[@class=&quot;container-content ls-content-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[6]/div[@class=&quot;grid grid-cols-12 gap-8 print:hidden&quot;]/div[@class=&quot;col-span-5&quot;]/div[1]/div[@class=&quot;form-group is-empty is-focused&quot;]/input[@id=&quot;eiereason&quot;]</value>
      <webElementGuid>675ecd4c-02cd-4cc2-9ec8-1191b2dfade1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eiereason']</value>
      <webElementGuid>de7c9f3e-3918-47b9-9f24-66fc6789749a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/input</value>
      <webElementGuid>47f1a76e-1187-48d9-ac39-c914292c6f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'eiereason' and @placeholder = 'Reason for Error']</value>
      <webElementGuid>372fadc0-ec50-493e-aeb0-bf8c101c52f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
