<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entered in Error_iseie</name>
   <tag></tag>
   <elementGuidId>640d1190-b51f-480b-b7d3-6599b6c87ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iseie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iseie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entered in Error&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b133413-31af-425b-8960-c56f13629bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8fb67a4b-2384-43c1-bac2-589502f61042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iseie</value>
      <webElementGuid>de9b9a5d-c6a8-4078-9a86-fb87851a2f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>showEieSection</value>
      <webElementGuid>79cb2fd3-7910-44ce-85df-4a96a27eea50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iseie&quot;)</value>
      <webElementGuid>15d4b430-b1fa-46ef-a06a-5cb944874f87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iseie']</value>
      <webElementGuid>3678f38c-1b31-4470-8d07-799ee6538c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/label/input</value>
      <webElementGuid>29f7354f-3ba4-4a4a-a9ae-e53d9445afc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'iseie']</value>
      <webElementGuid>cb458606-fb0c-40c6-9493-f8ad691d4dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
