<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Initiated</name>
   <tag></tag>
   <elementGuidId>1ece3381-84d6-4c3a-87c4-40026882172f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labtab_initiated > h5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='labtab_initiated']/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot; Initiated&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>89a4f320-7d58-4444-97da-98718826caed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Initiated 
                                        </value>
      <webElementGuid>c69a70c6-f0b4-4f1d-9de4-ec07f4ddeeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labtab_initiated&quot;)/h5[1]</value>
      <webElementGuid>58aaf35d-1fa8-44a2-8153-6e6f8a3d03b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='labtab_initiated']/h5</value>
      <webElementGuid>1003fb67-ee09-4942-8558-82339d2343cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[28]/following::h5[1]</value>
      <webElementGuid>c3e2d7c6-1f32-48af-ab68-e5bcb6ccd22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/h5</value>
      <webElementGuid>1e690a82-949e-4212-8c50-ce148ec75d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '
                                             Initiated 
                                        ' or . = '
                                             Initiated 
                                        ')]</value>
      <webElementGuid>ac46ec8e-1900-4826-8f19-b0a8c7990db8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
