<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reason_eiereason</name>
   <tag></tag>
   <elementGuidId>0fdb31fd-6ad7-4771-8c40-dd6b29258dd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.is-empty.is-focused > #eiereason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='eiereason'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Reason for Error&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af9e6318-be3a-4550-a990-f90fcaffd9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6b1cbc5-0099-4179-8165-633b7b5072ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>59c51138-ca10-4dbe-9ac4-f24b9fa4f88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eiereason</value>
      <webElementGuid>da5ea128-77af-4e0a-b427-c4c752595286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for Error</value>
      <webElementGuid>bbabf077-b272-41e5-8505-54df2ef0d596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c05b6e94-00c7-4435-b607-3d44b57d685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>ccce4735-020f-401d-9ed6-0f4bd1cecbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dcsumform&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/div[4]/div[@class=&quot;grid grid-cols-12 gap-8 print:hidden&quot;]/div[@class=&quot;col-span-5&quot;]/div[1]/div[@class=&quot;form-group is-empty is-focused&quot;]/input[@id=&quot;eiereason&quot;]</value>
      <webElementGuid>22720569-82f7-4c7e-8859-c879b480a1d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='eiereason'])[2]</value>
      <webElementGuid>4a8726fa-8da5-427e-b896-f70e142e7ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcsumform']/div[10]/div/div/div/div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>8e7e61b9-9f9d-4fd4-a745-fb279a5c073c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>2e341808-34ca-4b96-b56c-e6ce8676bff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'eiereason' and @placeholder = 'Reason for Error']</value>
      <webElementGuid>da8a4c65-7d1c-4b4e-8a00-7cdf40b1f9c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
