<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multiple Programs_admprogram</name>
   <tag></tag>
   <elementGuidId>080dbcf8-4711-4ef9-9e7c-1ad0ab474f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admprogram</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='admprogram']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Multiple Programs:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ef6b955-9308-4840-99c1-fd18864bc40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2cfeae40-9791-4bbd-b0f8-40195f0f4e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>admprogram</value>
      <webElementGuid>80eb0adf-d8d5-409c-ac4d-f73d6cb6fbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admprogram</value>
      <webElementGuid>ac1adfa0-4c51-470a-b442-b8f77761931c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>b1e3b620-d37b-467c-baa7-b808eda23060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admprogram&quot;)</value>
      <webElementGuid>2c1e19a0-fb6d-4e6a-9415-1acc58a8b7a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='admprogram']</value>
      <webElementGuid>3c117aa1-adcc-4a51-9282-eed87cd6460b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcsumform']/div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>c751366c-41b1-4bac-abf8-292c88adecd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/input</value>
      <webElementGuid>c4abbeb9-7ecd-447d-a8f8-27027c18a97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'admprogram' and @id = 'admprogram']</value>
      <webElementGuid>08e1fccc-4594-44fe-8d3a-af7dfbb1c949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
