<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Funding Source_payorname</name>
   <tag></tag>
   <elementGuidId>228d9562-650c-4df5-8196-28c59d9e4e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payorname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payorname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Funding Source:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>219e417b-4ed0-4c14-af56-ec8834c32b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9acc0392-5581-4327-b73f-cd146c32dd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payorname</value>
      <webElementGuid>7a291db6-717a-4978-adb9-3b025b9f906f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Scholarship</value>
      <webElementGuid>e0b4235f-6aed-4b7b-8c1d-16135486cae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payorname</value>
      <webElementGuid>e14ec3fe-e869-41a7-8434-dcf7a236e47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>5d6108a7-6fcb-48a3-bfa1-1ad58aad2720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payorname&quot;)</value>
      <webElementGuid>3cd9fc4c-06dc-4bd4-ad85-ece0d10bb8ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payorname']</value>
      <webElementGuid>53232334-0499-4731-aea5-af62c8d197d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcsumform']/div[2]/div/div[8]/div[2]/div/input</value>
      <webElementGuid>1cf7edce-e48a-4983-9262-2f5d123690d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/input</value>
      <webElementGuid>de958b87-aeaa-45fd-b979-c39b2c71d4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payorname' and @id = 'payorname']</value>
      <webElementGuid>cbadccad-9da9-4cfd-9fd4-aa1d45c9fd22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
