<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Detoxification Admission 11282024</name>
   <tag></tag>
   <elementGuidId>a5e1c1a3-0290-4ce7-84ec-7f201f86c71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddprogram</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddprogram']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ddprogram</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>704d1810-f61f-4b0e-b15d-c5bb6c2f9fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddprogram</value>
      <webElementGuid>a879d774-d7ab-4a34-841d-747ccb7a075b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddprogram</value>
      <webElementGuid>ee401cfa-bd9e-4986-9a3d-fdbc29247b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker printworthy hidden-print</value>
      <webElementGuid>fe9e65c6-86d1-4185-961d-51dec8d418e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldname</name>
      <type>Main</type>
      <value>ddprogram</value>
      <webElementGuid>71e95263-05b3-4857-b37e-31b162bee654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablename</name>
      <type>Main</type>
      <value>dcsums</value>
      <webElementGuid>747d27d1-6722-4b54-9f8f-ab7e19292757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                          Detoxification Admission: 11/28/2024
                                    </value>
      <webElementGuid>2b831051-8205-4fab-9368-689a352ced8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddprogram&quot;)</value>
      <webElementGuid>aeb000d3-abad-4ed8-bf53-303ffab52bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddprogram']</value>
      <webElementGuid>d5125745-8e7b-488d-9bd8-8802eade8be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admprogramsection']/div/div/div/select</value>
      <webElementGuid>900b5ac0-0e7a-40c5-ad99-83941933c9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/following::select[1]</value>
      <webElementGuid>fbae825c-7ece-4606-8c53-160e55cb77a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[1]/following::select[1]</value>
      <webElementGuid>a9b5d02a-0023-4ea2-8dde-f6c4e2b094cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detoxification Admission: 11/28/2024'])[2]/preceding::select[1]</value>
      <webElementGuid>79e29e50-2e33-4cf0-ba16-c1157608c6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If the Discharge Summary covers multiple programs, enter the program names below (optional).'])[1]/preceding::select[1]</value>
      <webElementGuid>92657049-cf06-4deb-9ec8-03aea93926b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>c8bfadaf-0d1e-4daa-901f-1ea244c5b498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddprogram' and @id = 'ddprogram' and (text() = '
                                          Detoxification Admission: 11/28/2024
                                    ' or . = '
                                          Detoxification Admission: 11/28/2024
                                    ')]</value>
      <webElementGuid>464d2550-d236-4f66-a8da-22e3ad0850e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
