<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional Information_note</name>
   <tag></tag>
   <elementGuidId>4b4561b6-9067-419a-9d90-a71b50372d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Additional Information:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>498b2e76-f840-4480-a67a-72dadb7eee4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>6012deb9-359b-4121-8e4c-d26d3ab1613b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2b57ead4-743a-4e8d-b2c6-de27a58f73e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>56788daf-3f2d-4ca9-a8ef-f207fa14497b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>49cd9f8a-ad9b-4aa4-a195-5ffd2c2fc92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>816df491-53ef-44f7-96f3-b8ccf47529b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fa9bc5bd-ad9a-4873-9fd7-76868c0355f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note&quot;)</value>
      <webElementGuid>d4f8ab8b-7987-4b2d-833d-a61da392b370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='note']</value>
      <webElementGuid>ac1638db-4d83-49d6-9ddf-c24a47de8d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcsumform']/div[7]/div/div[5]/div/div/textarea</value>
      <webElementGuid>c7bac8fe-5cd8-4fbd-9b3b-e56a95b8bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[5]/div/div/textarea</value>
      <webElementGuid>8cebaa47-9572-444b-8cc7-22f9b335ec05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'note' and @id = 'note']</value>
      <webElementGuid>d43ce101-635d-470b-946a-2fc485dfcbc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
