<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Additional Recommendations_txtadditional</name>
   <tag></tag>
   <elementGuidId>d5df8c6f-86d6-42ae-b619-487e5efa61df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtadditional</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtadditional']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Additional Recommendations:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8820ac0f-5a87-4723-893b-63ea34e04986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtadditional</value>
      <webElementGuid>702b9969-afca-45fd-b9ef-8e090f6a1ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>693f4703-61ab-4cc0-8f69-2f0a9116e2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>69790c5b-e388-4d14-8bac-fb5b959c9948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtadditional</value>
      <webElementGuid>fa15b3cb-a875-4c02-81b2-164bb99d5730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>6d35883e-9af9-406e-a3cd-21b0b9b12282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fd0272b0-d298-43dd-b017-41f0c1bad0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtadditional&quot;)</value>
      <webElementGuid>ad382db5-6d0b-4d1c-b520-cd7841436826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtadditional']</value>
      <webElementGuid>6a5fead4-0b3b-4387-9543-060e30520434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcsumform']/div[6]/div/div[5]/div/div/textarea</value>
      <webElementGuid>72d9db47-46fd-4e0b-822e-1aa932910fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/textarea</value>
      <webElementGuid>57dc240e-f087-4c6e-8a7d-3f78893ea1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtadditional' and @id = 'txtadditional']</value>
      <webElementGuid>a762a1de-14bb-45a9-8dde-dc25efb9a840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
