<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Summary of Treatment_txsummary</name>
   <tag></tag>
   <elementGuidId>38f3ed55-08cb-494c-bb15-d2791de340c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txsummary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txsummary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Summary of Treatment:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f77d1469-88d6-445d-9be3-815d66c5d4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txsummary</value>
      <webElementGuid>87986252-e086-48c6-b8e1-a55200ca880d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9d8b56ed-4eab-4ce4-9ba5-3d95765aa9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0611d01e-111c-4d5c-81c4-76c6842e859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txsummary</value>
      <webElementGuid>55c52df6-d4be-4e6a-b549-c7cadb257906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control locker</value>
      <webElementGuid>acea068d-6eae-4616-ad35-c51d440adac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columns</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e696f8b4-e2f7-4528-9a80-1ab2af827475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txsummary&quot;)</value>
      <webElementGuid>adf830d9-e573-48d8-ba4d-94c0abd9b405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txsummary']</value>
      <webElementGuid>db5ace5d-5e21-4bb1-bc85-b66033b6d0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dcsumform']/div[7]/div/div/div/div/textarea</value>
      <webElementGuid>fd903cbd-0997-4f3f-a340-243925f53e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/textarea</value>
      <webElementGuid>368be80c-8e3c-4c84-8f82-15a07e15a0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txsummary' and @id = 'txsummary']</value>
      <webElementGuid>498c368d-01cb-4494-b148-3c555caf9f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
