<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Collect Payment_search_action</name>
   <tag></tag>
   <elementGuidId>c5991237-fb2a-45d8-935d-a8c24d2c61bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search_action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#search_action</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8931c92c-9fbe-4804-89ae-70fd86bc08b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-raised</value>
      <webElementGuid>d9a2a061-6f8f-482e-bc87-b4734f587775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_action</value>
      <webElementGuid>311169ff-c792-4c42-9964-bad72aed63b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_action</value>
      <webElementGuid>ba2e7b01-5b92-4924-9576-277d739358f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>68789cec-2414-4aa8-b504-8d7dcd7d3c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92aa2a7b-3dbb-46ee-a2bf-9c736ad79cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_action&quot;)</value>
      <webElementGuid>f3b5d20c-8759-4770-a721-bf7622c7f3e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search_action']</value>
      <webElementGuid>03265691-e73d-4dce-9093-7dca185dd7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formCollectPayment']/div/div[3]/button</value>
      <webElementGuid>0ce03173-ebf5-482e-857c-f8309ff8cffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect Payment'])[2]/following::button[1]</value>
      <webElementGuid>aafb058d-ebab-47cf-9dc4-8fd79f66b57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::button[2]</value>
      <webElementGuid>92ac68e5-2cc0-433e-b60b-44ed9e2ce2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='**Only Inquiries that have a Payor Setup will appear in the search**'])[1]/preceding::button[1]</value>
      <webElementGuid>ee1ac00b-fbd9-4f36-ba63-9e93cd97d3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Name:'])[1]/preceding::button[1]</value>
      <webElementGuid>b6428433-8762-40b5-b038-2eea73f38e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/button</value>
      <webElementGuid>d97e2e62-7ee6-43b2-8f3a-cef41b76ffdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'search_action' and @id = 'search_action' and @type = 'button']</value>
      <webElementGuid>7248562f-65ad-44ab-83c6-d42da08f96d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
