<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Automation Additional Information_fa fa-pencil</name>
   <tag></tag>
   <elementGuidId>1cd6e0ae-f950-4df2-8431-ad931deda524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='weightbody']/tr/td[8]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8) > a.btn.btn-primary.btn-raised.btn-sm.hidden-print > i.fa.fa-pencil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f69a1d3a-1ce3-4fa1-be7f-e153957d9ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil</value>
      <webElementGuid>1f05d503-a811-4e88-9575-1bba65bbce66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weightbody&quot;)/tr[@class=&quot;odd&quot;]/td[8]/a[@class=&quot;btn btn-primary btn-raised btn-sm hidden-print&quot;]/i[@class=&quot;fa fa-pencil&quot;]</value>
      <webElementGuid>5b5e8783-77d7-4db7-8d7a-6b2a31cae10a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='weightbody']/tr/td[8]/a/i</value>
      <webElementGuid>f474a682-7e70-470d-9a95-5bfcd060bc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Additional Information'])[1]/following::i[1]</value>
      <webElementGuid>36acd9fb-4a96-4ff6-b50b-12142eb0985f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Information'])[1]/following::i[1]</value>
      <webElementGuid>c228cc1a-1910-4dca-9b08-262ed56c2ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::i[1]</value>
      <webElementGuid>73a17c34-cbf4-4211-9cfa-7101681ff29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a/i</value>
      <webElementGuid>3f4705d7-85fd-406a-87d7-d902e7913822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
