<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_186</name>
   <tag></tag>
   <elementGuidId>d11996fd-d2a9-451f-a313-e1d5158d94d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.rowVisibleHeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='weightbody']/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;186&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0ac96a9b-a7d0-4e13-81a0-acce8f41c553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rowVisibleHeight</value>
      <webElementGuid>5734cb9b-2b95-4e1d-8aeb-caa64e22d8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                                186
                                            </value>
      <webElementGuid>eb6ea4e0-8f23-4e83-8d0e-16a6e11deb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weightbody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;rowVisibleHeight&quot;]</value>
      <webElementGuid>b864bfdc-c0ef-49de-bca2-26b06966da69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='weightbody']/tr/td[4]</value>
      <webElementGuid>a93d925b-2303-46b7-be0c-07f133135289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Information'])[1]/following::td[4]</value>
      <webElementGuid>433bccd8-9600-4298-987e-44450dc7dcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IBW %'])[1]/following::td[4]</value>
      <webElementGuid>94c20589-2a45-437c-99f2-14b173deca9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Additional Information'])[1]/preceding::td[3]</value>
      <webElementGuid>bdbe0e11-bf4d-4d6e-b500-835f841f8bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::td[5]</value>
      <webElementGuid>30e78fc0-b843-444a-8398-45518b51db18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='186']/parent::*</value>
      <webElementGuid>ae92e57e-04a1-441e-9fc1-2c212bc35b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>c70ce410-47ea-491f-aa74-45f81d2b9fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '                                                186
                                            ' or . = '                                                186
                                            ')]</value>
      <webElementGuid>ddef3587-738e-46dc-9cf6-ad7a9f5ffc06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
