<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_11212024</name>
   <tag></tag>
   <elementGuidId>d65cfcf1-b1d2-4d32-ada3-f3d534b7a745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tblclientdx > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblclientdx']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;11/21/2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ffac6854-0fff-40ad-aa33-55d845e5f1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11/21/2024</value>
      <webElementGuid>6bcaef95-eb96-4fbf-b8e7-477831a81074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblclientdx&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>d2e71cf2-667f-42ce-b793-8348106cccae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblclientdx']/tbody/tr/td</value>
      <webElementGuid>6108ce63-7f49-419c-8c28-da0fa5c8172f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinician'])[2]/following::td[1]</value>
      <webElementGuid>4a8fdd3d-a489-4b31-bce1-7383887d28f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[2]/following::td[1]</value>
      <webElementGuid>5980305b-887f-4458-9002-75c2e90f5a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[2]/preceding::td[2]</value>
      <webElementGuid>0bd509c1-1395-41a1-b5de-f6e36ad82c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chemical Dependency'])[3]/preceding::td[4]</value>
      <webElementGuid>0ec6e0fd-2c04-4e8d-8e18-883ca06c7d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td</value>
      <webElementGuid>074b7b7f-c024-4016-88a3-d139afb7df37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '11/21/2024' or . = '11/21/2024')]</value>
      <webElementGuid>58c99d4b-305d-4e7f-a5bf-ef42d0372293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
