<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_summarize                Facesheet</name>
   <tag></tag>
   <elementGuidId>55452830-b88c-4041-a27f-54299b9e6f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='clientprofileblock']/div/div[2]/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;summarize Facesheet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3a675d5-6435-4989-b5ca-46b9195150db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ls-btn capitalize btn-white</value>
      <webElementGuid>3e23242a-85a1-45fa-9ca6-f5bd12bb9cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://site17.lsapp.cloud/client/facesheet/1557</value>
      <webElementGuid>c5ca8724-26ca-456b-a8b7-f63f8a2c7c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>View Client Facesheet</value>
      <webElementGuid>a9c09205-e0b7-4a09-86c0-18e38f48c9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover196383</value>
      <webElementGuid>ab36eb2b-ff70-4bab-8ce9-d4706fcf4a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                summarize
                Facesheet
            </value>
      <webElementGuid>f38035f9-cc90-4dab-b56a-b0bdf1d9fbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientprofileblock&quot;)/div[@class=&quot;client-profile--content&quot;]/div[@class=&quot;ls-profile-info-container&quot;]/div[@class=&quot;profile-info&quot;]/div[@class=&quot;profile-buttons&quot;]/a[@class=&quot;ls-btn capitalize btn-white&quot;]</value>
      <webElementGuid>c60fdca7-65df-41f1-8a67-23845335fec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clientprofileblock']/div/div[2]/div/div[2]/a[3]</value>
      <webElementGuid>19a6df19-92f7-4b2b-a479-2d81e75b0e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='news'])[1]/following::a[1]</value>
      <webElementGuid>9ac93866-cda1-4f5a-b644-9dcb0e1352f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projected Transfer Date:'])[1]/preceding::a[2]</value>
      <webElementGuid>2d5a332b-e36c-46a4-9e13-063bf5ad0b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Facesheet']/parent::*</value>
      <webElementGuid>27ef5825-441f-4906-a456-fe85d90bdc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://site17.lsapp.cloud/client/facesheet/1557')])[2]</value>
      <webElementGuid>173e8acb-69ed-45fb-8a0b-5503a617fb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]</value>
      <webElementGuid>f966843c-b161-48e1-94e9-a84cb34e4b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://site17.lsapp.cloud/client/facesheet/1557' and (text() = '
                summarize
                Facesheet
            ' or . = '
                summarize
                Facesheet
            ')]</value>
      <webElementGuid>fdefac3a-3c8d-470f-a5fc-ffc61dc3b62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
