<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Future Automation Test 1.2 Automaticall_19fd63</name>
   <tag></tag>
   <elementGuidId>b8d9c521-a298-478c-bd41-4a2be47ca081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='timeline-block-list-container']/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Future Automation Test 1.2 Automatically Enroll Clients in Selected Location/Pro&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac93bfc4-5922-433c-9b46-3cc34a110369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeline-customer-note</value>
      <webElementGuid>e5ee34e2-6170-4a8a-9bf8-9792915f610d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Future Automation Test 1.2 Automatically Enroll Clients in Selected Location/Program(s)</value>
      <webElementGuid>3b430537-7f42-4fe6-9feb-69faaae38825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeline-block-list-container&quot;)/div[@class=&quot;timeline-body&quot;]/div[@class=&quot;timeline-customer-container&quot;]/div[@class=&quot;timeline-customer-info&quot;]/div[@class=&quot;timeline-customer-note&quot;]</value>
      <webElementGuid>166886c2-ec25-48b3-9d59-5a9fee858a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='timeline-block-list-container']/div[2]/div[2]/div/div</value>
      <webElementGuid>3b613442-46b2-47e6-81b5-dff357fa2d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Friday'])[2]/following::div[3]</value>
      <webElementGuid>6ec0fd2a-468d-425c-b5b7-22ef4789da8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_right_alt'])[3]/following::div[7]</value>
      <webElementGuid>b801befb-e4f7-46f1-95e8-b27a7e2825e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Session'])[1]/preceding::div[1]</value>
      <webElementGuid>270315d6-bac3-42b2-a822-3ed602ef9ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[10]/preceding::div[3]</value>
      <webElementGuid>0d39a5da-83f6-4aff-bd61-ea44e79169e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Future Automation Test 1.2 Automatically Enroll Clients in Selected Location/Program(s)']/parent::*</value>
      <webElementGuid>bf79b2ba-5a22-4d3b-b165-4f913845ca21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>cd189846-0d68-4289-a457-a7b094ce44a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Future Automation Test 1.2 Automatically Enroll Clients in Selected Location/Program(s)' or . = 'Future Automation Test 1.2 Automatically Enroll Clients in Selected Location/Program(s)')]</value>
      <webElementGuid>66b3f5d6-59e3-4ec8-8e83-c3bc0fa0d473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Wednesday'])[2]/following::div[3]</value>
      <webElementGuid>99d77e5a-2717-4459-81e1-613b075e00b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
