<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_B2automation.com</name>
   <tag></tag>
   <elementGuidId>118597d7-a833-4a2e-a085-b338b68da7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='clientprofileblock']/div/div[2]/div[2]/div/div[9]/div[4]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.profile-details-column--value.break-all</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#clientprofileblock >> internal:text=&quot;B2@automation.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad84a319-af10-49a9-9c04-4a2806045079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-details-column--value break-all</value>
      <webElementGuid>eaaa4461-73ca-4afa-a49e-d138dd689a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B2@automation.com</value>
      <webElementGuid>f83b6760-9f07-441a-8c81-8abdf6ae491c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientprofileblock&quot;)/div[@class=&quot;client-profile--content&quot;]/div[@class=&quot;ls-profile-info-container&quot;]/div[@class=&quot;profile-details&quot;]/div[@class=&quot;profile-details-container&quot;]/div[@class=&quot;profile-details-column&quot;]/div[@class=&quot;profile-details-row&quot;]/div[@class=&quot;profile-details-column--value break-all&quot;]</value>
      <webElementGuid>d0f94cc5-6cb9-4a10-9b38-a11b6b746798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clientprofileblock']/div/div[2]/div[2]/div/div[9]/div[4]/div[2]</value>
      <webElementGuid>d4d90b93-7425-4aa7-8a7d-918cb8777536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[4]/following::div[1]</value>
      <webElementGuid>4fe9957b-f524-4a12-b076-669ee028f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(833) 957-2888'])[6]/following::div[3]</value>
      <webElementGuid>34cb4a17-1bcc-4d36-a4ca-56b2efead424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timeline'])[1]/preceding::div[1]</value>
      <webElementGuid>15650a24-5617-42f6-a001-05d7e6352428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Items'])[2]/preceding::div[2]</value>
      <webElementGuid>4d3a7bdd-0b13-44f2-a52d-7fa65200f099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[4]/div[2]</value>
      <webElementGuid>fe9b1153-b5b1-4e3a-9cbb-078258101638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'B2@automation.com' or . = 'B2@automation.com')]</value>
      <webElementGuid>88c8188c-a64a-4a5d-a73d-df108acbbff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
