<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Future Automation Test with B Automatio_ed8b34</name>
   <tag></tag>
   <elementGuidId>202eb617-1c83-4903-9a7c-57ddb734683a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='timeline-block-list-container']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.timeline-customer-note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Future Automation Test with B Automation, B Client MR# 24-11007: 5 Panel Drug Sc&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18f144a0-02fd-413e-93f9-f92793e824fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeline-customer-note</value>
      <webElementGuid>0ab3707c-2917-4d6f-bb29-6b6777863dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Future Automation Test with B Automation, B Client MR# 24-11007: 5 Panel Drug Screen</value>
      <webElementGuid>20cdc37d-db7a-49e7-bae8-13932d82e1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeline-block-list-container&quot;)/div[@class=&quot;timeline-body&quot;]/div[@class=&quot;timeline-customer-container&quot;]/div[@class=&quot;timeline-customer-info&quot;]/div[@class=&quot;timeline-customer-note&quot;]</value>
      <webElementGuid>8713a972-3a12-4903-8afa-e3a6d4ba6303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='timeline-block-list-container']/div/div[2]/div/div</value>
      <webElementGuid>47dc3f9b-8edc-4dfc-bd0c-2a7d63c79530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Wednesday'])[1]/following::div[3]</value>
      <webElementGuid>fe5940d6-1c98-4661-ba63-f689106a2048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_outward'])[1]/following::div[12]</value>
      <webElementGuid>1372c6e9-4941-4518-9592-59a4578fc8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='appointment'])[1]/preceding::div[1]</value>
      <webElementGuid>1623852b-358c-4118-8e50-1f946103c648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[9]/preceding::div[3]</value>
      <webElementGuid>22b9334f-31fe-4775-bc84-d6c4b5d724e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Future Automation Test with B Automation, B Client MR# 24-11007: 5 Panel Drug Screen']/parent::*</value>
      <webElementGuid>c2fd05f4-22d7-4113-b76c-b7f567b615f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>e159b19a-60ca-4677-a3cf-52b376243d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Future Automation Test with B Automation, B Client MR# 24-11007: 5 Panel Drug Screen' or . = 'Future Automation Test with B Automation, B Client MR# 24-11007: 5 Panel Drug Screen')]</value>
      <webElementGuid>96532fa4-f91c-4d2e-93d2-676a03493a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
