<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All Items</name>
   <tag></tag>
   <elementGuidId>b0d7e5f7-c03b-4866-a3bc-56e2c4fce483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-timeline-block-items-type-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-timeline-block-items-type-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;All Items&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6caf4c2a-8116-418d-85cb-eb6e7c056a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a7a32f9b-fc92-4ab2-a745-2989a2165399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-timeline-block-items-type-container</value>
      <webElementGuid>4dc25d96-7c7e-448e-a6f2-b28d2e880001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All Items</value>
      <webElementGuid>921fd34c-deb6-4eed-a40f-5c105989b0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Items</value>
      <webElementGuid>9f8f0771-c2f0-4ee9-b482-41cef7bb4401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-timeline-block-items-type-container&quot;)</value>
      <webElementGuid>aa603d1d-5d87-40d8-b914-0b18d0f090d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-timeline-block-items-type-container']</value>
      <webElementGuid>788a4ce3-086f-4075-9fb1-01b8cfc20640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clientprofileblock']/div/div[3]/div/div/div/div/span/span/span/span</value>
      <webElementGuid>0cfe0429-b3e6-42e6-bc71-6615bb17e846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timeline'])[1]/following::span[4]</value>
      <webElementGuid>e3fd8507-cf83-49f9-be9f-04a1b49ddea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B2@automation.com'])[3]/following::span[4]</value>
      <webElementGuid>ddd666cf-4e6c-417c-a77a-7837ad7bd589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='calendar_month'])[2]/preceding::span[3]</value>
      <webElementGuid>9603e88f-b032-4f21-9765-c338636677d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::span[4]</value>
      <webElementGuid>6c02b17f-b949-498a-8c93-b2258e8fd60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>74b7968f-5581-4d30-a1b8-f2f0f93bac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-timeline-block-items-type-container' and @title = 'All Items' and (text() = 'All Items' or . = 'All Items')]</value>
      <webElementGuid>d0a2bda1-9516-41fa-a4a5-77f5d7774123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
