<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_arrow_outward</name>
   <tag></tag>
   <elementGuidId>1ecf112c-5ae1-4e24-9d08-4c379511eacd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='clientprofileblock']/div/div[3]/div/div/div/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.timeline-open-icons.pointer > span.material-symbols-outlined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;arrow_outward&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3843fccc-0a17-4386-bcec-8b0d5336bd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-symbols-outlined</value>
      <webElementGuid>53274377-9856-432a-9319-8d93c6225b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_outward</value>
      <webElementGuid>4c51b38d-187d-4267-821d-186eecf03753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientprofileblock&quot;)/div[@class=&quot;client-profile--content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 sm-12&quot;]/div[@class=&quot;timeline-container-element&quot;]/div[@class=&quot;timeline-header&quot;]/div[@class=&quot;timeline-icons&quot;]/a[@class=&quot;timeline-open-icons pointer&quot;]/span[@class=&quot;material-symbols-outlined&quot;]</value>
      <webElementGuid>be8d137b-2e2e-48d9-978f-dca1c005a677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='clientprofileblock']/div/div[3]/div/div/div/div[2]/a/span</value>
      <webElementGuid>fdf33bff-71ad-459a-8c14-d9012c4c78ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[8]/following::span[1]</value>
      <webElementGuid>df8e2942-a4f6-4429-932d-64dd2e130bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[8]/following::span[2]</value>
      <webElementGuid>db25e481-da57-4809-8312-869ccf6bfb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Wednesday'])[1]/preceding::span[1]</value>
      <webElementGuid>948d99d6-c6e1-4b0f-bf9d-5faab143fd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Future Automation Test with B Automation, B Client MR# 24-11007: 5 Panel Drug Screen'])[1]/preceding::span[2]</value>
      <webElementGuid>943beca3-c44f-482e-9a1c-a19414b4ebd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='arrow_outward']/parent::*</value>
      <webElementGuid>78c2335b-657a-4164-9512-353adc08e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/a/span</value>
      <webElementGuid>f2f4aac1-7b76-4ad7-b0f8-dcea3eda44dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'arrow_outward' or . = 'arrow_outward')]</value>
      <webElementGuid>3416b84f-81ab-4d53-a5f8-32a07df98d3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
