<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Prescribed</name>
   <tag></tag>
   <elementGuidId>08df9084-2b47-4c09-8c61-01b6d6f262e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Instructions'])[1]/following::td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#porow8 > td:nth-of-type(8)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Prescribed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>31381869-7b26-4711-908f-96298414265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prescribed</value>
      <webElementGuid>8d8917f3-cc5b-43a8-bf47-31166a9d225c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;porow8&quot;)/td[8]</value>
      <webElementGuid>4a110161-59db-407a-8684-fce1379d257a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='porow8']/td[8]</value>
      <webElementGuid>8266af14-50f3-403b-b7ac-64fe92d56861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Instructions'])[1]/following::td[1]</value>
      <webElementGuid>6018d6d6-2a28-4ad5-99a3-a4f987162f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Prescriber'])[1]/following::td[2]</value>
      <webElementGuid>064d7aa3-b33f-40b5-9e3f-d8c02c5483aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescription Dispositions'])[1]/preceding::td[2]</value>
      <webElementGuid>e142022b-9a94-44a6-ac9d-ca385472b313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[51]/preceding::td[2]</value>
      <webElementGuid>9fdfee94-397d-40e6-aec9-2c4525847efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/table/tbody/tr/td[8]</value>
      <webElementGuid>1ef2f627-f422-4e4c-9a99-d4514a6ea450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Prescribed' or . = 'Prescribed')]</value>
      <webElementGuid>9bc06a1f-abb0-4343-9b1b-52bb44693506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
