<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Automation Event</name>
   <tag></tag>
   <elementGuidId>3dec4045-57f1-45c7-99e8-6f6bb5a851bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover256365']/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#popover256365 >> internal:text=&quot;Automation Event&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f680ea18-48a8-4291-9ef7-55e779be9892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78abbf9d-cc65-44f2-b0fe-3edba13f6287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Event</value>
      <webElementGuid>248a7fc7-5d53-4d5d-94a8-d8299179c165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover256365&quot;)/div[@class=&quot;popover-content&quot;]/div[@class=&quot;event-details-popover flex-col&quot;]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>b4d99e2a-2066-4ba4-82db-4bbb9b5c91e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover256365']/div[2]/div/span</value>
      <webElementGuid>2aadb33b-30fb-4a67-8b61-39bbea76f3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='delete'])[2]/following::span[1]</value>
      <webElementGuid>c0ed875e-8fce-4701-a8b7-5be216d824e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[4]/preceding::span[1]</value>
      <webElementGuid>63eb5217-fd4a-403a-9750-ddbbf4aab69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test'])[3]/preceding::span[2]</value>
      <webElementGuid>92d3c696-c888-4bc3-ac66-198a0dbf3f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/span</value>
      <webElementGuid>13f04499-c670-4d80-8486-c5fc07d9c3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Automation Event' or . = 'Automation Event')]</value>
      <webElementGuid>7777f0e8-2cc2-4d16-be86-51e1f117643a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
