<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_UDS</name>
   <tag></tag>
   <elementGuidId>15eee44c-716b-4465-8b8c-3535f90cb313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medevaluds > h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='medevaluds']/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot; UDS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>243b53b6-5830-4d33-bbfe-bfb9bea30f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> UDS</value>
      <webElementGuid>263c58f7-aae8-405e-9d35-c5cdedd6b027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medevaluds&quot;)/h4[1]</value>
      <webElementGuid>9c022c6b-764e-4669-951d-ed385fae5718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='medevaluds']/h4</value>
      <webElementGuid>b4a252a0-926b-49fc-9b75-ddc1aceaef34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAL'])[1]/following::h4[1]</value>
      <webElementGuid>d26540f8-4857-42fe-9209-062fc86ac105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergies'])[1]/following::h4[2]</value>
      <webElementGuid>dfdfdc64-9fa9-48c9-8542-c0aafb7bc1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vital Signs'])[1]/preceding::h4[1]</value>
      <webElementGuid>d11365d4-cdf7-438f-bd18-a1501f6e35cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB Testing'])[1]/preceding::h4[2]</value>
      <webElementGuid>8dc03991-92a3-433d-ad14-0c621e61c606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UDS']/parent::*</value>
      <webElementGuid>40e1a579-fcea-4363-901f-987aad2b14d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/h4</value>
      <webElementGuid>8b20ef83-208a-4d88-8103-0c8eb773ecf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' UDS' or . = ' UDS')]</value>
      <webElementGuid>5ddbab48-c93e-40fb-b7c6-5159860c8684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
