<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Last  30 days</name>
   <tag></tag>
   <elementGuidId>b8990ac8-3b39-49d1-a429-cc3b655b2a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='timeline_block_daterange_filter_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#timeline_block_daterange_filter_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#timeline_block_daterange_filter_value</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>189ae008-64cf-4564-9422-112cbae814df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeline_block_daterange_filter_value</value>
      <webElementGuid>60f97dfb-f1de-418b-8e36-d12580047110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last  30 days</value>
      <webElementGuid>169114c4-a4aa-49ae-a5bf-88835979e721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeline_block_daterange_filter_value&quot;)</value>
      <webElementGuid>b8b18684-3ca4-46ad-ac03-63cbd82ae953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='timeline_block_daterange_filter_value']</value>
      <webElementGuid>02e6d9fb-9d4d-43b6-9c61-770878f2feb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='timeline_block_daterange_filter']/div/span[2]</value>
      <webElementGuid>627d5bd8-42e9-4ccc-a4e8-68606f61501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='calendar_month'])[2]/following::span[1]</value>
      <webElementGuid>e83ca742-e90d-4e0e-97cf-401020ad5c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Items'])[2]/following::span[4]</value>
      <webElementGuid>e149e6c1-7d46-4bd2-b5ca-13b054af6e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::span[1]</value>
      <webElementGuid>7b2530b8-41ac-485c-817e-84871ffbffc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last week'])[1]/preceding::span[2]</value>
      <webElementGuid>7884198d-fd2c-4d5e-a8f5-73acbc7c3735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/span[2]</value>
      <webElementGuid>dc12669d-068d-4db7-a802-8e3fe263b3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'timeline_block_daterange_filter_value' and (text() = 'Last  30 days' or . = 'Last  30 days')]</value>
      <webElementGuid>238b7671-3d61-4f8e-8247-e01831758a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
