<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo</name>
   <tag></tag>
   <elementGuidId>10dd20bd-75b5-4a16-a388-d10038747a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wakefulnessyn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wakefulnessyn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Were there periods of wakefulness?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ce699bc-7e50-4360-8092-bc5074e79aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wakefulnessyn</value>
      <webElementGuid>6d8221dd-90e3-4484-af6a-de9a94e6f337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wakefulnessyn</value>
      <webElementGuid>e00c2594-a01c-4198-8b9b-4b6a3a8e0189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control yn locker audropdown</value>
      <webElementGuid>77ceb808-9686-46f9-b924-9a0718cce851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldname</name>
      <type>Main</type>
      <value>wakefulnessyn</value>
      <webElementGuid>fec264e2-dbed-4504-8201-4da5c9d7a34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablename</name>
      <type>Main</type>
      <value>amratings</value>
      <webElementGuid>23dc97a7-44fa-416e-a1a0-590265846c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>15fd221e-9774-4574-90ed-e175abf180fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wakefulnessyn&quot;)</value>
      <webElementGuid>b3ee4430-42c2-45a8-9989-4d7bddcae327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wakefulnessyn']</value>
      <webElementGuid>55c1ce39-412d-446c-bd86-040531f48a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amrating.edit']/div[2]/div/form/div/div/div[5]/div/div/select</value>
      <webElementGuid>d8c6f0b6-f0e5-4b4d-a2e2-2f088bf46766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Were there periods of wakefulness?'])[1]/following::select[1]</value>
      <webElementGuid>ebcb46b4-3950-4f9a-aef6-9121a6babeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many hours of restful sleep did you receive last night?'])[1]/following::select[1]</value>
      <webElementGuid>6e78788a-7a8d-4d87-a3b0-22f9b123320d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Were there periods of wakefulness?'])[2]/preceding::select[1]</value>
      <webElementGuid>4f561613-3beb-482c-8534-ee0a163d1d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If yes, please describe:'])[1]/preceding::select[1]</value>
      <webElementGuid>57742260-5fc1-4c77-8993-b1f84db0bea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>ea4325db-8da7-430d-9af2-2d21876dd5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wakefulnessyn' and @id = 'wakefulnessyn' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>eb7e4262-b0d0-47cf-b0f2-b67875e65b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
