<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo_1_2_3</name>
   <tag></tag>
   <elementGuidId>2f33cb70-50a4-4ade-bbc7-8d9ecb850478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='painyn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#painyn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Are you experiencing any pain?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a87d309f-421f-4de1-842a-4b7ff6d6f83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>painyn</value>
      <webElementGuid>d071fd0c-251f-4377-b500-168211f9445a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>painyn</value>
      <webElementGuid>5b57256d-b39e-4032-9cf3-b7f28c6618ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control yn locker audropdown</value>
      <webElementGuid>e9a114c1-ccc5-41b2-869f-65594c36810f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldname</name>
      <type>Main</type>
      <value>painyn</value>
      <webElementGuid>227e8e65-a0e1-4bfa-9afc-8f82bca90669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablename</name>
      <type>Main</type>
      <value>amratings</value>
      <webElementGuid>db79d664-b10a-4b9e-9c25-998620dd7f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>ec4ff3b6-5fae-4a20-8c61-9d39a067b565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;painyn&quot;)</value>
      <webElementGuid>1193d52a-4f05-4ab6-a83d-1762fbc70c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='painyn']</value>
      <webElementGuid>1fad5898-df43-4d53-8d5d-70b38194e401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amrating.edit']/div[2]/div/form/div/div/div[22]/div/div/select</value>
      <webElementGuid>3f203da7-aed9-4d7d-9b0f-7ceacd83180f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you experiencing any pain?'])[1]/following::select[1]</value>
      <webElementGuid>72f5d310-286a-483d-8778-4c8919520a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severity of Anxiety:'])[1]/following::select[1]</value>
      <webElementGuid>6c934549-ffcf-4c41-bbc1-bf392e4c2e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you experiencing any pain?'])[2]/preceding::select[1]</value>
      <webElementGuid>d4779ef7-eaa3-4259-b109-eb42b9eb0fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Character: Please describe your pain:'])[1]/preceding::select[1]</value>
      <webElementGuid>6165bf24-b970-42c2-80bb-bfe568a644c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/select</value>
      <webElementGuid>c20efc94-400b-4d21-932d-a8de25b81de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'painyn' and @id = 'painyn' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>78e12ed6-1aaa-406c-a068-bb0d44e1027e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
