<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo_1</name>
   <tag></tag>
   <elementGuidId>509b6816-e77e-4823-8573-5a808b00e2e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='nightmaresyn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nightmaresyn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Did you experience nightmares, using dreams?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5bda060-5725-46cd-8b9e-fa5d9262972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nightmaresyn</value>
      <webElementGuid>868c288e-46b8-403d-a9ef-6bc572cae141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nightmaresyn</value>
      <webElementGuid>6101dfb1-759e-4cef-970f-665765087a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control yn locker audropdown</value>
      <webElementGuid>be0dde90-0be3-4d83-bdd5-43a37443b41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldname</name>
      <type>Main</type>
      <value>nightmaresyn</value>
      <webElementGuid>ff63764d-9069-4f71-a499-d5b00ef56b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tablename</name>
      <type>Main</type>
      <value>amratings</value>
      <webElementGuid>cb7130b5-0701-4699-9406-1a8309a2653c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>f0dd2966-638f-49fe-af1a-01398936a0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nightmaresyn&quot;)</value>
      <webElementGuid>0eb6c211-57ad-4e1a-9264-24066977ae0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='nightmaresyn']</value>
      <webElementGuid>74480322-4da9-4ce3-b222-13e149cf86ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amrating.edit']/div[2]/div/form/div/div/div[8]/div/div/select</value>
      <webElementGuid>44ebf78e-5bad-4c5b-8fc4-64897c7b1160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Did you experience nightmares, using dreams?'])[1]/following::select[1]</value>
      <webElementGuid>fb03240a-8430-4e43-9873-698de26e0529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If yes, please describe:'])[1]/following::select[1]</value>
      <webElementGuid>94c3723f-5705-4399-a210-ef9a83dbc9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Did you experience nightmares, using dreams?'])[2]/preceding::select[1]</value>
      <webElementGuid>b8aa7ba8-4f4e-472b-8bb7-1c9968ed9f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If yes, please describe:'])[2]/preceding::select[1]</value>
      <webElementGuid>9ec0f9f2-597a-4ec0-aee1-b2dbdc479aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>b52fda33-2497-4d39-9160-8f07182a4637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'nightmaresyn' and @id = 'nightmaresyn' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>501848dd-5fe5-4e82-8be6-929380abd675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
