<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inhaled Oxygen Concentration_inhaled__06efa9</name>
   <tag></tag>
   <elementGuidId>cd980375-2a7a-4863-a3ee-2df1625379e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inhaled_oxygen_concentration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inhaled_oxygen_concentration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inhaled_oxygen_concentration</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb2cd251-5e38-4ea5-81a7-3de1a348d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9a12b6c-4885-444e-9f88-1635bb0aa760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inhaled_oxygen_concentration</value>
      <webElementGuid>f6ba45c8-fc3b-4158-8c7f-6bf4ea8fec3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inhaled_oxygen_concentration</value>
      <webElementGuid>368fe368-e22b-4efd-805a-5f2746495ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsaddfield</value>
      <webElementGuid>268fd0f9-09bc-40c0-9ad4-700c9592ead3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inhaled_oxygen_concentration&quot;)</value>
      <webElementGuid>6637543f-24f5-4567-88e1-8ef5564ffa61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inhaled_oxygen_concentration']</value>
      <webElementGuid>de7d2b30-c97d-42de-868b-d983efcdb665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsadd']/div[3]/div[2]/div/input</value>
      <webElementGuid>d470afc5-2cde-4985-926b-9b1aaecc65c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div[2]/div/input</value>
      <webElementGuid>3f0fcc50-e5e4-429a-a4f6-7fa1e4a63b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'inhaled_oxygen_concentration' and @id = 'inhaled_oxygen_concentration']</value>
      <webElementGuid>646a66ea-448f-4f51-97ff-7453f36a2337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
