<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Additional Information_vsadditional</name>
   <tag></tag>
   <elementGuidId>fc46a9d3-a76c-4019-932e-235f3aa68dfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vsadditional']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vsadditional</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#vsadditional</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fdd5ccd-70d0-4a76-bfdf-644d77a2debd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b650b645-9fc4-49a0-a58f-e5d525be72a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vsadditional</value>
      <webElementGuid>3d3e3a22-ec76-431a-9c14-30c4c25598a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vsadditional</value>
      <webElementGuid>3aebc6a8-e1c2-48c2-9067-0f51bf265618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control vsaddfield</value>
      <webElementGuid>583ef37a-be73-40c6-8766-e88df57b0b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vsadditional&quot;)</value>
      <webElementGuid>35676659-9cf0-457d-9a32-3f26585b4baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vsadditional']</value>
      <webElementGuid>6133808e-e349-4050-810a-419226a14e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmvsadd']/div[4]/div/div/input</value>
      <webElementGuid>6584bbcd-2c5c-423b-a17f-079c08880187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div/div/input</value>
      <webElementGuid>13a4c886-5eb9-408b-a52d-96c09ff33ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vsadditional' and @id = 'vsadditional']</value>
      <webElementGuid>0cf86a33-d7b0-4106-be82-1e000703f9a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
