<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-group-1639586686870_117</name>
   <tag></tag>
   <elementGuidId>7a4492d1-d93c-4f88-ad6e-cf89d8990789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-group-16395866868700 Not present']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;radio-group-16395866868700\ Not\ present&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>166fc861-58a9-4cae-a366-3dd1338bcf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a8fbb581-372c-49f6-97bc-6e4c00a9a259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locker autoupdateformdata required</value>
      <webElementGuid>984cba6c-5293-474c-bf71-9617398e9735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-group-1639586686870_117</value>
      <webElementGuid>34e7039b-574f-4608-a791-16897bf493a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group_id</name>
      <type>Main</type>
      <value>radio-group-1639586686870</value>
      <webElementGuid>60591e0d-a2ff-4ee0-9a8f-04818f25fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-group-16395866868700 Not present</value>
      <webElementGuid>7af80216-3b08-43e7-9634-050b1468df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0 Not present</value>
      <webElementGuid>9b11135f-047e-4fab-9a4d-cad9b2f5c02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-score</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c99c1b94-e107-481f-b842-7f515cca18ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scorename</name>
      <type>Main</type>
      <value>Score</value>
      <webElementGuid>38270336-2c99-48a6-b44f-4125aa5c9e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inquiry_id</name>
      <type>Main</type>
      <value>1673</value>
      <webElementGuid>656215ca-133b-4810-b9b0-9e3c0bcd821a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-docid</name>
      <type>Main</type>
      <value>117</value>
      <webElementGuid>b520a153-cf6f-4517-9fb4-e2a1a5ed5b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sluglabel</name>
      <type>Main</type>
      <value>0Notpresent</value>
      <webElementGuid>42c13b00-7358-44f0-b0b5-b77ab24b94d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-group-16395866868700 Not present&quot;)</value>
      <webElementGuid>ddf3eb66-fdad-4874-9d65-6b6277760cfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-group-16395866868700 Not present']</value>
      <webElementGuid>adc66f2f-7447-4b49-ba62-368e71efa456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_radio-group-1639586686870']/span/input</value>
      <webElementGuid>47bca4f9-d7ec-4b89-b4a0-598eb51bce01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/span/input</value>
      <webElementGuid>e83e58f1-7760-48e8-94bc-cfb796ec2261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio-group-1639586686870_117' and @id = 'radio-group-16395866868700 Not present']</value>
      <webElementGuid>c4e2b6b7-4cd9-4192-91a0-c0209d6f9ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
