<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amount</name>
   <tag></tag>
   <elementGuidId>a312f977-53f1-45cf-9f55-c739885e95d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.open > #censusdash_toggle > a.btn.btn-secondary.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='censusdash_toggle']/a)[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Amount&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f56db3df-1c79-4227-99e0-5e683b72e77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>75a099c7-e2e6-4e62-a2f6-d85a237ffe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary dropdown-item</value>
      <webElementGuid>336c4033-6561-4d18-b543-049a85ba6fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:click</name>
      <type>Main</type>
      <value>$set('invoiceData.data.discount_percent', 0)</value>
      <webElementGuid>fb99fff8-285c-4458-89d4-7bca492ae726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Amount
                                                        </value>
      <webElementGuid>94681535-caff-43fe-b0d4-cbc72ab648dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-md-12&quot;]/div[@class=&quot;bill-config&quot;]/div[@class=&quot;panel m_rounded panel-primary mb-4&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;panel__controls-group m_no-margin&quot;]/div[@class=&quot;item m_columns&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;dropdown open&quot;]/div[@id=&quot;censusdash_toggle&quot;]/a[@class=&quot;btn btn-secondary dropdown-item&quot;]</value>
      <webElementGuid>0b337c5e-b305-4454-9994-c3b4eb16448d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='censusdash_toggle']/a)[9]</value>
      <webElementGuid>04af7814-c560-4cbe-af25-7eb386acccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Amount')]</value>
      <webElementGuid>90ca6b2f-7cc8-419c-b48a-860674f8daa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount Type'])[1]/following::a[1]</value>
      <webElementGuid>ea712516-f758-4dd5-a3b6-c9b7848e41cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percent'])[1]/preceding::a[1]</value>
      <webElementGuid>55be5477-18df-4317-bce1-b54b864d7582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/preceding::a[2]</value>
      <webElementGuid>e12e599c-3945-4a58-a62a-d25868b51f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amount']/parent::*</value>
      <webElementGuid>ec955a7a-ebc4-4306-ab61-b60deec4a0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[9]</value>
      <webElementGuid>1bade4b8-fec2-47c2-a709-e9e0d470419f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/a</value>
      <webElementGuid>c0c28b33-7420-4267-8b91-875b266e0652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '
                                                            Amount
                                                        ' or . = '
                                                            Amount
                                                        ')]</value>
      <webElementGuid>5aae7860-a2db-4a02-bd70-3dd7e8b06eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
