<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>d53b36c3-6ba9-41b4-adf8-7bb5df2cb772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-secondary.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[35]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;×\n                \n                Linked Payment Plans\n                                    No payment plans found\n                            \n            \n                 Close&quot;i >> internal:text=&quot;Close&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e60b41f-0581-43e4-98eb-15225129e3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e691b032-b121-45d6-ab02-4c1c09da687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-secondary text-danger</value>
      <webElementGuid>2e56cfaf-a703-4131-b4b3-c8f10aeaf844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0100e4f4-32a8-48cd-9ec9-fbd4fa40fe2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Close</value>
      <webElementGuid>37e436af-c59f-400f-a408-d9b64d9d8b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice_payment_plans_list&quot;)/div[@class=&quot;modal-dialog modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-sm btn-secondary text-danger&quot;]</value>
      <webElementGuid>437a0ca0-3de0-4c9d-9c1a-90deb08db76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[35]</value>
      <webElementGuid>af49ee0c-3d89-4438-b40f-5ef9eada4a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='invoice_payment_plans_list']/div/div/div[2]/button</value>
      <webElementGuid>2ab3997f-8d14-4fcd-96e3-b0339467f926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No payment plans found'])[1]/following::button[1]</value>
      <webElementGuid>d8654003-ccc5-48a4-896c-c29a399d6647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linked Payment Plans'])[1]/following::button[1]</value>
      <webElementGuid>72e129c4-26dc-4129-a218-7fb9abce9156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linked Payments'])[1]/preceding::button[2]</value>
      <webElementGuid>6bd72b42-cf68-4490-b65c-00a8dbabafe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No linked payments.'])[1]/preceding::button[2]</value>
      <webElementGuid>3f8cd1c7-331c-4225-bb75-c497986d6860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/button</value>
      <webElementGuid>ac7ce154-9b73-48bf-bf61-025526969e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Close' or . = ' Close')]</value>
      <webElementGuid>904367a5-f0a9-4922-887a-78eb94e0bb73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
