<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>6cd16035-713b-4b66-ba2f-4d38a5c012dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pdf-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenuButton']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d8216dd-6f68-4252-aed6-b4997d106366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdf-download</value>
      <webElementGuid>0ccdd3dc-b7e3-4721-82b7-f1e79f607b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>5c315621-0513-41f9-a639-fdc1296274af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuButton&quot;)/span[@class=&quot;pdf-download&quot;]</value>
      <webElementGuid>5f56804b-aa80-49fd-a1d0-fabf013cf94b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenuButton']/span</value>
      <webElementGuid>e6d35334-f2f3-4977-8240-31e3c02ec68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::span[1]</value>
      <webElementGuid>9dc92ce4-4cf1-498f-a747-39cd1ee21230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect Payment'])[1]/following::span[2]</value>
      <webElementGuid>7f342520-3a9f-46b0-99b9-df8b7f4c9350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect Payment'])[2]/preceding::span[4]</value>
      <webElementGuid>1fe5c6f8-fc3b-4aba-8c6f-a3f72cf23f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Name:'])[1]/preceding::span[4]</value>
      <webElementGuid>a4e23ccc-c19f-4c8b-b2f6-9f157ac08d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='...']/parent::*</value>
      <webElementGuid>f58322d7-9b45-4e2f-8664-817efbefea3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/span</value>
      <webElementGuid>655aaba4-e287-4840-b252-9029228b6f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '...' or . = '...')]</value>
      <webElementGuid>e29703ac-6352-43ca-8483-7a4ccba33615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
