<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Yes</name>
   <tag></tag>
   <elementGuidId>df8c6783-bb1a-48ae-b12e-cc33cceb0af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblcontacts']/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tblcontacts > tbody > tr.bg-success > td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Yes&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4a56950a-8100-49e5-a37e-ead8348016c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Yes
                                            </value>
      <webElementGuid>9d7ca387-a018-412b-b5d9-a114edba1eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblcontacts&quot;)/tbody[1]/tr[@class=&quot;bg-success&quot;]/td[4]</value>
      <webElementGuid>138d1bae-c2e2-4e78-9372-1ca3ba4f6dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblcontacts']/tbody/tr/td[4]</value>
      <webElementGuid>88018cf1-aed1-4a8f-8992-31a4e09d08c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(833) 957-2888 x'])[1]/following::td[1]</value>
      <webElementGuid>a2e477d9-688c-499d-ab51-1d19f4b51f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B Parent B Client'])[2]/following::td[2]</value>
      <webElementGuid>96b99b2f-24d9-4db8-8d65-60b7088bc9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent or Guardian'])[1]/preceding::td[1]</value>
      <webElementGuid>034a64aa-2314-4454-b7ed-4306457b289b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[4]/preceding::td[2]</value>
      <webElementGuid>8a9ac94e-712f-4869-abf0-ecda91057024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>f25694ad-f9ee-4ca2-992f-b760b1eed986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                Yes
                                            ' or . = '
                                                Yes
                                            ')]</value>
      <webElementGuid>91a09ca1-81d3-4601-88e0-3735c3fcd903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
