<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Satellite Office_btn btn-primary btn-rais_d7a22f</name>
   <tag></tag>
   <elementGuidId>7d9ec851-7375-47c0-8a8a-855f2840c4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > a.btn.btn-primary.btn-raised.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblcentralstore_client_profile']/tbody/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>539594bd-20ff-42cb-b3e1-c8097c73f46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-raised btn-sm</value>
      <webElementGuid>7e9ae667-905b-4461-8f3b-52e2550ff895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/centrallystored/18/edit?currentClientId=1558</value>
      <webElementGuid>917c43d6-1954-4f38-bdea-2b400766313c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblcentralstore_client_profile&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/a[@class=&quot;btn btn-primary btn-raised btn-sm&quot;]</value>
      <webElementGuid>1f7b1cbc-5245-4b0f-a718-379d574f7681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblcentralstore_client_profile']/tbody/tr/td[3]/a</value>
      <webElementGuid>ab7dcccc-0520-4084-9991-a4381a35f81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satellite Office'])[3]/following::a[1]</value>
      <webElementGuid>8115d00b-73e1-4ae1-a131-51994033fc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::a[1]</value>
      <webElementGuid>fd05f018-d3f7-4dcc-ac3c-c520dacd3d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::a[1]</value>
      <webElementGuid>1b82bc43-d66b-40af-af23-926af491e7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medication Dispositions'])[1]/preceding::a[4]</value>
      <webElementGuid>3ece1d54-741f-4430-a511-2b32b77e27ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/centrallystored/18/edit?currentClientId=1558')]</value>
      <webElementGuid>1dfe8b9c-8f86-4984-9b57-12c21ddd9151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>3fd550d3-2b26-4e03-978f-d09cea9727e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/centrallystored/18/edit?currentClientId=1558']</value>
      <webElementGuid>38430f5e-19af-40f5-80ef-b101ef23399c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
