<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_No medical orders to display at this time</name>
   <tag></tag>
   <elementGuidId>72c6ed7d-1d45-4579-99c7-8298511db54d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblmedorders']/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tblmedorders > tbody > tr.odd > td.dataTables_empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;No medical orders to display at this time.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7b94cbc2-ef8e-4bb5-8726-6d2591a9b09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>051e6a4a-336d-4b59-b739-5f5ab1024cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>2d9ad93c-b4d9-4735-851b-9587161ad5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_empty</value>
      <webElementGuid>cc00e6dc-aeca-46c6-9308-4a3b240d4443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No medical orders to display at this time.</value>
      <webElementGuid>54cac8c9-79a5-4d61-b8d7-9807dd72683a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblmedorders&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dataTables_empty&quot;]</value>
      <webElementGuid>4479eb8d-190b-4754-b5e6-e2b5312a9ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblmedorders']/tbody/tr/td</value>
      <webElementGuid>1c76d30d-619b-44cf-a25c-342f49a2aab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[5]/following::td[1]</value>
      <webElementGuid>77146659-4c33-461d-8696-a7c86d4fd742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Stop'])[1]/following::td[1]</value>
      <webElementGuid>ba878c58-b943-44f9-a686-ec822add0a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(filtered from 1 total entries)'])[1]/preceding::td[1]</value>
      <webElementGuid>89946c5d-c50c-4438-af7e-7001cc0cda89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[24]/preceding::td[1]</value>
      <webElementGuid>9dd0bcc7-2c59-42d1-ac9d-0bf2a641c639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No medical orders to display at this time.']/parent::*</value>
      <webElementGuid>96f64a5e-4fdc-4cb2-89be-0d568edd7061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>a1a0faff-4ac8-488e-b8c1-3f2954727c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'No medical orders to display at this time.' or . = 'No medical orders to display at this time.')]</value>
      <webElementGuid>976889f3-cdc7-47c8-8a3b-8f6ecd7311ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
