<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>b69c842e-c591-401d-90ef-9a960edbe5ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnmainfrmsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnmainfrmsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e8769c0-6d3e-412a-b690-691eff4fed88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-raised btn-primary btn-block locker nodoubleclick topazsig</value>
      <webElementGuid>1653a0c5-4aef-49bf-b4d0-8909f10d2347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8cc17d11-fa23-449b-8a0b-bea940cf5553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>b23a50b4-f188-4858-9a5e-1feb51082246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnmainfrmsubmit</value>
      <webElementGuid>2ee674f6-afb9-4d60-a102-b91003a7063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save
        </value>
      <webElementGuid>c5ba8252-4a84-4e56-be37-b5296d2be021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnmainfrmsubmit&quot;)</value>
      <webElementGuid>b311364d-2ef4-4ecb-8ad8-1d0a0ab1257e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnmainfrmsubmit']</value>
      <webElementGuid>63cf60c4-47dd-4382-9053-b00ac21cb387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creator / Last Editor Name - Automation Test'])[1]/preceding::button[1]</value>
      <webElementGuid>66e968ca-ac1a-47ae-a977-6fc19267131a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/button</value>
      <webElementGuid>2ee2ef11-04a1-4a04-9892-4de0df5dfca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and @id = 'btnmainfrmsubmit' and (text() = ' Save
        ' or . = ' Save
        ')]</value>
      <webElementGuid>4d4de18c-247e-48b2-9004-9843f023717e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
