<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>8ab681f6-3244-472e-95de-62c9d50c95b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-search.btn-primary.btn-raised.btn-sm.markContinueAtDischarge.locker.btn-block.hidden-print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ef44231-7f90-4ba5-a166-cb1fea86dfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61fe1fda-45bd-42be-85e4-41f8a4494cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-search btn-primary btn-raised btn-sm markContinueAtDischarge locker btn-block hidden-print</value>
      <webElementGuid>8d953145-6e6f-40eb-b017-7063b6b89a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medorder_id</name>
      <type>Main</type>
      <value>1510</value>
      <webElementGuid>d2b332e1-c3cf-4433-af80-68eb23bd928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                      Continue
                                </value>
      <webElementGuid>f1a72959-ad42-44a8-85b3-7fcd7da2977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medorderrow1510&quot;)/td[@class=&quot;dcmedslistStatusCell&quot;]/button[@class=&quot;btn btn-search btn-primary btn-raised btn-sm markContinueAtDischarge locker btn-block hidden-print&quot;]</value>
      <webElementGuid>c9fa3bdd-fac6-474d-81e0-2654e67ae41d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>680dfbac-af89-4908-8a3b-cc5c7050d905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='medorderrow1510']/td[6]/button[2]</value>
      <webElementGuid>452132e5-4dc0-4b8e-9ba2-89ce18fcb2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View/Print'])[1]/preceding::button[3]</value>
      <webElementGuid>3724c571-9baa-4d23-9ae1-ed77d2d0dc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>8c7fb2e9-d37b-4c2c-bd61-f090e18fabf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button[2]</value>
      <webElementGuid>de5c37cd-1225-40ce-93c2-236685ad37bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                      Continue
                                ' or . = '
                                      Continue
                                ')]</value>
      <webElementGuid>99ff36cb-358a-41d8-8584-a749d4503f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
