<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entered in Error_iseie</name>
   <tag></tag>
   <elementGuidId>e2d97487-2dc5-491d-abc4-cd5b206b04c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iseie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iseie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entered in Error&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12a4d92a-402b-4f11-b1e2-e937a08267b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7145ce0a-6342-4138-a67c-31acd3d382c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iseie</value>
      <webElementGuid>93e78ed9-ef44-4464-ad80-92e84a016616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>showEieSection</value>
      <webElementGuid>45d44177-85df-4a93-aa29-8ec4ec256e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iseie&quot;)</value>
      <webElementGuid>70d8b97e-3656-4532-aa3e-7b97ad5ae0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iseie']</value>
      <webElementGuid>d3dec9ab-fd86-4a52-b905-07ec4bb1d0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/label/input</value>
      <webElementGuid>f6a7fc64-c6a2-49a6-b042-87ab4c5191e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'iseie']</value>
      <webElementGuid>4cbd9328-0e12-497c-a7c6-aa174621e057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
