<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign and Lock_dss</name>
   <tag></tag>
   <elementGuidId>07b07a7c-3d95-4ec7-94a3-61446bdfa3d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign and Lock&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58d1f378-385c-4702-9ee8-452e4ee61aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1c3a34aa-9eb0-4a1e-99dc-cf2bf0fdedf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>4efc6c40-d5e2-484b-ab03-de01eda57960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>6883c8a8-8806-4a3b-ae43-3d6bd926a189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1291cb91-00bb-499e-92bb-84e9f2a5f642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkcosign locker</value>
      <webElementGuid>60a041a9-4d38-4d69-930c-3f240070093d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dss&quot;)</value>
      <webElementGuid>6a87fde1-d4cc-4fa2-a3e3-fc51a900ab07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dss']</value>
      <webElementGuid>f48ebbf4-5e12-4fbd-97f3-10e57c53b0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainDssSection']/div/label/input</value>
      <webElementGuid>2bcacb1a-ac28-4579-b6e6-b83dd6e36fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/label/input</value>
      <webElementGuid>b52ae2ff-9535-4bac-a3c3-e79e8e6bc1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'dss' and @id = 'dss']</value>
      <webElementGuid>5c7ab868-92b2-4868-a50b-daef68ce9463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
