<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign and Lock_dss</name>
   <tag></tag>
   <elementGuidId>07b07a7c-3d95-4ec7-94a3-61446bdfa3d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign and Lock&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1185f69f-fe45-48d9-9c75-d14f32e7870a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d17c143b-1379-4a4d-acba-481e1b20423a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>f313af3a-1e54-4725-a00f-4307083c6a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dss</value>
      <webElementGuid>22ff72a0-dee0-4023-8efd-fb6f54bf304f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af49a362-c21d-43ad-aefe-24c625894ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkcosign locker</value>
      <webElementGuid>f8dd3e72-2dcf-44ed-b152-9bbb1f7973ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dss&quot;)</value>
      <webElementGuid>1bf4888d-e81a-4159-8356-a4987d961ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dss']</value>
      <webElementGuid>3db3e6c6-76c4-42f0-ab27-76447855917f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainDssSection']/div/label/input</value>
      <webElementGuid>46937bbd-7c88-444e-b11a-24f449a2033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/label/input</value>
      <webElementGuid>5f9224cb-cb1b-4c41-a1bf-15ce2cb797a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'dss' and @id = 'dss']</value>
      <webElementGuid>0584a267-0f50-44d5-b1bf-188a218226b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
