<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entered in Error_iseie</name>
   <tag></tag>
   <elementGuidId>e2d97487-2dc5-491d-abc4-cd5b206b04c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iseie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iseie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entered in Error&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd0c110f-f942-4908-ba63-d9a2929d25d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dab969e8-8195-47b9-9dfd-34aea52b2c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iseie</value>
      <webElementGuid>7ad524aa-7425-42d7-a21d-0c99971fb63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>showEieSection</value>
      <webElementGuid>54811365-174c-4c12-af06-dbf0f0864f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iseie&quot;)</value>
      <webElementGuid>2e740755-a58a-4f32-852f-5d362bc46c4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iseie']</value>
      <webElementGuid>6aa68a76-52c9-4eb3-9c0f-f8c698519a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/label/input</value>
      <webElementGuid>b701027b-64f1-4d39-9853-ad3812fe48a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'iseie']</value>
      <webElementGuid>0bdad739-4882-43f9-b5d2-586714ac6272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
