<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_01152025</name>
   <tag></tag>
   <elementGuidId>657e39d8-be73-4f7b-930a-30297ba64e3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medorderrow1510 > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='medorderrow1510']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;01/15/2025&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>de2e4391-0cd0-4726-a6da-1b00430b661f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01/15/2025</value>
      <webElementGuid>ef3290f2-a21c-4892-882b-6aa79bba3cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medorderrow1510&quot;)/td[1]</value>
      <webElementGuid>559c2aa3-0721-427e-bbd4-7f3861b209d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='medorderrow1510']/td</value>
      <webElementGuid>6549d66a-9907-4e8d-bce3-fceaa7d1bd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status at Discharge'])[1]/following::td[1]</value>
      <webElementGuid>4a9edebf-e984-4abc-acc3-69d1bb1d717a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescription Taken?'])[1]/following::td[1]</value>
      <webElementGuid>b5e69f10-4e56-42db-8ba1-37d453a6a17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aspirin, 10, , Once Immediately'])[1]/preceding::td[1]</value>
      <webElementGuid>c5a8fb87-b222-46cb-9879-fc23ba13774b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Purpose'])[1]/preceding::td[2]</value>
      <webElementGuid>1ddcb8af-1041-471a-a37e-cca0b13b0e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01/15/2025']/parent::*</value>
      <webElementGuid>46773032-0f61-4667-9e62-694d85f5ae1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td</value>
      <webElementGuid>5880b376-47eb-4e08-b17f-7456be452f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '01/15/2025' or . = '01/15/2025')]</value>
      <webElementGuid>8ff02e45-2071-48cc-9ea0-2e9cc409beb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
