<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Duricef</name>
   <tag></tag>
   <elementGuidId>610fa4f2-8f74-4fbb-a8ba-db2fb06ee289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cm_medication_cell228</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='cm_medication_cell228']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Duricef&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f05ad82e-517a-46d0-a6fa-22e92b85b54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cm_medication_cell228</value>
      <webElementGuid>1d9d8dd5-14e8-45ae-aedb-764b1d648f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Duricef
                                                        
                        </value>
      <webElementGuid>f3bd3a7b-3ac8-4a1a-bac3-373e86b97db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cm_medication_cell228&quot;)</value>
      <webElementGuid>71f3dcd8-b7d7-4a18-adf6-69d1655dd6af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='cm_medication_cell228']</value>
      <webElementGuid>17ebf2a7-df24-411b-89da-2781a3bf0c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cmedrow228']/td</value>
      <webElementGuid>f2ce62b5-6b41-4fe8-a8e7-3665bc6f4fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review'])[1]/following::td[1]</value>
      <webElementGuid>01008f4c-86c1-4f86-a6a7-fbac92975f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disposition'])[1]/following::td[1]</value>
      <webElementGuid>356266c7-bf31-4bfb-ab0b-53a33e8940cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasal'])[1]/preceding::td[3]</value>
      <webElementGuid>843bce84-5e37-4393-b9d2-56f73e594ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stored/Verified'])[1]/preceding::td[6]</value>
      <webElementGuid>f0a753e2-b824-40ab-a4b0-656d4b4ff04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Duricef']/parent::*</value>
      <webElementGuid>b7bf126e-a383-4f72-8f29-2af3429fdca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td</value>
      <webElementGuid>720ef204-8bc4-4862-aa5b-55df15197689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'cm_medication_cell228' and (text() = '
                            Duricef
                                                        
                        ' or . = '
                            Duricef
                                                        
                        ')]</value>
      <webElementGuid>4a2baa10-c8df-438b-94ee-c209ecb53b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
